using System;
using System.Collections.Generic;
using Xunit;

namespace Parsek.Tests
{
    // Covers the link between a tree's main mission (Missions window) and its root group
    // (Recordings window): renaming either renames both, the auto "/ Debris" + "/ Crew" subgroups
    // cascade, a name collision refuses the whole rename, clones rename alone, and a fresh tree's
    // default mission is seeded from the root group name. See MissionGroupLink / MissionStore.
    [Collection("Sequential")]
    public class MissionGroupLinkTests : IDisposable
    {
        private readonly List<string> logLines = new List<string>();

        public MissionGroupLinkTests()
        {
            RecordingStore.SuppressLogging = false;
            RecordingStore.ResetForTesting();
            MissionStore.SuppressLogging = false;
            MissionStore.ResetForTesting();
            MilestoneStore.ResetForTesting();
            GameStateStore.SuppressLogging = true;
            ParsekLog.ResetTestOverrides();
            ParsekLog.SuppressLogging = false;
            ParsekLog.TestSinkForTesting = line => logLines.Add(line);
            GroupHierarchyStore.ResetGroupsForTesting();
            CrewReservationManager.ResetReplacementsForTesting();
            ParsekScenario.SetInstanceForTesting(null);
        }

        public void Dispose()
        {
            ParsekLog.ResetTestOverrides();
            ParsekLog.SuppressLogging = true;
            RecordingStore.SuppressLogging = true;
            RecordingStore.ResetForTesting();
            MissionStore.SuppressLogging = true;
            MissionStore.ResetForTesting();
            GroupHierarchyStore.ResetGroupsForTesting();
            CrewReservationManager.ResetReplacementsForTesting();
            ParsekScenario.SetInstanceForTesting(null);
        }

        private static Recording MakeRec(string id, string name, string treeId,
            bool isDebris = false, string evaCrewName = null)
        {
            return new Recording
            {
                RecordingId = id,
                VesselName = name,
                TreeId = treeId,
                IsDebris = isDebris,
                EvaCrewName = evaCrewName,
                Points = new List<TrajectoryPoint>
                {
                    new TrajectoryPoint { ut = 100.0 },
                    new TrajectoryPoint { ut = 200.0 }
                }
            };
        }

        // Commits a tree (running auto-grouping) and ensures its default main mission exists.
        private static RecordingTree CommitTreeWithMission(string treeId, string treeName, params Recording[] recs)
        {
            var tree = new RecordingTree
            {
                Id = treeId,
                TreeName = treeName,
                RootRecordingId = recs[0].RecordingId
            };
            foreach (var r in recs)
                tree.Recordings[r.RecordingId] = r;
            RecordingStore.CommitTree(tree);
            MissionStore.EnsureDefaultsForTrees(RecordingStore.CommittedTrees);
            return RecordingStore.CommittedTrees.Find(t => t.Id == treeId);
        }

        [Fact]
        public void RenameRootGroup_RenamesMainMission_AndCascadesSubgroups()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var debris = MakeRec("deb", "Booster", "t1", isDebris: true);
            debris.ParentRecordingId = root.RecordingId;
            var crew = MakeRec("crew", "Jeb", "t1", evaCrewName: "Jeb");
            crew.ParentRecordingId = root.RecordingId;
            var tree = CommitTreeWithMission("t1", "Kerbal X", root, debris, crew);

            // Align-at-creation: the default mission was seeded from the root group name.
            Assert.Equal("Kerbal X", tree.AutoGeneratedRootGroupName);
            Assert.Equal("Kerbal X", MissionStore.FindOriginalMission("t1").Name);

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "Duna One", out string reason));
            Assert.Null(reason);

            // Root + both subgroups renamed on the tree metadata...
            Assert.Equal("Duna One", tree.AutoGeneratedRootGroupName);
            Assert.Equal("Duna One / Debris", tree.AutoGeneratedDebrisGroupName);
            Assert.Equal("Duna One / Crew", tree.AutoGeneratedCrewGroupName);
            // ...on the recording tags...
            Assert.Contains("Duna One", root.RecordingGroups);
            Assert.Contains("Duna One / Debris", debris.RecordingGroups);
            Assert.Contains("Duna One / Crew", crew.RecordingGroups);
            // ...and the linked main mission.
            Assert.Equal("Duna One", MissionStore.FindOriginalMission("t1").Name);

            Assert.Contains(logLines, l =>
                l.Contains("RenameMissionGroup") && l.Contains("main mission synced"));
        }

        [Fact]
        public void Rename_ToExistingGroupName_RejectsAndLeavesEverythingUnchanged()
        {
            var a = MakeRec("a", "Alpha", "ta");
            var ta = CommitTreeWithMission("ta", "Alpha", a);
            var b = MakeRec("b", "Beta", "tb");
            var tb = CommitTreeWithMission("tb", "Beta", b);

            Assert.False(MissionGroupLink.RenameMissionGroup(ta, "Beta", out string reason));
            Assert.Contains("already exists", reason);

            // Nothing moved on either side.
            Assert.Equal("Alpha", ta.AutoGeneratedRootGroupName);
            Assert.Equal("Alpha", MissionStore.FindOriginalMission("ta").Name);
            Assert.Contains("Alpha", a.RecordingGroups);
            Assert.Equal("Beta", tb.AutoGeneratedRootGroupName);
            Assert.Equal("Beta", MissionStore.FindOriginalMission("tb").Name);
        }

        [Fact]
        public void Rename_OnlyTouchesMainMission_NotClones()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var tree = CommitTreeWithMission("t1", "Kerbal X", root);
            Mission main = MissionStore.FindOriginalMission("t1");
            Mission clone = MissionStore.Clone(main);

            Assert.True(MissionStore.IsOriginalMission(main));
            Assert.False(MissionStore.IsOriginalMission(clone));

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "Duna One", out _));

            Assert.Equal("Duna One", main.Name);
            Assert.Equal("Kerbal X copy", clone.Name); // clone untouched
            Assert.Equal("Duna One", tree.AutoGeneratedRootGroupName);
        }

        [Fact]
        public void Rename_LeavesUserRenamedSubgroupAlone()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var debris = MakeRec("deb", "Booster", "t1", isDebris: true);
            debris.ParentRecordingId = root.RecordingId;
            var tree = CommitTreeWithMission("t1", "Kerbal X", root, debris);

            // User gives the debris subgroup a bespoke name first (no longer "<root> / Debris").
            Assert.True(RecordingStore.RenameGroup("Kerbal X / Debris", "Scraps"));
            GroupHierarchyStore.RenameGroupInHierarchy("Kerbal X / Debris", "Scraps");
            Assert.Equal("Scraps", tree.AutoGeneratedDebrisGroupName);

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "Duna One", out _));

            Assert.Equal("Duna One", tree.AutoGeneratedRootGroupName);
            Assert.Equal("Scraps", tree.AutoGeneratedDebrisGroupName); // bespoke child preserved
            Assert.Contains("Scraps", debris.RecordingGroups);
        }

        [Fact]
        public void EnsureDefaults_SeedsNameFromRootGroup_WhenPresent()
        {
            // A second "Kerbal X" launch whose folder deduped to "Kerbal X #2": the default mission
            // must be born matching the folder, not the raw tree name.
            var tree = new RecordingTree
            {
                Id = "t1",
                TreeName = "Kerbal X",
                AutoGeneratedRootGroupName = "Kerbal X #2"
            };
            RecordingStore.CommittedTrees.Add(tree);

            Assert.Equal(1, MissionStore.EnsureDefaultsForTrees(RecordingStore.CommittedTrees));
            Assert.Equal("Kerbal X #2", MissionStore.FindOriginalMission("t1").Name);
        }

        [Fact]
        public void Rename_NoRootGroup_RenamesMainMissionOnly()
        {
            // Tree committed-but-not-grouped (or in flight): no root group, but a mission exists.
            var tree = new RecordingTree { Id = "t1", TreeName = "Kerbal X" };
            RecordingStore.CommittedTrees.Add(tree);
            MissionStore.EnsureDefaultsForTrees(RecordingStore.CommittedTrees);
            Assert.Equal("Kerbal X", MissionStore.FindOriginalMission("t1").Name);

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "Renamed", out string reason));
            Assert.Null(reason);
            Assert.Equal("Renamed", MissionStore.FindOriginalMission("t1").Name);
            Assert.True(string.IsNullOrEmpty(tree.AutoGeneratedRootGroupName)); // still no group
            Assert.Contains(logLines, l =>
                l.Contains("RenameMissionGroup") && l.Contains("has no root group"));
        }

        [Fact]
        public void Rename_CaseOnly_FlipsCase_NotTreatedAsNoOp()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var tree = CommitTreeWithMission("t1", "Kerbal X", root);

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "kerbal x", out string reason));
            Assert.Null(reason);
            Assert.Equal("kerbal x", tree.AutoGeneratedRootGroupName);
            Assert.Equal("kerbal x", MissionStore.FindOriginalMission("t1").Name);
            Assert.Contains("kerbal x", root.RecordingGroups);
            Assert.DoesNotContain("Kerbal X", root.RecordingGroups);
        }

        [Fact]
        public void Rename_ToCurrentRootName_SyncsMainMission()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var tree = CommitTreeWithMission("t1", "Kerbal X", root);
            // Simulate a drifted main mission name, then rename the group to its current name.
            Mission main = MissionStore.FindOriginalMission("t1");
            main.Name = "Drifted";

            Assert.True(MissionGroupLink.RenameMissionGroup(tree, "Kerbal X", out string reason));
            Assert.Null(reason);
            Assert.Equal("Kerbal X", tree.AutoGeneratedRootGroupName); // unchanged
            Assert.Equal("Kerbal X", main.Name); // mission re-synced to the root
        }

        [Fact]
        public void FindTreeByRootGroup_MatchesRootOnly()
        {
            var root = MakeRec("root", "Kerbal X", "t1");
            var debris = MakeRec("deb", "Booster", "t1", isDebris: true);
            debris.ParentRecordingId = root.RecordingId;
            var tree = CommitTreeWithMission("t1", "Kerbal X", root, debris);

            Assert.Same(tree, MissionGroupLink.FindTreeByRootGroup("Kerbal X"));
            Assert.True(MissionGroupLink.IsMissionRootGroup("Kerbal X"));
            // A subgroup or an unknown name is not a mission root group.
            Assert.Null(MissionGroupLink.FindTreeByRootGroup("Kerbal X / Debris"));
            Assert.Null(MissionGroupLink.FindTreeByRootGroup("Nonexistent"));
            Assert.False(MissionGroupLink.IsMissionRootGroup("Kerbal X / Debris"));
        }
    }
}
