using System;
using System.Collections.Generic;
using Xunit;

namespace Parsek.Tests
{
    /// <summary>
    /// Phase 5 of Rewind-to-Staging (design §7.30 / §7.25). Guards
    /// <see cref="GroupHierarchyStore.CanHide"/> and
    /// <see cref="GroupHierarchyStore.IsDropTargetAllowed"/> — the two
    /// system-group gates surfaced in Phase 5 Commit 2.
    /// </summary>
    [Collection("Sequential")]
    public class UnfinishedFlightsGroupCannotHideTests : IDisposable
    {
        private readonly List<string> logLines = new List<string>();
        private readonly bool priorParsekLogSuppress;
        private readonly bool priorStoreSuppress;

        public UnfinishedFlightsGroupCannotHideTests()
        {
            priorParsekLogSuppress = ParsekLog.SuppressLogging;
            priorStoreSuppress = RecordingStore.SuppressLogging;
            ParsekLog.ResetTestOverrides();
            ParsekLog.SuppressLogging = false;
            RecordingStore.SuppressLogging = true;
            ParsekLog.VerboseOverrideForTesting = true;
            ParsekLog.TestSinkForTesting = line => logLines.Add(line);

            RecordingStore.ResetForTesting();
            GroupHierarchyStore.ResetGroupsForTesting();
        }

        public void Dispose()
        {
            ParsekLog.ResetTestOverrides();
            ParsekLog.SuppressLogging = priorParsekLogSuppress;
            RecordingStore.SuppressLogging = priorStoreSuppress;
            RecordingStore.ResetForTesting();
            GroupHierarchyStore.ResetGroupsForTesting();
        }

        // =====================================================================
        // CanHide (design §7.30)
        // =====================================================================

        [Fact]
        public void CanHide_UnfinishedFlights_False()
        {
            // Regression: the virtual Unfinished Flights group must never
            // be hideable — the list is a diagnostic of the player's
            // unresolved split siblings, so "out of sight" is not a
            // permitted UX outcome.
            Assert.False(GroupHierarchyStore.CanHide(UnfinishedFlightsGroup.GroupName));
        }

        [Fact]
        public void CanHide_UserGroup_True()
        {
            // Regression: user-defined groups are still hide-eligible. The
            // gate only rejects system groups.
            Assert.True(GroupHierarchyStore.CanHide("MyUserGroup"));
        }

        [Fact]
        public void CanHide_AutoGeneratedTreeGroup_True()
        {
            // Regression: auto-generated group names (e.g. tree-derived
            // "Vessel N flights") are indistinguishable from user groups at
            // the store level and must remain hide-eligible.
            Assert.True(GroupHierarchyStore.CanHide("Vessel 1 flights"));
        }

        [Fact]
        public void CanHide_EmptyOrNullName_False()
        {
            // Regression: defensive — null / empty names are not valid
            // groups at all; the store returns false rather than throwing.
            Assert.False(GroupHierarchyStore.CanHide(null));
            Assert.False(GroupHierarchyStore.CanHide(""));
        }

        // =====================================================================
        // IsDropTargetAllowed (design §7.25)
        // =====================================================================

        [Fact]
        public void IsDropTargetAllowed_UnfinishedFlights_False()
        {
            // Regression: system groups must reject drag-into attempts so
            // the group-picker popup cannot route a recording into the
            // virtual group.
            Assert.False(GroupHierarchyStore.IsDropTargetAllowed(UnfinishedFlightsGroup.GroupName));
        }

        [Fact]
        public void IsDropTargetAllowed_UserGroup_True()
        {
            // Regression: user-defined groups remain valid drop targets —
            // the virtual-group gate is a narrow exception.
            Assert.True(GroupHierarchyStore.IsDropTargetAllowed("MyUserGroup"));
        }

        [Fact]
        public void IsDropTargetAllowed_EmptyOrNullName_False()
        {
            // Regression: defensive. Empty / null target names must not
            // throw; they are simply not valid drop targets.
            Assert.False(GroupHierarchyStore.IsDropTargetAllowed(null));
            Assert.False(GroupHierarchyStore.IsDropTargetAllowed(""));
        }
    }
}
