using System;
using System.Collections.Generic;

namespace Parsek
{
    // Static store of player-defined Missions, surviving scene changes and persisted
    // through ParsekScenario OnSave/OnLoad. Every committed tree always has at least
    // one Mission (a default, all-included), and Delete is blocked on a tree's last
    // Mission, so a tree is never left without one. See Mission / MissionsWindowUI.
    internal static class MissionStore
    {
        private static readonly List<Mission> missions = new List<Mission>();

        internal static bool SuppressLogging;

        // Global "Archive" toggle for the Missions window: when true, archived missions are
        // hidden from the list (mirrors the recordings window's GroupHierarchyStore.HideActive).
        // Persisted alongside the missions so the view state survives a reload.
        internal static bool HideArchived;

        internal static IReadOnlyList<Mission> Missions => missions;

        internal static void ResetForTesting()
        {
            missions.Clear();
            HideArchived = false;
        }

        internal static int CountForTree(string treeId)
        {
            int n = 0;
            for (int i = 0; i < missions.Count; i++)
                if (missions[i].TreeId == treeId)
                    n++;
            return n;
        }

        /// <summary>
        /// Creates an all-included default Mission for any tree that has none. Returns
        /// the number created. Idempotent: a no-op once every tree has a Mission.
        /// </summary>
        internal static int EnsureDefaultsForTrees(IEnumerable<RecordingTree> trees)
        {
            if (trees == null)
                return 0;
            int created = 0;
            foreach (var tree in trees)
            {
                if (tree == null || string.IsNullOrEmpty(tree.Id))
                    continue;
                if (CountForTree(tree.Id) > 0)
                    continue;
                // A tree's default (main) mission IS its Recordings-window folder presented in the
                // Missions view, so seed the name from the tree's root group name when it has one.
                // That keeps the two in lockstep from creation: a second "Kerbal X" launch whose
                // folder dedups to "Kerbal X #2" gets a "Kerbal X #2" mission, not a mismatched
                // "Kerbal X". Falls back to the raw tree name, then a generic "Mission".
                string name = !string.IsNullOrEmpty(tree.AutoGeneratedRootGroupName)
                    ? tree.AutoGeneratedRootGroupName
                    : (string.IsNullOrEmpty(tree.TreeName) ? "Mission" : tree.TreeName);
                missions.Add(new Mission(Guid.NewGuid().ToString("N"), tree.Id, name));
                created++;
            }
            if (created > 0 && !SuppressLogging)
                ParsekLog.Verbose("Mission", $"EnsureDefaultsForTrees: created {created} default mission(s)");
            return created;
        }

        /// <summary>
        /// Removes Missions whose tree no longer exists. Returns count removed.
        /// <para>
        /// <paramref name="additionalLiveTreeIds"/> protects trees that exist but are NOT in
        /// the committed list at call time - chiefly a quickload-resume tree parked in the
        /// pending-Limbo slot or still serialized as an isActive / isPending RECORDING_TREE
        /// node that <c>TryRestoreActiveTreeNode</c> restores LATER in the same OnLoad (mission
        /// reconcile runs before that restore). Without it, a mission whose tree is merely
        /// parked would be pruned and the player's mission name + loop settings lost even
        /// though the tree itself survives - the second half of the Limbo-tree data-loss bug.
        /// </para>
        /// </summary>
        internal static int PruneOrphans(
            IEnumerable<RecordingTree> trees,
            IEnumerable<string> additionalLiveTreeIds = null)
        {
            var live = new HashSet<string>(StringComparer.Ordinal);
            if (trees != null)
                foreach (var tree in trees)
                    if (tree != null && !string.IsNullOrEmpty(tree.Id))
                        live.Add(tree.Id);
            if (additionalLiveTreeIds != null)
                foreach (var id in additionalLiveTreeIds)
                    if (!string.IsNullOrEmpty(id))
                        live.Add(id);

            int removed = missions.RemoveAll(
                m => m == null || string.IsNullOrEmpty(m.TreeId) || !live.Contains(m.TreeId));
            if (removed > 0 && !SuppressLogging)
                ParsekLog.Verbose("Mission", $"PruneOrphans: removed {removed} mission(s) for missing trees");
            return removed;
        }

        /// <summary>
        /// Drops stale selection ids from every Mission's excluded sets when the underlying tree
        /// topology has changed (a branch/segment was edited away, re-flown, or merged out):
        /// <list type="bullet">
        /// <item><see cref="Mission.ExcludedThroughLineHeadIds"/> ids that are no longer a current
        /// through-line head; and</item>
        /// <item><see cref="Mission.ExcludedIntervalKeys"/> keys that are no longer a selectable
        /// composition node (the keys are composition node HeadLegIds, including synthetic
        /// <c>&lt;head&gt;/segN</c> sub-segment ids whose N shifts when the structural-peel count
        /// changes - a stale /segN would otherwise silently re-target a DIFFERENT segment).</item>
        /// </list>
        /// A stale exclusion would otherwise silently re-include / mis-target a piece the player had
        /// dropped, so this fails loudly with a warn. Builds each tree's structure / view /
        /// composition at most once and reuses them across Missions that share the tree. Returns the
        /// total number of ids removed across all Missions.
        /// <para>
        /// M-MIS-5 (D3): this is also the one-time selection-schema upgrade seam. A generation-0
        /// mission (loaded from a pre-M-MIS-5 save) authored its excluded interval keys when a
        /// structural key covered the WHOLE structural interval, docked stretch included; the dock
        /// edges mint "@dockM" sub-intervals inside that span, which would silently re-render. So
        /// for generation-0 missions every excluded key is EXTENDED across its @dock sub-siblings
        /// (against the SAME composition-derived valid-key set the stale-dropper uses, BEFORE
        /// stale-dropping - semantics-preserving and idempotent, a superset union), then EVERY
        /// mission whose tree resolves is stamped to the current generation UNCONDITIONALLY,
        /// including empty-exclusion missions (so a later deliberate pre-dock-only exclusion is
        /// never wrongly extended). Missions whose tree is not committed yet (a parked Limbo /
        /// quickload-resume tree restored later in OnLoad) keep their generation so a later
        /// reconcile with the tree present still performs the extension.
        /// </para>
        /// </summary>
        internal static int ReconcileSelections(
            IEnumerable<RecordingTree> trees,
            IEnumerable<string> additionalLiveTreeIds = null)
        {
            var byId = new Dictionary<string, RecordingTree>(StringComparer.Ordinal);
            var allTreesList = new List<RecordingTree>();
            if (trees != null)
                foreach (var tree in trees)
                    if (tree != null && !string.IsNullOrEmpty(tree.Id))
                    {
                        byId[tree.Id] = tree;
                        allTreesList.Add(tree);
                    }

            // M-MIS-8: a PARKED tree (quickload-resume isActive/isPending node restored LATER in
            // this OnLoad - the same population PruneOrphans protects) may be the FOREIGN tree a
            // dock link points into. Link derivation cannot see it yet, and a stale link id does
            // not name its tree, so while any parked tree is uncommitted the link validation +
            // the linked missions' interval-key stale-drop are DEFERRED wholesale (mirrors the
            // generation-stamp deferral); the next reconcile with the tree committed re-runs it.
            bool parkedUncommittedExists = false;
            if (additionalLiveTreeIds != null)
                foreach (var id in additionalLiveTreeIds)
                    if (!string.IsNullOrEmpty(id) && !byId.ContainsKey(id))
                    {
                        parkedUncommittedExists = true;
                        break;
                    }

            var structureCache = new Dictionary<string, MissionStructure>(StringComparer.Ordinal);
            var viewCache = new Dictionary<string, MissionThroughLineView>(StringComparer.Ordinal);
            var intervalKeyCache = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
            // M-MIS-8: derived cross-tree dock links per mission tree (reused across same-tree
            // missions), and foreign composition roots per foreign tree.
            var linksCache = new Dictionary<string, List<ForeignDockLink>>(StringComparer.Ordinal);
            var compRootsCache = new Dictionary<string, List<MissionCompositionNode>>(StringComparer.Ordinal);
            int removedHeads = 0;
            int removedIntervals = 0;
            int removedLinks = 0;
            int linkReconcileDeferred = 0;
            int stamped = 0;
            int extendedMissions = 0;
            int extendedKeys = 0;
            int stampDeferredNoTree = 0;
            for (int i = 0; i < missions.Count; i++)
            {
                Mission m = missions[i];
                if (m == null || string.IsNullOrEmpty(m.TreeId))
                    continue;
                bool isLegacyGeneration =
                    m.SelectionSchemaGeneration < Mission.CurrentSelectionSchemaGeneration;
                if (!byId.TryGetValue(m.TreeId, out RecordingTree tree))
                {
                    // Tree not committed yet (parked Limbo / restored later this OnLoad): defer
                    // the stamp so the @dock extension still runs once the tree is present.
                    // M-MIS-8: link ids are likewise left untouched until the tree is present.
                    if (isLegacyGeneration)
                        stampDeferredNoTree++;
                    continue;
                }

                // M-MIS-8: validate included cross-tree dock links FIRST (they extend the
                // valid-interval-key set below). A link that no longer derives (foreign tree /
                // branch point gone, claim no longer matches) is dropped like any stale id;
                // surviving links contribute their partner-journey selectable keys so a
                // cross-seam exclusion is not wrongly dropped as stale. While a parked tree is
                // uncommitted the whole cross-tree reconcile (link drop + this mission's
                // interval-key stale-drop) is deferred - the parked tree may be the link's
                // foreign tree, and dropping now would permanently lose the player's selection.
                bool deferCrossTree = m.IncludedForeignDockLinkIds.Count > 0
                    && parkedUncommittedExists;
                if (deferCrossTree)
                    linkReconcileDeferred++;
                HashSet<string> foreignValidKeys = null;
                if (m.IncludedForeignDockLinkIds.Count > 0 && !deferCrossTree)
                {
                    if (!linksCache.TryGetValue(m.TreeId, out List<ForeignDockLink> links))
                    {
                        links = MissionCrossTreeDock.FindLinks(tree, allTreesList);
                        linksCache[m.TreeId] = links;
                    }
                    var validLinkIds = new HashSet<string>(StringComparer.Ordinal);
                    for (int l = 0; l < links.Count; l++)
                        validLinkIds.Add(links[l].LinkId);
                    removedLinks += RemoveStale(m.IncludedForeignDockLinkIds, validLinkIds.Contains);

                    for (int l = 0; l < links.Count; l++)
                    {
                        ForeignDockLink link = links[l];
                        if (!m.IncludedForeignDockLinkIds.Contains(link.LinkId)
                            || !byId.TryGetValue(link.ForeignTreeId, out RecordingTree foreignTree))
                            continue;
                        if (!structureCache.TryGetValue(foreignTree.Id, out MissionStructure fs))
                        {
                            fs = MissionStructureBuilder.Build(foreignTree);
                            structureCache[foreignTree.Id] = fs;
                        }
                        if (!viewCache.TryGetValue(foreignTree.Id, out MissionThroughLineView fv))
                        {
                            fv = MissionThroughLineBuilder.Build(fs);
                            viewCache[foreignTree.Id] = fv;
                        }
                        if (!compRootsCache.TryGetValue(foreignTree.Id, out List<MissionCompositionNode> fRoots))
                        {
                            fRoots = MissionCompositionBuilder.Build(fs);
                            compRootsCache[foreignTree.Id] = fRoots;
                        }
                        var journeySet = new HashSet<string>(
                            MissionCrossTreeDock.ComputePartnerJourneyLegIds(foreignTree, link),
                            StringComparer.Ordinal);
                        var journeyWindows = MissionCrossTreeDock.ComputeJourneyWindowsByOwner(
                            fs, fv, journeySet);
                        if (foreignValidKeys == null)
                            foreignValidKeys = new HashSet<string>(StringComparer.Ordinal);
                        MissionCrossTreeDock.CollectJourneySelectableKeys(
                            fRoots, journeyWindows, foreignValidKeys);
                    }
                }

                bool hasHeadExcl = m.ExcludedThroughLineHeadIds.Count > 0;
                bool hasIntervalExcl = m.ExcludedIntervalKeys.Count > 0;

                if (hasHeadExcl || hasIntervalExcl)
                {
                    if (!structureCache.TryGetValue(m.TreeId, out MissionStructure structure))
                    {
                        structure = MissionStructureBuilder.Build(tree);
                        structureCache[m.TreeId] = structure;
                    }

                    if (hasHeadExcl)
                    {
                        if (!viewCache.TryGetValue(m.TreeId, out MissionThroughLineView view))
                        {
                            view = MissionThroughLineBuilder.Build(structure);
                            viewCache[m.TreeId] = view;
                        }
                        removedHeads += RemoveStale(m.ExcludedThroughLineHeadIds,
                            id => view.ByHeadId.ContainsKey(id));
                    }

                    if (hasIntervalExcl)
                    {
                        if (!intervalKeyCache.TryGetValue(m.TreeId, out HashSet<string> validKeys))
                        {
                            validKeys = new HashSet<string>(StringComparer.Ordinal);
                            CollectSelectableHeadLegIds(MissionCompositionBuilder.Build(structure), validKeys);
                            intervalKeyCache[m.TreeId] = validKeys;
                        }
                        // D3 generation-0 extension: BEFORE stale-dropping, against the SAME
                        // valid-key set, so a still-valid key gains its @dock sub-siblings before
                        // anything is removed.
                        if (isLegacyGeneration)
                        {
                            int added = ExtendLegacyExclusionsAcrossDockSubIntervals(
                                m.ExcludedIntervalKeys, validKeys);
                            if (added > 0)
                            {
                                extendedMissions++;
                                extendedKeys += added;
                                if (!SuppressLogging)
                                    ParsekLog.Info("Mission",
                                        $"ReconcileSelections: mission '{m.Name}' (tree={m.TreeId}) " +
                                        $"generation-0 selection extended across {added} @dock " +
                                        "sub-interval key(s) (a pre-M-MIS-5 exclusion covered the " +
                                        "whole structural interval, docked stretch included)");
                            }
                        }
                        // M-MIS-8: a key is still valid when it is a current OWN-tree selectable
                        // key OR a current partner-journey key of a surviving included link. A
                        // deferred cross-tree reconcile (parked tree) skips the stale-drop for
                        // this mission entirely - the foreign key population cannot be derived
                        // yet, so nothing may be judged stale this pass.
                        if (!deferCrossTree)
                        {
                            HashSet<string> fKeys = foreignValidKeys;
                            removedIntervals += RemoveStale(m.ExcludedIntervalKeys,
                                key => validKeys.Contains(key)
                                       || (fKeys != null && fKeys.Contains(key)));
                        }
                    }
                }

                // D3 (verdict C3b): stamp UNCONDITIONALLY for every tree-resolvable mission,
                // including empty-exclusion ones (no extension work for those, stamp only) - a
                // generation-0 mission left unstamped would have a later deliberate pre-dock-only
                // exclusion wrongly extended on the next load.
                if (isLegacyGeneration)
                {
                    m.SelectionSchemaGeneration = Mission.CurrentSelectionSchemaGeneration;
                    stamped++;
                }
            }

            // Logged whenever any generation-0 mission was touched OR deferred: a deferred-only
            // pass (every legacy mission's tree still uncommitted) must still be visible.
            if ((stamped > 0 || stampDeferredNoTree > 0) && !SuppressLogging)
                ParsekLog.Info("Mission",
                    $"ReconcileSelections: stamped {stamped} mission(s) to selection schema " +
                    $"generation {Mission.CurrentSelectionSchemaGeneration} ({extendedMissions} " +
                    $"extended with {extendedKeys} @dock key(s); {stampDeferredNoTree} deferred, " +
                    "tree not committed yet)");

            if (linkReconcileDeferred > 0 && !SuppressLogging)
                ParsekLog.Info("Mission",
                    $"ReconcileSelections: deferred cross-tree link reconcile for " +
                    $"{linkReconcileDeferred} mission(s) (a parked tree is not committed yet; " +
                    "re-runs once it is)");

            int removed = removedHeads + removedIntervals + removedLinks;
            if (removed > 0 && !SuppressLogging)
                ParsekLog.Warn("Mission",
                    $"ReconcileSelections: removed {removedHeads} stale through-line head id(s) + " +
                    $"{removedIntervals} stale interval key(s) + {removedLinks} stale cross-tree " +
                    "dock link id(s) (no longer current after a topology change; cleared to avoid " +
                    "silently dropping / mis-targeting segments)");
            return removed;
        }

        // M-MIS-5 (D3): adds every valid "<parentKey>@dockM" sub-interval key whose parent key is
        // already excluded. Pre-M-MIS-5 the parent key covered the whole structural interval, so
        // extending across the new sub-siblings exactly preserves the old selection's meaning.
        // Superset union: idempotent across a crash-and-reload re-run. Returns the count added.
        private static int ExtendLegacyExclusionsAcrossDockSubIntervals(
            HashSet<string> excluded, HashSet<string> validKeys)
        {
            int added = 0;
            foreach (string validKey in validKeys)
            {
                int marker = validKey.IndexOf("@dock", StringComparison.Ordinal);
                if (marker <= 0)
                    continue;
                string parentKey = validKey.Substring(0, marker);
                if (excluded.Contains(parentKey) && excluded.Add(validKey))
                    added++;
            }
            return added;
        }

        // Removes from <paramref name="excluded"/> every id for which <paramref name="isStillValid"/>
        // returns false. Returns the count removed.
        private static int RemoveStale(HashSet<string> excluded, Func<string, bool> isStillValid)
        {
            List<string> stale = null;
            foreach (string id in excluded)
                if (!isStillValid(id))
                    (stale ?? (stale = new List<string>())).Add(id);
            if (stale == null)
                return 0;
            for (int s = 0; s < stale.Count; s++)
                excluded.Remove(stale[s]);
            return stale.Count;
        }

        // Collects the HeadLegId of every SELECTABLE composition node (intervals / branches that
        // carry an include checkbox; not roster atoms) into <paramref name="into"/>, recursing into
        // children. These are exactly the keys a Mission may hold in ExcludedIntervalKeys.
        private static void CollectSelectableHeadLegIds(
            IReadOnlyList<MissionCompositionNode> nodes, HashSet<string> into)
        {
            if (nodes == null)
                return;
            for (int i = 0; i < nodes.Count; i++)
            {
                MissionCompositionNode n = nodes[i];
                if (n == null)
                    continue;
                if (n.IsSelectable && !string.IsNullOrEmpty(n.HeadLegId))
                    into.Add(n.HeadLegId);
                CollectSelectableHeadLegIds(n.Children, into);
            }
        }

        /// <summary>
        /// Enables or disables loop playback on a Mission. Multiple Missions may loop at once, but
        /// at most ONE per recording tree: enabling <paramref name="target"/> turns off any other
        /// looping Mission that shares its <see cref="Mission.TreeId"/>, while leaving looping
        /// Missions on OTHER trees untouched. (Two Missions on the same tree are variant selections
        /// that share trunk legs before any fork, so their committed-recording indices overlap and
        /// cannot each own a span clock; Missions on different trees have disjoint indices and loop
        /// concurrently with no conflict.) Enabling also stamps <see cref="Mission.LoopAnchorUT"/>
        /// to <paramref name="currentUT"/> so the span clock phases from this moment: every enable
        /// (including the first, and every re-enable after a disable) restarts the looped mission
        /// from the recording's start instead of resuming mid-phase. Disabling only clears the
        /// target's flag and leaves the stale anchor in place (the next enable overwrites it).
        /// </summary>
        internal static void SetLoopEnabled(Mission target, bool on, double currentUT,
            IReadOnlyList<RecordingTree> trees = null)
        {
            if (target == null)
                return;
            if (on)
            {
                ClearLoopsConflictingWith(target, trees, out int clearedSameTree,
                    out int clearedCrossTree, "SetLoopEnabled");
                target.LoopPlayback = true;
                target.LoopAnchorUT = currentUT;
                if (!SuppressLogging)
                    ParsekLog.Info("Mission",
                        $"SetLoopEnabled: loop ON for '{target.Name}' (tree={target.TreeId}); " +
                        $"anchorUT={currentUT.ToString("R", System.Globalization.CultureInfo.InvariantCulture)}; " +
                        $"cleared {clearedSameTree} other looping mission(s) on the same tree (one loop per tree)" +
                        (clearedCrossTree > 0 ? $" + {clearedCrossTree} on cross-tree-linked tree(s)" : ""));
            }
            else
            {
                target.LoopPlayback = false;
                if (!SuppressLogging)
                    ParsekLog.Info("Mission",
                        $"SetLoopEnabled: loop OFF for '{target.Name}' (tree={target.TreeId})");
            }
        }

        /// <summary>
        /// M-MIS-8: clears every OTHER looping mission that conflicts with
        /// <paramref name="target"/> - same-tree siblings (the original one-loop-per-tree rule),
        /// plus, when <paramref name="trees"/> is supplied, missions whose SPANNED tree sets
        /// (own tree + linked foreign trees) intersect the target's. Called by SetLoopEnabled on
        /// enable and by the Missions-window link toggle when a link is included on an
        /// ALREADY-LOOPING mission (including a link widens the span, which can newly conflict
        /// with a loop on the foreign tree). The target's own loop state is not touched.
        /// </summary>
        internal static void ClearLoopsConflictingWith(
            Mission target, IReadOnlyList<RecordingTree> trees,
            out int clearedSameTree, out int clearedCrossTree, string reason)
        {
            clearedSameTree = 0;
            clearedCrossTree = 0;
            if (target == null)
                return;
            // With no trees supplied (legacy callers / tests) the spanned set degenerates to
            // the own tree and the behavior is the original one-loop-per-tree clear.
            HashSet<string> targetSpan = ComputeSpannedTreeIds(target, trees);
            for (int i = 0; i < missions.Count; i++)
            {
                Mission m = missions[i];
                if (m == null || ReferenceEquals(m, target) || !m.LoopPlayback)
                    continue;
                // Only clear looping siblings whose spanned trees intersect; concurrent loops
                // on disjoint trees are allowed.
                if (string.Equals(m.TreeId, target.TreeId, StringComparison.Ordinal))
                {
                    m.LoopPlayback = false;
                    clearedSameTree++;
                    continue;
                }
                if (targetSpan.Count > 1 || m.IncludedForeignDockLinkIds.Count > 0)
                {
                    HashSet<string> mSpan = ComputeSpannedTreeIds(m, trees);
                    if (SpansIntersect(targetSpan, mSpan))
                    {
                        m.LoopPlayback = false;
                        clearedCrossTree++;
                        if (!SuppressLogging)
                            ParsekLog.Info("Mission",
                                $"{reason}: cleared looping mission '{m.Name}' " +
                                $"(tree={m.TreeId}) - its spanned trees intersect " +
                                $"'{target.Name}' via a cross-tree dock link");
                    }
                }
            }
        }

        // M-MIS-8: the set of tree ids a mission's loop unit spans - its own tree plus the
        // foreign tree of every included dock link that still derives. With no trees supplied
        // the set degenerates to the own tree (legacy behavior).
        internal static HashSet<string> ComputeSpannedTreeIds(
            Mission m, IReadOnlyList<RecordingTree> trees)
        {
            var span = new HashSet<string>(StringComparer.Ordinal);
            if (m == null)
                return span;
            if (!string.IsNullOrEmpty(m.TreeId))
                span.Add(m.TreeId);
            if (trees == null || m.IncludedForeignDockLinkIds.Count == 0)
                return span;
            RecordingTree myTree = null;
            for (int i = 0; i < trees.Count; i++)
                if (trees[i] != null && string.Equals(trees[i].Id, m.TreeId, StringComparison.Ordinal))
                {
                    myTree = trees[i];
                    break;
                }
            if (myTree == null)
                return span;
            List<ForeignDockLink> links = MissionCrossTreeDock.FindLinks(myTree, trees);
            for (int i = 0; i < links.Count; i++)
                if (m.IncludedForeignDockLinkIds.Contains(links[i].LinkId))
                    span.Add(links[i].ForeignTreeId);
            return span;
        }

        private static bool SpansIntersect(HashSet<string> a, HashSet<string> b)
        {
            foreach (string id in a)
                if (b.Contains(id))
                    return true;
            return false;
        }

        /// <summary>
        /// Enforces the one-loop-per-tree invariant after load. SetLoopEnabled keeps at most one
        /// Mission looping per tree during normal use, but a hand-edited save could carry several
        /// looping Missions that share a tree. Keeps the first in list order for each tree and
        /// clears the rest, so the adapter never builds two conflicting span clocks over the same
        /// (overlapping) committed indices. Looping Missions on distinct trees are all kept.
        /// M-MIS-8: with <paramref name="trees"/> supplied, the invariant generalizes to SPANNED
        /// tree sets (own tree + linked foreign trees) - a looping cross-tree-linked mission and
        /// a looping mission on its linked foreign tree conflict over the foreign tree's
        /// committed indices, so the later one in list order is cleared. Returns the number
        /// cleared.
        /// </summary>
        internal static int NormalizeOneLoopPerTree(IReadOnlyList<RecordingTree> trees = null)
        {
            var seenTrees = new HashSet<string>(StringComparer.Ordinal);
            int cleared = 0;
            for (int i = 0; i < missions.Count; i++)
            {
                Mission m = missions[i];
                if (m == null || !m.LoopPlayback)
                    continue;
                HashSet<string> span = ComputeSpannedTreeIds(m, trees);
                if (span.Count == 0)
                    span.Add(m.TreeId ?? string.Empty);
                if (SpansIntersect(span, seenTrees))
                {
                    m.LoopPlayback = false;
                    cleared++;
                    continue;
                }
                foreach (string id in span)
                    seenTrees.Add(id);
            }
            if (cleared > 0 && !SuppressLogging)
                ParsekLog.Warn("Mission",
                    $"NormalizeOneLoopPerTree: cleared {cleared} extra looping mission(s) " +
                    "(at most one Mission may loop per tree or spanned tree set; kept the " +
                    "first of each)");
            return cleared;
        }

        internal static Mission Clone(Mission source)
        {
            if (source == null)
                return null;
            Mission copy = source.Clone(Guid.NewGuid().ToString("N"));
            // Insert the copy directly after its source so a clone sits next to the
            // original it was made from (and shares its tree index in the UI). Falls
            // back to append if the source is somehow not in the list.
            int srcIdx = missions.IndexOf(source);
            if (srcIdx >= 0)
                missions.Insert(srcIdx + 1, copy);
            else
                missions.Add(copy);
            if (!SuppressLogging)
                ParsekLog.Info("Mission",
                    $"Cloned mission '{source.Name}' -> '{copy.Name}' (tree={source.TreeId})");
            return copy;
        }

        // Only a COPY can be deleted; the original mission of a tree is never deletable. The
        // original is the first mission in list order for the tree (the auto-created default;
        // clones are inserted after it). So a mission is deletable iff it is NOT the first mission
        // of its tree. This also keeps every tree with at least its original.
        internal static bool CanDelete(Mission m)
        {
            if (m == null)
                return false;
            for (int i = 0; i < missions.Count; i++)
            {
                if (missions[i] == null || missions[i].TreeId != m.TreeId)
                    continue;
                // First same-tree mission found: it is the original. Deletable only if it is not m.
                return !ReferenceEquals(missions[i], m);
            }
            return false;
        }

        internal static bool Delete(Mission m)
        {
            if (!CanDelete(m))
                return false;
            missions.Remove(m);
            if (!SuppressLogging)
                ParsekLog.Info("Mission", $"Deleted mission '{m.Name}' (tree={m.TreeId})");
            return true;
        }

        // The "main" mission of a tree: the first mission in list order for that tree (the
        // auto-created default / original, never a clone). This is the mission whose name is
        // linked to the tree's Recordings-window root group (see MissionGroupLink). Returns null
        // when the tree has no mission yet. Mirrors CanDelete's "first same-tree mission is the
        // original" rule.
        internal static Mission FindOriginalMission(string treeId)
        {
            if (string.IsNullOrEmpty(treeId))
                return null;
            for (int i = 0; i < missions.Count; i++)
                if (missions[i] != null
                    && string.Equals(missions[i].TreeId, treeId, StringComparison.Ordinal))
                    return missions[i];
            return null;
        }

        // True when m is its tree's original (main) mission, i.e. not a clone. Clones are inserted
        // after the original, so the original is always the first same-tree mission in list order.
        internal static bool IsOriginalMission(Mission m)
        {
            return m != null && ReferenceEquals(FindOriginalMission(m.TreeId), m);
        }

        // Sets a mission's display name. Used by the rename flows (including the linked
        // main-mission <-> group rename in MissionGroupLink). No-op when the name is blank or
        // unchanged. Mission names need not be unique (clones / different trees may share one),
        // so there is no collision check here; the group side enforces uniqueness.
        internal static void RenameMission(Mission m, string newName)
        {
            if (m == null || string.IsNullOrEmpty(newName) || string.Equals(m.Name, newName, StringComparison.Ordinal))
                return;
            string old = m.Name;
            m.Name = newName;
            if (!SuppressLogging)
                ParsekLog.Info("Mission", $"Renamed mission '{old}' -> '{newName}' (tree={m.TreeId})");
        }

        // --- Persistence (driven by ParsekScenario) ---

        internal static void Save(ConfigNode node)
        {
            node.RemoveValues("missionHideArchived");
            node.AddValue("missionHideArchived", HideArchived);
            // Purge the retired Missions-window size keys from older saves (the Missions view is now
            // a tab in the Recordings window and no longer persists its own size).
            node.RemoveValues("missionWindowWidth");
            node.RemoveValues("missionWindowHeight");
            node.RemoveNodes("MISSION");
            for (int i = 0; i < missions.Count; i++)
            {
                ConfigNode mNode = node.AddNode("MISSION");
                missions[i].Save(mNode);
            }
            if (!SuppressLogging)
                ParsekLog.Verbose("Mission", $"Saved {missions.Count} mission(s)");
        }

        internal static void Load(ConfigNode node)
        {
            missions.Clear();
            HideArchived = bool.TryParse(node.GetValue("missionHideArchived"), out bool hide) && hide;
            ConfigNode[] mNodes = node.GetNodes("MISSION");
            for (int i = 0; i < mNodes.Length; i++)
                missions.Add(Mission.Load(mNodes[i]));
            if (!SuppressLogging)
                ParsekLog.Info("Mission", $"Loaded {missions.Count} mission(s)");
        }
    }
}
