using System;
using System.Collections.Generic;

namespace Parsek
{
    // Keeps a recording tree's "mission" identity consistent across the two views that present
    // it: the root group/folder in the Recordings window (RecordingTree.AutoGeneratedRootGroupName)
    // and the tree's MAIN mission in the Missions window (the first/original Mission for the tree,
    // never a clone). They are the same abstraction shown two ways, so renaming either renames both
    // - plus the auto "/ Debris" and "/ Crew" subgroups that hang off the root - in one atomic step.
    //
    // Group names must be unique (a folder is keyed by its name), while mission names need not be;
    // the linked rename therefore validates the new root + derived child names for collisions up
    // front and refuses the whole rename (leaving every name untouched) if any collide, so the two
    // views can never drift. Both UI commit paths (RecordingsTableUI.CommitGroupRename and
    // MissionsWindowUI.CommitMissionRename) route a main-mission/root-group rename through here.
    internal static class MissionGroupLink
    {
        // Returns the committed tree whose root mission group is exactly groupName (root group
        // names are unique, so at most one matches), or null when groupName is not a tree root
        // group - a user-defined group, a "/ Debris" or "/ Crew" subgroup, or an unknown name.
        internal static RecordingTree FindTreeByRootGroup(string groupName)
        {
            if (string.IsNullOrEmpty(groupName))
                return null;
            var trees = RecordingStore.CommittedTrees;
            for (int i = 0; i < trees.Count; i++)
            {
                RecordingTree t = trees[i];
                if (t != null
                    && !string.IsNullOrEmpty(t.AutoGeneratedRootGroupName)
                    && string.Equals(t.AutoGeneratedRootGroupName, groupName, StringComparison.OrdinalIgnoreCase))
                    return t;
            }
            return null;
        }

        // True when groupName is a committed tree's root mission group (i.e. renaming it should
        // also rename the tree's main mission + its auto subgroups via RenameMissionGroup).
        internal static bool IsMissionRootGroup(string groupName)
        {
            return FindTreeByRootGroup(groupName) != null;
        }

        /// <summary>
        /// Renames everything that represents <paramref name="tree"/>'s mission to
        /// <paramref name="newName"/>: the root group (recording tags + tree field + group
        /// hierarchy), its auto "/ Debris" and "/ Crew" subgroups that are still in derived
        /// "&lt;root&gt; / X" form, and the tree's main <see cref="Mission.Name"/>. Atomic: the root
        /// and every derived child target name is collision-checked first, and on any collision /
        /// invalid / permanent name nothing is mutated and the method returns false (so the caller
        /// keeps the old name). A user-renamed child (no longer "&lt;root&gt; / X") is left as-is to
        /// preserve deliberate customization. A tree with no root group yet only has its main
        /// mission renamed. Returns true (no group work) when <paramref name="newName"/> already
        /// equals the current root.
        /// </summary>
        internal static bool RenameMissionGroup(RecordingTree tree, string newName, out string failReason)
        {
            failReason = null;
            if (tree == null)
            {
                failReason = "no tree";
                return false;
            }
            if (string.IsNullOrEmpty(newName))
            {
                failReason = "empty name";
                return false;
            }
            if (RecordingStore.IsInvalidGroupName(newName))
            {
                failReason = "invalid characters";
                return false;
            }
            if (RecordingStore.IsPermanentRootGroup(newName))
            {
                failReason = "reserved name";
                return false;
            }

            Mission main = MissionStore.FindOriginalMission(tree.Id);
            string oldRoot = tree.AutoGeneratedRootGroupName;

            // No root group yet (tree committed but not auto-grouped, or in flight): nothing to
            // link, just carry the rename onto the main mission if there is one.
            if (string.IsNullOrEmpty(oldRoot))
            {
                MissionStore.RenameMission(main, newName);
                ParsekLog.Info("Mission",
                    $"RenameMissionGroup: tree={tree.Id} has no root group; renamed main mission only " +
                    $"-> '{newName}' (main={(main != null ? "present" : "none")})");
                return true;
            }

            // Group unchanged (a case-only edit is NOT identical and falls through to the full
            // rename below): when truly identical, just make sure the main mission tracks it.
            if (string.Equals(oldRoot, newName, StringComparison.Ordinal))
            {
                MissionStore.RenameMission(main, newName);
                ParsekLog.Verbose("Mission",
                    $"RenameMissionGroup: tree={tree.Id} root group '{oldRoot}' unchanged; main mission synced");
                return true;
            }

            // Derive the child renames, but only cascade a child still in the auto "<root> / X"
            // form. A child the user renamed to something bespoke keeps its own name.
            string debrisOld = tree.AutoGeneratedDebrisGroupName;
            string crewOld = tree.AutoGeneratedCrewGroupName;
            string newDebris = IsDerivedChild(debrisOld, oldRoot, RecordingGroupStore.DebrisSubgroupSuffix)
                ? newName + RecordingGroupStore.DebrisSubgroupSuffix
                : null;
            string newCrew = IsDerivedChild(crewOld, oldRoot, RecordingGroupStore.CrewSubgroupSuffix)
                ? newName + RecordingGroupStore.CrewSubgroupSuffix
                : null;

            // Atomic collision pre-check: none of the target names may already belong to a
            // DIFFERENT group. The names we are vacating (oldRoot + the children being renamed)
            // are exempt - reusing them is exactly what a rename does.
            var existing = new HashSet<string>(RecordingStore.GetGroupNames(), StringComparer.OrdinalIgnoreCase);
            var vacating = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            AddIfPresent(vacating, oldRoot);
            if (newDebris != null) AddIfPresent(vacating, debrisOld);
            if (newCrew != null) AddIfPresent(vacating, crewOld);

            string collision = FirstCollision(existing, vacating, newName, newDebris, newCrew);
            if (collision != null)
            {
                failReason = $"'{collision}' already exists";
                return false;
            }

            // Apply children BEFORE the root: a child name is "<oldRoot> / X", so moving the root
            // to newName can never transiently collide with a not-yet-renamed child this way (and
            // the normal case is unaffected). Pre-validation guarantees each succeeds; guard
            // defensively.
            int renamed = 0;
            if (newDebris != null)
                renamed += RenameOneGroup(debrisOld, newDebris) ? 1 : 0;
            if (newCrew != null)
                renamed += RenameOneGroup(crewOld, newCrew) ? 1 : 0;
            renamed += RenameOneGroup(oldRoot, newName) ? 1 : 0;

            MissionStore.RenameMission(main, newName);

            ParsekLog.Info("Mission",
                $"RenameMissionGroup: tree={tree.Id} '{oldRoot}' -> '{newName}' " +
                $"({renamed} group(s) + main mission synced; " +
                $"debris={(newDebris ?? "-")}, crew={(newCrew ?? "-")})");
            return true;
        }

        // Renames a single group name across recording tags + tree auto-group fields
        // (RecordingStore.RenameGroup) and the group hierarchy (GroupHierarchyStore). Skips a
        // no-op / empty pair. Returns whether the recording-side rename reported success.
        private static bool RenameOneGroup(string oldName, string newName)
        {
            if (string.IsNullOrEmpty(oldName) || string.IsNullOrEmpty(newName)
                || string.Equals(oldName, newName, StringComparison.Ordinal))
                return false;
            bool ok = RecordingStore.RenameGroup(oldName, newName);
            GroupHierarchyStore.RenameGroupInHierarchy(oldName, newName);
            if (!ok)
                ParsekLog.Warn("Mission",
                    $"RenameMissionGroup: unexpected RenameGroup failure for '{oldName}' -> '{newName}' " +
                    "after collision pre-check passed");
            return ok;
        }

        private static bool IsDerivedChild(string childName, string rootName, string suffix)
        {
            return !string.IsNullOrEmpty(childName)
                && string.Equals(childName, rootName + suffix, StringComparison.OrdinalIgnoreCase);
        }

        private static void AddIfPresent(HashSet<string> set, string value)
        {
            if (!string.IsNullOrEmpty(value))
                set.Add(value);
        }

        // Returns the first target name that already exists as a different group, or null.
        private static string FirstCollision(HashSet<string> existing, HashSet<string> vacating,
            string newRoot, string newDebris, string newCrew)
        {
            if (Collides(existing, vacating, newRoot)) return newRoot;
            if (newDebris != null && Collides(existing, vacating, newDebris)) return newDebris;
            if (newCrew != null && Collides(existing, vacating, newCrew)) return newCrew;
            return null;
        }

        private static bool Collides(HashSet<string> existing, HashSet<string> vacating, string target)
        {
            return target != null && existing.Contains(target) && !vacating.Contains(target);
        }
    }
}
