using System;
using System.Collections.Generic;

namespace Parsek
{
    internal static class RecordingGroupStore
    {
        // Auto-assigned-standalone-group tracking has two storage locations:
        //   1. Recording.AutoAssignedStandaloneGroupName (authoritative, persisted
        //      via RecordingTree save/load as `autoAssignedStandaloneGroup`).
        //   2. autoAssignedStandaloneGroupsByRecordingId (static, in-memory only).
        // The dict exists so test recordings without a persisted field (built via
        // RecordingBuilder / direct .Add calls) still resolve through
        // TryGetAutoAssignedStandaloneGroup. Invariant: every mutation goes through
        // MarkAutoAssignedStandaloneGroup / ClearAutoAssignedStandaloneGroup so the
        // field and dict stay aligned. Do NOT write to either directly from outside
        // these helpers (Recording.cs field deserialization is the one exception
        // and is reconciled by TryGet's first branch).
        private static readonly Dictionary<string, string> autoAssignedStandaloneGroupsByRecordingId =
            new Dictionary<string, string>(StringComparer.Ordinal);

        internal static void ResetForTesting()
        {
            autoAssignedStandaloneGroupsByRecordingId.Clear();
        }

        /// <summary>
        /// Auto-groups tree recordings under a unique group name.
        /// Debris recordings get a "Debris" subgroup under the main group.
        /// Uses GenerateUniqueGroupName to avoid merging multiple launches of the same vessel
        /// into one group (bug #104).
        /// </summary>
        internal static void AutoGroupTreeRecordings(
            RecordingTree tree,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(tree.TreeName) || tree.Recordings.Count <= 1)
                return;

            string groupName = GenerateUniqueGroupName(tree.TreeName, committedRecordings);
            int debrisCount = 0;
            int crewCount = 0;
            string debrisGroupName = null;
            string crewGroupName = null;
            tree.AutoGeneratedRootGroupName = groupName;
            tree.AutoGeneratedDebrisGroupName = null;
            tree.AutoGeneratedCrewGroupName = null;

            foreach (var rec in tree.Recordings.Values)
            {
                string targetGroup = groupName;
                if (rec.IsDebris)
                {
                    // Create debris subgroup on first debris recording
                    if (debrisGroupName == null)
                    {
                        debrisGroupName = groupName + " / Debris";
                        GroupHierarchyStore.SetGroupParent(debrisGroupName, groupName);
                    }
                    targetGroup = debrisGroupName;
                    tree.AutoGeneratedDebrisGroupName = debrisGroupName;
                    debrisCount++;
                }
                else if (!string.IsNullOrEmpty(rec.EvaCrewName))
                {
                    // EVA recordings belong under a dedicated crew subgroup for the mission.
                    if (crewGroupName == null)
                    {
                        crewGroupName = groupName + " / Crew";
                        GroupHierarchyStore.SetGroupParent(crewGroupName, groupName);
                    }
                    targetGroup = crewGroupName;
                    tree.AutoGeneratedCrewGroupName = crewGroupName;
                    crewCount++;
                }

                if (rec.RecordingGroups == null)
                    rec.RecordingGroups = new List<string>();
                if (!rec.RecordingGroups.Contains(targetGroup))
                    rec.RecordingGroups.Add(targetGroup);
                ClearAutoAssignedStandaloneGroup(rec);
            }

            int mainCount = tree.Recordings.Count - debrisCount - crewCount;
            if (debrisCount > 0 || crewCount > 0)
            {
                var details = new List<string>();
                if (mainCount > 0)
                    details.Add($"{mainCount} main under '{groupName}'");
                if (crewCount > 0)
                    details.Add($"{crewCount} crew under '{crewGroupName}'");
                if (debrisCount > 0)
                    details.Add($"{debrisCount} debris under '{debrisGroupName}'");
                ParsekLog.Info("RecordingStore",
                    $"Auto-grouped {string.Join(", ", details)}");
            }
            else
            {
                ParsekLog.Info("RecordingStore",
                    $"Auto-grouped {tree.Recordings.Count} recordings under '{groupName}'");
            }
        }

        private static string ResolveTreeRootGroupName(RecordingTree tree)
        {
            if (tree == null) return null;

            foreach (var rec in tree.Recordings.Values)
            {
                if (rec.RecordingGroups == null || rec.RecordingGroups.Count == 0)
                    continue;

                string groupName = rec.RecordingGroups[0];
                string parent;
                while (GroupHierarchyStore.TryGetGroupParent(groupName, out parent))
                    groupName = parent;
                return groupName;
            }

            return null;
        }

        internal static bool IsAutoGeneratedTreeGroup(
            string groupName,
            List<RecordingTree> committedTrees)
        {
            if (string.IsNullOrEmpty(groupName))
                return false;

            for (int i = 0; i < committedTrees.Count; i++)
            {
                var tree = committedTrees[i];
                EnsureAutoGeneratedTreeGroups(tree);
                if (string.IsNullOrEmpty(tree.AutoGeneratedRootGroupName))
                    continue;

                if (string.Equals(groupName, tree.AutoGeneratedRootGroupName, StringComparison.OrdinalIgnoreCase)
                    || string.Equals(groupName, tree.AutoGeneratedDebrisGroupName, StringComparison.OrdinalIgnoreCase)
                    || string.Equals(groupName, tree.AutoGeneratedCrewGroupName, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        internal static bool IsPermanentRootGroup(string groupName)
        {
            return string.Equals(groupName, RecordingStore.GloopsGroupName, StringComparison.OrdinalIgnoreCase);
        }

        internal static bool IsPermanentGroup(
            string groupName,
            List<RecordingTree> committedTrees)
        {
            return IsPermanentRootGroup(groupName)
                || IsAutoGeneratedTreeGroup(groupName, committedTrees);
        }

        private static void EnsureAutoGeneratedTreeGroups(RecordingTree tree)
        {
            if (tree == null || !string.IsNullOrEmpty(tree.AutoGeneratedRootGroupName))
                return;

            string rootGroupName, debrisGroupName, crewGroupName;
            if (TryInferAutoGeneratedTreeGroups(tree,
                out rootGroupName, out debrisGroupName, out crewGroupName))
            {
                tree.AutoGeneratedRootGroupName = rootGroupName;
                tree.AutoGeneratedDebrisGroupName = debrisGroupName;
                tree.AutoGeneratedCrewGroupName = crewGroupName;
                // Best-effort migration from pre-#265 saves: RecordingGroups[0] is
                // assumed to be the user's primary group. If the user reordered
                // groups before the fix landed, the inference can pick a wrong
                // primary — log loud so a misinference is easy to spot in KSP.log.
                ParsekLog.Info("RecordingStore",
                    $"EnsureAutoGeneratedTreeGroups: inferred groups for tree '{tree.TreeName}' " +
                    $"(root='{rootGroupName ?? "null"}', debris='{debrisGroupName ?? "null"}', " +
                    $"crew='{crewGroupName ?? "null"}') from first-group heuristic");
            }
        }

        private static bool TryInferAutoGeneratedTreeGroups(RecordingTree tree,
            out string rootGroupName, out string debrisGroupName, out string crewGroupName)
        {
            rootGroupName = null;
            debrisGroupName = null;
            crewGroupName = null;

            if (tree == null || tree.Recordings == null || tree.Recordings.Count == 0)
                return false;

            Recording rootRec;
            if (!string.IsNullOrEmpty(tree.RootRecordingId)
                && tree.Recordings.TryGetValue(tree.RootRecordingId, out rootRec))
            {
                rootGroupName = GetPrimaryGroup(rootRec);
            }

            foreach (var rec in tree.Recordings.Values)
            {
                string primaryGroup = GetPrimaryGroup(rec);
                if (string.IsNullOrEmpty(primaryGroup))
                    continue;

                if (string.IsNullOrEmpty(rootGroupName)
                    && !rec.IsDebris
                    && string.IsNullOrEmpty(rec.EvaCrewName))
                {
                    rootGroupName = primaryGroup;
                }

                if (rec.IsDebris
                    && string.IsNullOrEmpty(debrisGroupName)
                    && !string.Equals(primaryGroup, rootGroupName, StringComparison.OrdinalIgnoreCase))
                    debrisGroupName = primaryGroup;

                if (!string.IsNullOrEmpty(rec.EvaCrewName)
                    && string.IsNullOrEmpty(crewGroupName)
                    && !string.Equals(primaryGroup, rootGroupName, StringComparison.OrdinalIgnoreCase))
                    crewGroupName = primaryGroup;
            }

            return !string.IsNullOrEmpty(rootGroupName);
        }

        private static string GetPrimaryGroup(Recording rec)
        {
            if (rec == null || rec.RecordingGroups == null || rec.RecordingGroups.Count == 0)
                return null;
            return rec.RecordingGroups[0];
        }

        private static string ResolveAdoptedTreeGroup(string rootGroupName, Recording rec)
        {
            if (string.IsNullOrEmpty(rootGroupName) || rec == null)
                return rootGroupName;

            if (rec.IsDebris)
            {
                string debrisGroupName = rootGroupName + " / Debris";
                GroupHierarchyStore.SetGroupParent(debrisGroupName, rootGroupName);
                return debrisGroupName;
            }

            if (!string.IsNullOrEmpty(rec.EvaCrewName))
            {
                string crewGroupName = rootGroupName + " / Crew";
                GroupHierarchyStore.SetGroupParent(crewGroupName, rootGroupName);
                return crewGroupName;
            }

            return rootGroupName;
        }

        private static bool GroupBelongsToRootHierarchy(string groupName, string rootGroupName)
        {
            if (string.IsNullOrEmpty(groupName) || string.IsNullOrEmpty(rootGroupName))
                return false;

            string current = groupName;
            while (!string.IsNullOrEmpty(current))
            {
                if (string.Equals(current, rootGroupName, StringComparison.OrdinalIgnoreCase))
                    return true;

                string parent;
                if (!GroupHierarchyStore.TryGetGroupParent(current, out parent))
                    break;
                current = parent;
            }

            return false;
        }

        internal static void MarkAutoAssignedStandaloneGroup(Recording rec, string groupName)
        {
            if (rec == null || string.IsNullOrEmpty(rec.RecordingId) || IsInvalidGroupName(groupName))
                return;

            rec.AutoAssignedStandaloneGroupName = groupName;
            autoAssignedStandaloneGroupsByRecordingId[rec.RecordingId] = groupName;
        }

        /// <summary>
        /// Clears the auto-assigned-standalone-group marker. Must be called from
        /// every group-mutation entry point (AddRecordingToGroup, RemoveRecordingFromGroup,
        /// AddChainToGroup, RemoveChainFromGroup, RenameGroup, RemoveGroupFromAll,
        /// ReplaceGroupOnAll). If a new group-mutation path is added, call this here
        /// too — otherwise a manual edit will silently get re-adopted on the next
        /// tree commit (bug #265 / #376).
        /// </summary>
        private static void ClearAutoAssignedStandaloneGroup(Recording rec)
        {
            if (rec == null || string.IsNullOrEmpty(rec.RecordingId))
                return;

            rec.AutoAssignedStandaloneGroupName = null;
            autoAssignedStandaloneGroupsByRecordingId.Remove(rec.RecordingId);
        }

        private static bool TryGetAutoAssignedStandaloneGroup(Recording rec, out string groupName)
        {
            groupName = null;
            if (rec == null)
                return false;

            if (!string.IsNullOrEmpty(rec.AutoAssignedStandaloneGroupName))
            {
                groupName = rec.AutoAssignedStandaloneGroupName;
                if (!string.IsNullOrEmpty(rec.RecordingId))
                    autoAssignedStandaloneGroupsByRecordingId[rec.RecordingId] = groupName;
                return true;
            }

            if (string.IsNullOrEmpty(rec.RecordingId))
                return false;

            return autoAssignedStandaloneGroupsByRecordingId.TryGetValue(rec.RecordingId, out groupName);
        }

        private static bool ShouldAdoptRecordingIntoTreeGroup(Recording rec, string rootGroupName)
        {
            if (rec == null)
                return false;

            if (rec.RecordingGroups == null || rec.RecordingGroups.Count == 0)
                return true;

            for (int i = 0; i < rec.RecordingGroups.Count; i++)
            {
                if (GroupBelongsToRootHierarchy(rec.RecordingGroups[i], rootGroupName))
                    return false;
            }

            if (rec.RecordingGroups.Count != 1 || GroupHierarchyStore.HasGroupParent(rec.RecordingGroups[0]))
                return false;

            string autoGroupName;
            if (!TryGetAutoAssignedStandaloneGroup(rec, out autoGroupName))
                return false;

            return string.Equals(rec.RecordingGroups[0], autoGroupName, StringComparison.Ordinal);
        }

        /// <summary>
        /// Adopts orphaned committed recordings that belong to this tree but were
        /// committed as standalone before the tree (e.g., split segments committed
        /// via deferred merge dialog before the tree revert/commit).
        /// Matches by TreeId or by vessel PID + overlapping time range.
        /// </summary>
        internal static void AdoptOrphanedRecordingsIntoTreeGroup(
            RecordingTree tree,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(tree.TreeName))
                return;

            string rootGroupName = ResolveTreeRootGroupName(tree);
            if (rootGroupName == null)
                return;

            // Collect tree vessel PIDs and time range for matching
            var treePids = new HashSet<uint>();
            double treeStartUT = double.MaxValue, treeEndUT = 0;
            foreach (var rec in tree.Recordings.Values)
            {
                if (rec.VesselPersistentId != 0)
                    treePids.Add(rec.VesselPersistentId);
                if (rec.StartUT < treeStartUT) treeStartUT = rec.StartUT;
                if (rec.EndUT > treeEndUT) treeEndUT = rec.EndUT;
            }

            int adopted = 0;
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var cr = committedRecordings[i];

                bool match = cr.TreeId == tree.Id;
                if (!match && treePids.Contains(cr.VesselPersistentId)
                    && cr.StartUT >= treeStartUT - 60 && cr.EndUT <= treeEndUT + 60)
                    match = true;

                if (!match) continue;
                if (!ShouldAdoptRecordingIntoTreeGroup(cr, rootGroupName)) continue;

                string targetGroup = ResolveAdoptedTreeGroup(rootGroupName, cr);
                cr.RecordingGroups = new List<string> { targetGroup };
                ClearAutoAssignedStandaloneGroup(cr);
                adopted++;
                ParsekLog.Info("RecordingStore",
                    $"Adopted orphaned recording '{cr.VesselName}' (id={cr.RecordingId}) into group '{targetGroup}'");
            }
            if (adopted > 0)
                ParsekLog.Info("RecordingStore",
                    $"Adopted {adopted} orphaned recording(s) into tree group '{rootGroupName}'");
        }

        /// <summary>
        /// Returns true if the group name contains characters that would break ConfigNode serialization.
        /// </summary>
        internal static bool IsInvalidGroupName(string name)
        {
            return string.IsNullOrEmpty(name) ||
                   name.Contains("=") || name.Contains("{") || name.Contains("}") ||
                   name.Contains("\n") || name.Contains("\r");
        }

        /// <summary>
        /// Returns distinct group names across all committed recordings.
        /// </summary>
        internal static List<string> GetGroupNames(List<Recording> committedRecordings)
        {
            var names = new HashSet<string>();
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var groups = committedRecordings[i].RecordingGroups;
                if (groups == null) continue;
                for (int j = 0; j < groups.Count; j++)
                    names.Add(groups[j]);
            }
            var result = new List<string>(names);
            result.Sort(StringComparer.OrdinalIgnoreCase);
            return result;
        }

        /// <summary>
        /// Returns a group name that doesn't collide with existing group names.
        /// If baseName is not already used, returns it unchanged.
        /// Otherwise appends " (2)", " (3)", etc. until a unique name is found.
        /// </summary>
        internal static string GenerateUniqueGroupName(
            string baseName,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(baseName))
            {
                ParsekLog.Verbose("RecordingStore",
                    "GenerateUniqueGroupName: baseName is null/empty, returning 'Chain'");
                baseName = "Chain";
            }

            var existing = new HashSet<string>(GetGroupNames(committedRecordings), StringComparer.OrdinalIgnoreCase);
            if (!existing.Contains(baseName))
            {
                ParsekLog.Verbose("RecordingStore",
                    $"GenerateUniqueGroupName: '{baseName}' is unique, returning unchanged");
                return baseName;
            }

            for (int n = 2; n < 1000; n++)
            {
                string candidate = $"{baseName} ({n})";
                if (!existing.Contains(candidate))
                {
                    ParsekLog.Info("RecordingStore",
                        $"GenerateUniqueGroupName: '{baseName}' already exists, using '{candidate}'");
                    return candidate;
                }
            }

            // Safety fallback — should never happen in practice
            string fallback = $"{baseName} ({Guid.NewGuid().ToString("N").Substring(0, 6)})";
            ParsekLog.Warn("RecordingStore",
                $"GenerateUniqueGroupName: exhausted 999 candidates for '{baseName}', using fallback '{fallback}'");
            return fallback;
        }

        /// <summary>
        /// Adds a recording to a group. No-op if already a member or index invalid.
        /// </summary>
        internal static void AddRecordingToGroup(
            int index,
            string groupName,
            List<Recording> committedRecordings)
        {
            if (index < 0 || index >= committedRecordings.Count || IsInvalidGroupName(groupName)) return;
            var rec = committedRecordings[index];
            if (rec.RecordingGroups == null)
                rec.RecordingGroups = new List<string>();
            if (!rec.RecordingGroups.Contains(groupName))
            {
                rec.RecordingGroups.Add(groupName);
                ClearAutoAssignedStandaloneGroup(rec);
                ParsekLog.Info("RecordingStore", $"Recording '{rec.VesselName}' added to group '{groupName}'");
            }
        }

        /// <summary>
        /// Removes a recording from a group. No-op if not a member or index invalid.
        /// </summary>
        internal static void RemoveRecordingFromGroup(
            int index,
            string groupName,
            List<Recording> committedRecordings)
        {
            if (index < 0 || index >= committedRecordings.Count || string.IsNullOrEmpty(groupName)) return;
            var rec = committedRecordings[index];
            if (rec.RecordingGroups != null && rec.RecordingGroups.Remove(groupName))
            {
                if (rec.RecordingGroups.Count == 0)
                    rec.RecordingGroups = null;
                ClearAutoAssignedStandaloneGroup(rec);
                ParsekLog.Info("RecordingStore", $"Recording '{rec.VesselName}' removed from group '{groupName}'");
            }
        }

        /// <summary>
        /// Returns indices of all recordings in a given chain. Single scan, reusable for batch ops.
        /// </summary>
        internal static List<int> GetChainMemberIndices(
            string chainId,
            List<Recording> committedRecordings)
        {
            var indices = new List<int>();
            if (string.IsNullOrEmpty(chainId)) return indices;
            for (int i = 0; i < committedRecordings.Count; i++)
                if (committedRecordings[i].ChainId == chainId)
                    indices.Add(i);
            return indices;
        }

        /// <summary>
        /// Adds all chain members to a group.
        /// </summary>
        internal static void AddChainToGroup(
            string chainId,
            string groupName,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(chainId) || IsInvalidGroupName(groupName)) return;
            var members = GetChainMemberIndices(chainId, committedRecordings);
            int count = 0;
            for (int i = 0; i < members.Count; i++)
            {
                var rec = committedRecordings[members[i]];
                if (rec.RecordingGroups == null)
                    rec.RecordingGroups = new List<string>();
                if (!rec.RecordingGroups.Contains(groupName))
                {
                    rec.RecordingGroups.Add(groupName);
                    ClearAutoAssignedStandaloneGroup(rec);
                    count++;
                }
            }
            if (count > 0)
                ParsekLog.Info("RecordingStore", $"Chain '{chainId}': {count} members added to group '{groupName}'");
        }

        /// <summary>
        /// Removes all chain members from a group.
        /// </summary>
        internal static void RemoveChainFromGroup(
            string chainId,
            string groupName,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(chainId) || string.IsNullOrEmpty(groupName)) return;
            var members = GetChainMemberIndices(chainId, committedRecordings);
            int count = 0;
            for (int i = 0; i < members.Count; i++)
            {
                var rec = committedRecordings[members[i]];
                if (rec.RecordingGroups != null && rec.RecordingGroups.Remove(groupName))
                {
                    if (rec.RecordingGroups.Count == 0)
                        rec.RecordingGroups = null;
                    ClearAutoAssignedStandaloneGroup(rec);
                    count++;
                }
            }
            if (count > 0)
                ParsekLog.Info("RecordingStore", $"Chain '{chainId}': {count} members removed from group '{groupName}'");
        }

        /// <summary>
        /// Renames a group across all committed recordings. Returns false if newName already exists.
        /// </summary>
        internal static bool RenameGroup(
            string oldName,
            string newName,
            List<Recording> committedRecordings,
            List<RecordingTree> committedTrees)
        {
            if (string.IsNullOrEmpty(oldName) || string.IsNullOrEmpty(newName) || oldName == newName)
                return false;

            if (IsPermanentRootGroup(oldName))
            {
                ParsekLog.Warn("RecordingStore", $"RenameGroup: cannot rename permanent root group '{oldName}'");
                return false;
            }

            // Check for collision
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var groups = committedRecordings[i].RecordingGroups;
                if (groups != null && groups.Contains(newName))
                {
                    ParsekLog.Warn("RecordingStore", $"RenameGroup: cannot rename '{oldName}' to '{newName}' — name already exists");
                    return false;
                }
            }

            int updated = 0;
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var groups = committedRecordings[i].RecordingGroups;
                if (groups != null)
                {
                    int idx = groups.IndexOf(oldName);
                    if (idx >= 0)
                    {
                        groups[idx] = newName;
                        ClearAutoAssignedStandaloneGroup(committedRecordings[i]);
                        updated++;
                    }
                }
            }
            RenameAutoGeneratedTreeGroups(oldName, newName, committedTrees);
            ParsekLog.Info("RecordingStore", $"RenameGroup: '{oldName}' → '{newName}' ({updated} recordings updated)");
            return true;
        }

        private static void RenameAutoGeneratedTreeGroups(
            string oldName,
            string newName,
            List<RecordingTree> committedTrees)
        {
            for (int i = 0; i < committedTrees.Count; i++)
            {
                var tree = committedTrees[i];
                EnsureAutoGeneratedTreeGroups(tree);

                if (string.Equals(tree.AutoGeneratedRootGroupName, oldName, StringComparison.OrdinalIgnoreCase))
                    tree.AutoGeneratedRootGroupName = newName;
                if (string.Equals(tree.AutoGeneratedDebrisGroupName, oldName, StringComparison.OrdinalIgnoreCase))
                    tree.AutoGeneratedDebrisGroupName = newName;
                if (string.Equals(tree.AutoGeneratedCrewGroupName, oldName, StringComparison.OrdinalIgnoreCase))
                    tree.AutoGeneratedCrewGroupName = newName;
            }
        }

        /// <summary>
        /// Removes a group from all committed recordings' group lists.
        /// Returns the number of recordings that were modified.
        /// </summary>
        internal static int RemoveGroupFromAll(
            string groupName,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(groupName)) return 0;
            int updated = 0;
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var rec = committedRecordings[i];
                if (rec.RecordingGroups != null && rec.RecordingGroups.Remove(groupName))
                {
                    if (rec.RecordingGroups.Count == 0)
                        rec.RecordingGroups = null;
                    ClearAutoAssignedStandaloneGroup(rec);
                    updated++;
                }
            }
            ParsekLog.Info("RecordingStore", $"RemoveGroupFromAll: '{groupName}' removed from {updated} recordings");
            return updated;
        }

        /// <summary>
        /// Replaces a group tag with a parent group tag on all committed recordings.
        /// If parentGroup is null, the group tag is simply removed.
        /// </summary>
        internal static int ReplaceGroupOnAll(
            string groupName,
            string parentGroup,
            List<Recording> committedRecordings)
        {
            if (string.IsNullOrEmpty(groupName)) return 0;
            int updated = 0;
            for (int i = 0; i < committedRecordings.Count; i++)
            {
                var rec = committedRecordings[i];
                if (rec.RecordingGroups == null) continue;
                int idx = rec.RecordingGroups.IndexOf(groupName);
                if (idx < 0) continue;
                if (parentGroup != null && !rec.RecordingGroups.Contains(parentGroup))
                    rec.RecordingGroups[idx] = parentGroup;
                else
                    rec.RecordingGroups.RemoveAt(idx);
                if (rec.RecordingGroups.Count == 0)
                    rec.RecordingGroups = null;
                ClearAutoAssignedStandaloneGroup(rec);
                updated++;
            }
            string dest = parentGroup ?? "(standalone)";
            ParsekLog.Info("RecordingStore", $"ReplaceGroupOnAll: '{groupName}' → '{dest}' on {updated} recordings");
            return updated;
        }
    }
}
