using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

namespace Parsek
{
    public class RecordingTree
    {
        internal const int CurrentTreeFormatVersion = 1;

        internal sealed class LegacyResourceResidual
        {
            public double PreTreeFunds;
            public double PreTreeScience;
            public float PreTreeReputation;
            public double DeltaFunds;
            public double DeltaScience;
            public float DeltaReputation;
            public bool ResourcesApplied;
            public bool ResourcesAppliedFieldPresent;

            public bool HasAnyNonZeroDelta(
                double fundsTolerance = 0.0,
                double scienceTolerance = 0.0,
                double reputationTolerance = 0.0)
            {
                return Math.Abs(DeltaFunds) > fundsTolerance
                    || Math.Abs(DeltaScience) > scienceTolerance
                    || Math.Abs((double)DeltaReputation) > reputationTolerance;
            }
        }

        // --- Serialized fields ---
        public string Id;
        public string TreeName;                     // root vessel name at launch
        public string RootRecordingId;
        public string ActiveRecordingId;            // nullable: null if all background
        public string AutoGeneratedRootGroupName;
        public string AutoGeneratedDebrisGroupName;
        public string AutoGeneratedCrewGroupName;
        public int TreeFormatVersion;

        public Dictionary<string, Recording> Recordings
            = new Dictionary<string, Recording>();
        public List<BranchPoint> BranchPoints = new List<BranchPoint>();

        // --- Runtime-only fields (not serialized) ---
        // Maps vessel persistentId -> recordingId for background vessel lookup.
        // Rebuilt from Recordings on load via RebuildBackgroundMap().
        public Dictionary<uint, string> BackgroundMap
            = new Dictionary<uint, string>();

        private LegacyResourceResidual legacyResidual;

        // Set of all vessel PIDs that appear anywhere in this tree's recordings.
        // This is archived-history membership, not a globally unique ownership claim.
        // Used by ghost skip logic to answer the tree-local question
        // "does this PID appear in this tree at all?".
        // Rebuilt alongside BackgroundMap via RebuildBackgroundMap().
        public HashSet<uint> RecordedVesselPids = new HashSet<uint>();

        internal void AddOrReplaceRecording(Recording rec)
        {
            if (rec == null || string.IsNullOrEmpty(rec.RecordingId))
                return;

            AssignTreeOrderIfMissing(rec);
            Recordings[rec.RecordingId] = rec;
        }

        /// <summary>
        /// Returns the maximum EndUT across all recordings in this tree.
        /// Returns 0 if all recordings have 0 points (degraded tree).
        /// </summary>
        internal double ComputeEndUT()
        {
            double endUT = 0;
            foreach (var rec in Recordings.Values)
            {
                double recEnd = rec.EndUT;
                if (recEnd > endUT) endUT = recEnd;
            }
            return endUT;
        }

        /// <summary>
        /// Returns true if this tree has no trajectory data (all recordings have 0 points).
        /// Degraded trees should not have their budget applied.
        /// </summary>
        internal bool IsDegraded => ComputeEndUT() == 0;

        internal LegacyResourceResidual ConsumeLegacyResidual()
        {
            var residual = legacyResidual;
            legacyResidual = null;
            return residual;
        }

        internal void SetLegacyResidualForTesting(
            double deltaFunds,
            double deltaScience,
            float deltaReputation,
            bool resourcesApplied,
            bool resourcesAppliedFieldPresent = true,
            double preTreeFunds = 0.0,
            double preTreeScience = 0.0,
            float preTreeReputation = 0f)
        {
            legacyResidual = new LegacyResourceResidual
            {
                PreTreeFunds = preTreeFunds,
                PreTreeScience = preTreeScience,
                PreTreeReputation = preTreeReputation,
                DeltaFunds = deltaFunds,
                DeltaScience = deltaScience,
                DeltaReputation = deltaReputation,
                ResourcesApplied = resourcesApplied,
                ResourcesAppliedFieldPresent = resourcesAppliedFieldPresent
            };
        }

        // --- Serialization ---

        public void Save(ConfigNode treeNode)
        {
            var ic = CultureInfo.InvariantCulture;

            treeNode.AddValue("id", Id ?? "");
            treeNode.AddValue("treeName", TreeName ?? "");
            treeNode.AddValue("rootRecordingId", RootRecordingId ?? "");
            TreeFormatVersion = CurrentTreeFormatVersion;
            treeNode.AddValue("treeFormatVersion", TreeFormatVersion.ToString(ic));
            if (ActiveRecordingId != null)
                treeNode.AddValue("activeRecordingId", ActiveRecordingId);
            if (!string.IsNullOrEmpty(AutoGeneratedRootGroupName))
                treeNode.AddValue("autoGeneratedRootGroupName", AutoGeneratedRootGroupName);
            if (!string.IsNullOrEmpty(AutoGeneratedDebrisGroupName))
                treeNode.AddValue("autoGeneratedDebrisGroupName", AutoGeneratedDebrisGroupName);
            if (!string.IsNullOrEmpty(AutoGeneratedCrewGroupName))
                treeNode.AddValue("autoGeneratedCrewGroupName", AutoGeneratedCrewGroupName);

            // Phase F: legacy resource fields (preTreeFunds/preTreeScience/preTreeRep,
            // deltaFunds/deltaScience/deltaRep, resourcesApplied) are NOT written
            // anymore. They remain on the in-memory type so Phase A's load-time
            // migration in LedgerOrchestrator can still read pre-Phase-F .sfs files,
            // but the new save shape carries the ledger as the single source of truth.

            // Serialize each recording
            EnsureRecordingTreeOrder();
            var orderedRecordings = new List<Recording>(Recordings.Values);
            orderedRecordings.Sort(CompareRecordingTreeOrder);
            foreach (var rec in orderedRecordings)
            {
                ConfigNode recNode = treeNode.AddNode("RECORDING");
                SaveRecordingInto(recNode, rec);
            }

            // Serialize branch points
            for (int i = 0; i < BranchPoints.Count; i++)
            {
                ConfigNode bpNode = treeNode.AddNode("BRANCH_POINT");
                SaveBranchPointInto(bpNode, BranchPoints[i]);
            }

            ParsekLog.Verbose("RecordingTree",
                $"Save: tree='{TreeName}' formatVersion={TreeFormatVersion} " +
                $"recordings={Recordings.Count} branchPoints={BranchPoints.Count} " +
                "(Phase F: legacy resource fields not persisted)");
        }

        public static RecordingTree Load(ConfigNode treeNode)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            var tree = new RecordingTree();
            tree.Id = treeNode.GetValue("id") ?? "";
            tree.TreeName = Recording.ResolveLocalizedName(treeNode.GetValue("treeName") ?? "");
            tree.RootRecordingId = treeNode.GetValue("rootRecordingId") ?? "";
            int treeFormatVersion;
            if (int.TryParse(treeNode.GetValue("treeFormatVersion"), NumberStyles.Integer, ic, out treeFormatVersion))
                tree.TreeFormatVersion = treeFormatVersion;
            else
                tree.TreeFormatVersion = 0;

            tree.ActiveRecordingId = treeNode.GetValue("activeRecordingId");
            tree.AutoGeneratedRootGroupName = treeNode.GetValue("autoGeneratedRootGroupName");
            tree.AutoGeneratedDebrisGroupName = treeNode.GetValue("autoGeneratedDebrisGroupName");
            tree.AutoGeneratedCrewGroupName = treeNode.GetValue("autoGeneratedCrewGroupName");
            tree.legacyResidual = LoadLegacyResidual(treeNode, inv, ic);
            string resourcesAppliedStr = treeNode.GetValue("resourcesApplied");

            // Load recordings
            ConfigNode[] recNodes = treeNode.GetNodes("RECORDING");
            for (int i = 0; i < recNodes.Length; i++)
            {
                var rec = new Recording();
                LoadRecordingFrom(recNodes[i], rec);
                tree.AddOrReplaceRecording(rec);
            }

            // Load branch points
            ConfigNode[] bpNodes = treeNode.GetNodes("BRANCH_POINT");
            for (int i = 0; i < bpNodes.Length; i++)
            {
                tree.BranchPoints.Add(LoadBranchPointFrom(bpNodes[i]));
            }

            tree.RebuildBackgroundMap();
            NormalizeLegacyRewindSuppressionMarkers(tree);

            ParsekLog.Verbose("RecordingTree",
                $"Load: id={tree.Id} tree='{tree.TreeName}' recordings={tree.Recordings.Count} " +
                $"branchPoints={tree.BranchPoints.Count} treeFormatVersion={tree.TreeFormatVersion} " +
                $"legacyResidualPresent={tree.legacyResidual != null} " +
                $"resourcesAppliedFieldPresent={resourcesAppliedStr != null}");

            // Rewind-to-Staging Phase 1 (design section 9): one-shot migration log
            // emitted after each tree load. The counter is cumulative across the save,
            // so the first tree with legacy `committed` entries flushes it; subsequent
            // loads in the same session become no-ops.
            RecordingStore.EmitLegacyMergeStateMigrationLogOnce();

            // Phase F: surface pre-Phase-F .sfs files that still carry the legacy
            // resource fields. Phase A's MigrateLegacyTreeResources is expected to
            // process these on the same load cycle; this VERBOSE line is a
            // diagnostic hook so an operator can see "tree X loaded with stale
            // residuals" if the migration ever misses one.
            bool anyLegacyResourceFieldPresent = tree.legacyResidual != null;
            bool anyResidual = tree.legacyResidual != null
                && tree.legacyResidual.HasAnyNonZeroDelta();
            if (anyLegacyResourceFieldPresent && anyResidual)
            {
                ParsekLog.Verbose("RecordingTree",
                    $"Load (Phase F): legacy resource fields present in save for " +
                    $"tree id='{tree.Id}' name='{tree.TreeName}' — " +
                    $"deltaFunds={tree.legacyResidual.DeltaFunds.ToString("R", ic)} " +
                    $"deltaScience={tree.legacyResidual.DeltaScience.ToString("R", ic)} " +
                    $"deltaRep={tree.legacyResidual.DeltaReputation.ToString("R", ic)} " +
                    $"resourcesApplied={tree.legacyResidual.ResourcesApplied}. " +
                    "LedgerOrchestrator.MigrateLegacyTreeResources will reconcile.");
            }
            return tree;
        }

        private static void NormalizeLegacyRewindSuppressionMarkers(RecordingTree tree)
        {
            if (tree == null || tree.Recordings == null || tree.Recordings.Count == 0)
                return;

            int legacyCount = 0;
            int sourceProtected = 0;
            int futureEligible = 0;
            Recording fallbackSource = null;
            var legacyMarkers = new List<Recording>();
            string sourceRecordingId = null;
            // Prefer the saved root over ActiveRecordingId when both exist.
            // Committed trees can retain ActiveRecordingId as a future leaf, and
            // treating that as the legacy source would re-block #589 terminal spawns.
            if (!string.IsNullOrEmpty(tree.RootRecordingId)
                && tree.Recordings.ContainsKey(tree.RootRecordingId))
            {
                sourceRecordingId = tree.RootRecordingId;
            }
            else if (!string.IsNullOrEmpty(tree.ActiveRecordingId)
                && tree.Recordings.ContainsKey(tree.ActiveRecordingId))
            {
                sourceRecordingId = tree.ActiveRecordingId;
            }
            bool hasKnownSourceCandidate = !string.IsNullOrEmpty(sourceRecordingId);
            if (hasKnownSourceCandidate
                && tree.Recordings.TryGetValue(sourceRecordingId, out var existingSource)
                && existingSource != null
                && existingSource.SpawnSuppressedByRewind
                && string.Equals(existingSource.SpawnSuppressedByRewindReason,
                    ParsekScenario.RewindSpawnSuppressionReasonSameRecording,
                    StringComparison.Ordinal))
            {
                sourceProtected = 1;
            }

            foreach (var rec in tree.Recordings.Values)
            {
                if (rec == null
                    || !rec.SpawnSuppressedByRewind
                    || !string.Equals(rec.SpawnSuppressedByRewindReason,
                        ParsekScenario.RewindSpawnSuppressionReasonLegacyUnscoped,
                        StringComparison.Ordinal))
                {
                    continue;
                }

                legacyCount++;
                legacyMarkers.Add(rec);
                bool isSavedSource = !string.IsNullOrEmpty(sourceRecordingId)
                    && string.Equals(rec.RecordingId, sourceRecordingId, StringComparison.Ordinal);
                if (isSavedSource)
                {
                    MarkLegacyRewindSuppressionAsSource(rec);
                    sourceProtected++;
                    continue;
                }

                if (fallbackSource == null || CompareRecordingTreeOrder(rec, fallbackSource) < 0)
                    fallbackSource = rec;
            }

            if (legacyCount == 0)
                return;

            if (sourceProtected == 0 && fallbackSource != null && !hasKnownSourceCandidate)
            {
                MarkLegacyRewindSuppressionAsSource(fallbackSource);
                sourceProtected++;
            }

            for (int i = 0; i < legacyMarkers.Count; i++)
            {
                var rec = legacyMarkers[i];
                if (rec != null
                    && string.Equals(rec.SpawnSuppressedByRewindReason,
                        ParsekScenario.RewindSpawnSuppressionReasonLegacyUnscoped,
                        StringComparison.Ordinal))
                {
                    futureEligible++;
                }
            }

            ParsekLog.Info("RecordingTree",
                $"Legacy SpawnSuppressedByRewind markers normalized: tree='{tree.TreeName}' " +
                $"id={tree.Id} legacy={legacyCount} sourceProtected={sourceProtected} " +
                $"futureEligible={futureEligible}");
        }

        private static void MarkLegacyRewindSuppressionAsSource(Recording rec)
        {
            rec.SpawnSuppressedByRewindReason =
                ParsekScenario.RewindSpawnSuppressionReasonSameRecording;
            if (double.IsNaN(rec.SpawnSuppressedByRewindUT))
                rec.SpawnSuppressedByRewindUT = rec.StartUT;

            ParsekLog.Verbose("RecordingTree",
                $"Legacy SpawnSuppressedByRewind retained as same-recording source: " +
                $"id={rec.RecordingId} name='{rec.VesselName}' " +
                $"treeOrder={rec.TreeOrder.ToString(CultureInfo.InvariantCulture)} " +
                $"rewindUT={ParsekScenario.FormatRewindUT(rec.SpawnSuppressedByRewindUT)}");
        }

        private static LegacyResourceResidual LoadLegacyResidual(
            ConfigNode treeNode,
            NumberStyles numberStyles,
            CultureInfo culture)
        {
            string preTreeFundsStr = treeNode.GetValue("preTreeFunds");
            string preTreeScienceStr = treeNode.GetValue("preTreeScience");
            string preTreeRepStr = treeNode.GetValue("preTreeRep");
            string deltaFundsStr = treeNode.GetValue("deltaFunds");
            string deltaScienceStr = treeNode.GetValue("deltaScience");
            string deltaRepStr = treeNode.GetValue("deltaRep");
            string resourcesAppliedStr = treeNode.GetValue("resourcesApplied");

            bool anyLegacyFieldPresent =
                preTreeFundsStr != null
                || preTreeScienceStr != null
                || preTreeRepStr != null
                || deltaFundsStr != null
                || deltaScienceStr != null
                || deltaRepStr != null
                || resourcesAppliedStr != null;
            if (!anyLegacyFieldPresent)
                return null;

            var residual = new LegacyResourceResidual();
            double.TryParse(preTreeFundsStr, numberStyles, culture, out residual.PreTreeFunds);
            double.TryParse(preTreeScienceStr, numberStyles, culture, out residual.PreTreeScience);
            float.TryParse(preTreeRepStr, numberStyles, culture, out residual.PreTreeReputation);
            double.TryParse(deltaFundsStr, numberStyles, culture, out residual.DeltaFunds);
            double.TryParse(deltaScienceStr, numberStyles, culture, out residual.DeltaScience);
            float.TryParse(deltaRepStr, numberStyles, culture, out residual.DeltaReputation);
            residual.ResourcesAppliedFieldPresent = resourcesAppliedStr != null;
            if (resourcesAppliedStr != null)
            {
                bool resourcesApplied;
                if (bool.TryParse(resourcesAppliedStr, out resourcesApplied))
                    residual.ResourcesApplied = resourcesApplied;
            }

            return residual;
        }

        public void RebuildBackgroundMap()
        {
            BackgroundMap.Clear();
            RecordedVesselPids.Clear();
            EnsureRecordingTreeOrder();
            var duplicateEligiblePids = new HashSet<uint>();
            var duplicateExamples = new List<string>();
            var orderedRecordings = new List<Recording>(Recordings.Values);
            orderedRecordings.Sort(CompareRecordingTreeOrder);
            foreach (var rec in orderedRecordings)
            {
                if (rec.VesselPersistentId != 0)
                    RecordedVesselPids.Add(rec.VesselPersistentId);

                if (IsBackgroundMapEligible(rec))
                {
                    if (BackgroundMap.TryGetValue(rec.VesselPersistentId, out string existingId))
                    {
                        duplicateEligiblePids.Add(rec.VesselPersistentId);

                        if (duplicateExamples.Count < 3)
                        {
                            duplicateExamples.Add(
                                $"{rec.VesselPersistentId}:{existingId}->{rec.RecordingId}");
                        }
                    }

                    BackgroundMap[rec.VesselPersistentId] = rec.RecordingId;
                }
            }

            if (duplicateEligiblePids.Count > 0)
            {
                string treeId = !string.IsNullOrEmpty(Id) ? Id : (TreeName ?? "unknown");
                string exampleSuffix = duplicateExamples.Count > 0
                    ? $" examples=[{string.Join(", ", duplicateExamples)}]"
                    : string.Empty;
                ParsekLog.VerboseRateLimited(
                    "RecordingTree",
                    $"bgmap-duplicate-{treeId}",
                    $"RebuildBackgroundMap: tree='{treeId}' has {duplicateEligiblePids.Count} " +
                    $"duplicate eligible PID(s); BackgroundMap kept the latest tree-order winner." +
                    exampleSuffix,
                    60.0);
            }

            ParsekLog.Verbose("RecordingTree",
                $"RebuildBackgroundMap: entries={BackgroundMap.Count} recordedPids={RecordedVesselPids.Count} totalRecordings={Recordings.Count}");
        }

        internal bool IsBackgroundMapEligible(Recording rec)
        {
            return rec != null
                && rec.VesselPersistentId != 0
                && rec.TerminalStateValue == null
                && !HasNextChainSegment(rec)
                && rec.ChildBranchPointId == null
                && rec.RecordingId != ActiveRecordingId;
        }

        private bool HasNextChainSegment(Recording rec)
        {
            if (rec == null || string.IsNullOrEmpty(rec.ChainId))
                return false;

            int nextIdx = rec.ChainIndex + 1;
            foreach (var other in Recordings.Values)
            {
                if (other.ChainId == rec.ChainId
                    && other.ChainIndex == nextIdx
                    && other.ChainBranch == rec.ChainBranch)
                {
                    return true;
                }
            }

            return false;
        }

        private void EnsureRecordingTreeOrder()
        {
            int nextOrder = 0;
            foreach (var rec in Recordings.Values)
            {
                if (rec != null && rec.TreeOrder >= nextOrder)
                    nextOrder = rec.TreeOrder + 1;
            }

            foreach (var rec in Recordings.Values)
            {
                if (rec != null && rec.TreeOrder < 0)
                    rec.TreeOrder = nextOrder++;
            }
        }

        private void AssignTreeOrderIfMissing(Recording rec)
        {
            if (rec == null || rec.TreeOrder >= 0)
                return;

            int nextOrder = 0;
            foreach (var existing in Recordings.Values)
            {
                if (existing != null && existing.TreeOrder >= nextOrder)
                    nextOrder = existing.TreeOrder + 1;
            }

            rec.TreeOrder = nextOrder;
        }

        private static int CompareRecordingTreeOrder(Recording a, Recording b)
        {
            if (ReferenceEquals(a, b))
                return 0;
            if (a == null)
                return -1;
            if (b == null)
                return 1;

            int aOrder = a.TreeOrder >= 0 ? a.TreeOrder : int.MaxValue;
            int bOrder = b.TreeOrder >= 0 ? b.TreeOrder : int.MaxValue;
            int cmp = aOrder.CompareTo(bOrder);
            if (cmp != 0)
                return cmp;

            cmp = a.StartUT.CompareTo(b.StartUT);
            if (cmp != 0)
                return cmp;

            cmp = a.EndUT.CompareTo(b.EndUT);
            if (cmp != 0)
                return cmp;

            return string.CompareOrdinal(a.RecordingId, b.RecordingId);
        }

        internal List<uint> FindDuplicateBackgroundMapPids()
        {
            var counts = new Dictionary<uint, int>();
            var duplicates = new List<uint>();

            foreach (var rec in Recordings.Values)
            {
                if (!IsBackgroundMapEligible(rec))
                    continue;

                int nextCount = 1;
                if (counts.TryGetValue(rec.VesselPersistentId, out int existing))
                    nextCount = existing + 1;

                counts[rec.VesselPersistentId] = nextCount;
                if (nextCount == 2)
                    duplicates.Add(rec.VesselPersistentId);
            }

            return duplicates;
        }
        // --- Recording serialization helpers ---

        internal static void SaveRecordingInto(ConfigNode recNode, Recording rec)
        {
            var ic = CultureInfo.InvariantCulture;

            recNode.AddValue("recordingId", rec.RecordingId ?? "");
            recNode.AddValue("vesselName", rec.VesselName ?? "");
            if (rec.TreeId != null)
                recNode.AddValue("treeId", rec.TreeId);
            if (rec.TreeOrder >= 0)
                recNode.AddValue("treeOrder", rec.TreeOrder.ToString(ic));
            recNode.AddValue("vesselPersistentId", rec.VesselPersistentId.ToString(ic));

            if (!double.IsNaN(rec.ExplicitStartUT))
                recNode.AddValue("explicitStartUT", rec.ExplicitStartUT.ToString("R", ic));
            if (!double.IsNaN(rec.ExplicitEndUT))
                recNode.AddValue("explicitEndUT", rec.ExplicitEndUT.ToString("R", ic));

            if (rec.TerminalStateValue.HasValue)
                recNode.AddValue("terminalState", ((int)rec.TerminalStateValue.Value).ToString(ic));
            if (rec.EndpointPhase != RecordingEndpointPhase.Unknown)
                recNode.AddValue("endpointPhase", ((int)rec.EndpointPhase).ToString(ic));
            if (!string.IsNullOrEmpty(rec.EndpointBodyName))
                recNode.AddValue("endpointBodyName", rec.EndpointBodyName);

            if (rec.ParentBranchPointId != null)
                recNode.AddValue("parentBranchPointId", rec.ParentBranchPointId);
            if (rec.ChildBranchPointId != null)
                recNode.AddValue("childBranchPointId", rec.ChildBranchPointId);

            // Terminal orbit fields (only when Orbiting or SubOrbital)
            if (!string.IsNullOrEmpty(rec.TerminalOrbitBody))
            {
                recNode.AddValue("tOrbInc", rec.TerminalOrbitInclination.ToString("R", ic));
                recNode.AddValue("tOrbEcc", rec.TerminalOrbitEccentricity.ToString("R", ic));
                recNode.AddValue("tOrbSma", rec.TerminalOrbitSemiMajorAxis.ToString("R", ic));
                recNode.AddValue("tOrbLan", rec.TerminalOrbitLAN.ToString("R", ic));
                recNode.AddValue("tOrbArgPe", rec.TerminalOrbitArgumentOfPeriapsis.ToString("R", ic));
                recNode.AddValue("tOrbMna", rec.TerminalOrbitMeanAnomalyAtEpoch.ToString("R", ic));
                recNode.AddValue("tOrbEpoch", rec.TerminalOrbitEpoch.ToString("R", ic));
                recNode.AddValue("tOrbBody", rec.TerminalOrbitBody);
            }

            // Terminal position (Landed/Splashed)
            if (rec.TerminalPosition.HasValue)
            {
                ConfigNode tpNode = recNode.AddNode("TERMINAL_POSITION");
                SurfacePosition.SaveInto(tpNode, rec.TerminalPosition.Value);
            }

            // Terrain height at recording end
            if (!double.IsNaN(rec.TerrainHeightAtEnd))
                recNode.AddValue("terrainHeightAtEnd", rec.TerrainHeightAtEnd.ToString("R", ic));

            // Background surface position
            if (rec.SurfacePos.HasValue)
            {
                ConfigNode spNode = recNode.AddNode("SURFACE_POSITION");
                SurfacePosition.SaveInto(spNode, rec.SurfacePos.Value);
            }

            // Playback settings, linkage, and chain metadata
            SaveRecordingPlaybackAndLinkage(recNode, rec);

            // Resource, rewind, geometry, and mutable state
            SaveRecordingResourceAndState(recNode, rec);
        }

        /// <summary>
        /// Saves playback settings (format version, ghost snapshot mode, loop, playback enabled),
        /// EVA child linkage, and chain linkage into a RECORDING ConfigNode.
        /// </summary>
        private static void SaveRecordingPlaybackAndLinkage(ConfigNode recNode, Recording rec)
        {
            var ic = CultureInfo.InvariantCulture;

            // Existing recording metadata
            recNode.AddValue("recordingFormatVersion", rec.RecordingFormatVersion);
            // Persist the mode that matches the current sidecars on disk. Recomputing
            // from live snapshots here can drift .sfs metadata away from sidecars when
            // later saves serialize tree state without rewriting files.
            GhostSnapshotMode ghostSnapshotMode = RecordingStore.GetExpectedGhostSnapshotMode(rec);
            rec.GhostSnapshotMode = ghostSnapshotMode;
            if (ghostSnapshotMode != GhostSnapshotMode.Unspecified)
                recNode.AddValue("ghostSnapshotMode", ghostSnapshotMode.ToString());

            // Sidecar epoch (bug #270): stamped into .prec on write, validated on load
            if (rec.SidecarEpoch > 0)
                recNode.AddValue("sidecarEpoch", rec.SidecarEpoch.ToString(ic));
            recNode.AddValue("loopPlayback", rec.LoopPlayback);
            recNode.AddValue("loopIntervalSeconds", rec.LoopIntervalSeconds.ToString("R", ic));
            if (!double.IsNaN(rec.LoopStartUT))
                recNode.AddValue("loopStartUT", rec.LoopStartUT.ToString("R", ic));
            if (!double.IsNaN(rec.LoopEndUT))
                recNode.AddValue("loopEndUT", rec.LoopEndUT.ToString("R", ic));
            if (rec.LoopAnchorVesselId != 0)
                recNode.AddValue("loopAnchorPid", rec.LoopAnchorVesselId.ToString(ic));
            if (!string.IsNullOrEmpty(rec.LoopAnchorBodyName))
                recNode.AddValue("loopAnchorBodyName", rec.LoopAnchorBodyName);
            if (!rec.PlaybackEnabled)
                recNode.AddValue("playbackEnabled", rec.PlaybackEnabled.ToString());
            if (rec.Hidden)
                recNode.AddValue("hidden", rec.Hidden.ToString());

            // EVA child linkage
            if (!string.IsNullOrEmpty(rec.ParentRecordingId))
                recNode.AddValue("parentRecordingId", rec.ParentRecordingId);
            if (!string.IsNullOrEmpty(rec.EvaCrewName))
                recNode.AddValue("evaCrewName", rec.EvaCrewName);

            // Chain linkage
            if (!string.IsNullOrEmpty(rec.ChainId))
                recNode.AddValue("chainId", rec.ChainId);
            if (rec.ChainIndex >= 0)
                recNode.AddValue("chainIndex", rec.ChainIndex.ToString(ic));
            if (rec.ChainBranch > 0)
                recNode.AddValue("chainBranch", rec.ChainBranch.ToString(ic));
        }

        /// <summary>
        /// Saves atmosphere segment metadata, pre-launch resources, rewind save metadata,
        /// mutable playback state, and UI grouping tags into a RECORDING ConfigNode.
        /// </summary>
        internal static void SaveRecordingResourceAndState(ConfigNode recNode, Recording rec)
        {
            var ic = CultureInfo.InvariantCulture;

            // Atmosphere segment metadata
            if (!string.IsNullOrEmpty(rec.SegmentPhase))
                recNode.AddValue("segmentPhase", rec.SegmentPhase);
            if (!string.IsNullOrEmpty(rec.SegmentBodyName))
                recNode.AddValue("segmentBodyName", rec.SegmentBodyName);

            // Location context (Phase 10)
            if (!string.IsNullOrEmpty(rec.StartBodyName))
                recNode.AddValue("startBodyName", rec.StartBodyName);
            if (!string.IsNullOrEmpty(rec.StartBiome))
                recNode.AddValue("startBiome", rec.StartBiome);
            if (!string.IsNullOrEmpty(rec.StartSituation))
                recNode.AddValue("startSituation", rec.StartSituation);
            if (!string.IsNullOrEmpty(rec.EndBiome))
                recNode.AddValue("endBiome", rec.EndBiome);
            if (!string.IsNullOrEmpty(rec.LaunchSiteName))
                recNode.AddValue("launchSiteName", rec.LaunchSiteName);

            // Pre-launch resources
            if (rec.PreLaunchFunds != 0)
                recNode.AddValue("preLaunchFunds", rec.PreLaunchFunds.ToString("R", ic));
            if (rec.PreLaunchScience != 0)
                recNode.AddValue("preLaunchScience", rec.PreLaunchScience.ToString("R", ic));
            if (rec.PreLaunchReputation != 0)
                recNode.AddValue("preLaunchRep", rec.PreLaunchReputation.ToString("R", ic));

            // Rewind save metadata
            if (!string.IsNullOrEmpty(rec.RewindSaveFileName))
            {
                recNode.AddValue("rewindSave", rec.RewindSaveFileName);
                recNode.AddValue("rewindResFunds", rec.RewindReservedFunds.ToString("R", ic));
                recNode.AddValue("rewindResSci", rec.RewindReservedScience.ToString("R", ic));
                recNode.AddValue("rewindResRep", rec.RewindReservedRep.ToString("R", ic));
            }

            // Mutable playback state (parallels ParsekScenario.OnSave standalone fields)
            if (rec.SpawnedVesselPersistentId != 0)
                recNode.AddValue("spawnedPid", rec.SpawnedVesselPersistentId);
            if (!string.IsNullOrEmpty(rec.TerminalSpawnSupersededByRecordingId))
                recNode.AddValue("terminalSpawnSupersededBy", rec.TerminalSpawnSupersededByRecordingId);
            if (rec.VesselDestroyed)
                recNode.AddValue("vesselDestroyed", rec.VesselDestroyed.ToString());
            // #573/#589: persist scoped rewind suppression metadata. New saves only
            // write this for the active/source recording; unscoped legacy markers are
            // recognized at load/spawn time and cleared instead of blocking future
            // same-tree terminal materialization forever.
            if (rec.SpawnSuppressedByRewind)
            {
                recNode.AddValue("spawnSuppressedByRewind", rec.SpawnSuppressedByRewind.ToString());
                if (!string.IsNullOrEmpty(rec.SpawnSuppressedByRewindReason))
                    recNode.AddValue("spawnSuppressedByRewindReason", rec.SpawnSuppressedByRewindReason);
                if (!double.IsNaN(rec.SpawnSuppressedByRewindUT))
                    recNode.AddValue("spawnSuppressedByRewindUT", rec.SpawnSuppressedByRewindUT.ToString("R", ic));
            }
            recNode.AddValue("lastResIdx", rec.LastAppliedResourceIndex);
            recNode.AddValue("pointCount", rec.Points != null ? rec.Points.Count : 0);

            // UI grouping tags (multi-group membership)
            if (rec.RecordingGroups != null)
                for (int g = 0; g < rec.RecordingGroups.Count; g++)
                    recNode.AddValue("recordingGroup", rec.RecordingGroups[g]);
            if (!string.IsNullOrEmpty(rec.AutoAssignedStandaloneGroupName))
                recNode.AddValue("autoAssignedStandaloneGroup", rec.AutoAssignedStandaloneGroupName);

            // Controller info
            if (rec.Controllers != null)
            {
                for (int i = 0; i < rec.Controllers.Count; i++)
                {
                    ConfigNode ctrlNode = recNode.AddNode("CONTROLLER");
                    ctrlNode.AddValue("type", rec.Controllers[i].type ?? "");
                    ctrlNode.AddValue("part", rec.Controllers[i].partName ?? "");
                    ctrlNode.AddValue("pid", rec.Controllers[i].partPersistentId.ToString(ic));
                }
                ParsekLog.Verbose("RecordingTree",
                    $"SaveRecordingResourceAndState: saved {rec.Controllers.Count} controller(s) for recording={rec.RecordingId}");
            }
            if (rec.IsDebris)
                recNode.AddValue("isDebris", rec.IsDebris.ToString());
            if (rec.IsGhostOnly)
                recNode.AddValue("isGhostOnly", rec.IsGhostOnly.ToString());

            // Max distance from launch (#302): needed for idle-on-pad auto-discard
            // after scene reload (without this, deserialized recordings default to 0.0
            // and IsTreeIdleOnPad falsely discards the whole tree).
            if (rec.MaxDistanceFromLaunch > 0)
                recNode.AddValue("maxDist", rec.MaxDistanceFromLaunch.ToString("R", ic));

            // Cascade depth (#284). Only written when non-zero so existing
            // gen-0 recordings stay byte-identical and old saves stay clean.
            if (rec.Generation > 0)
                recNode.AddValue("generation", rec.Generation.ToString(ic));

            // Crew end states (kerbals module)
            if (rec.CrewEndStatesResolved)
                recNode.AddValue("crewEndStatesResolved", rec.CrewEndStatesResolved.ToString());
            RecordingStore.SerializeCrewEndStates(recNode, rec);

            // Resource manifests (Phase 11)
            RecordingStore.SerializeResourceManifest(recNode, rec);

            // Inventory manifests (Phase 11)
            RecordingStore.SerializeInventoryManifest(recNode, rec);
            if (rec.StartInventorySlots != 0)
                recNode.AddValue("startInvSlots", rec.StartInventorySlots.ToString(ic));
            if (rec.EndInventorySlots != 0)
                recNode.AddValue("endInvSlots", rec.EndInventorySlots.ToString(ic));

            // Crew manifests (Phase 11)
            RecordingStore.SerializeCrewManifest(recNode, rec);

            // Dock target vessel PID (Phase 11)
            if (rec.DockTargetVesselPid != 0)
                recNode.AddValue("dockTargetPid", rec.DockTargetVesselPid.ToString(ic));

            // Rewind-to-Staging (design section 5.5). Omit the default Immutable enum value
            // so legacy saves stay byte-identical; write the string form for durability across
            // enum renumbering. SupersedeTargetId is transient but written defensively so a
            // mid-session crash can be diagnosed.
            if (rec.MergeState != MergeState.Immutable)
                recNode.AddValue("mergeState", rec.MergeState.ToString());
            if (!string.IsNullOrEmpty(rec.CreatingSessionId))
                recNode.AddValue("creatingSessionId", rec.CreatingSessionId);
            if (!string.IsNullOrEmpty(rec.SupersedeTargetId))
                recNode.AddValue("supersedeTargetId", rec.SupersedeTargetId);
            if (!string.IsNullOrEmpty(rec.ProvisionalForRpId))
                recNode.AddValue("provisionalForRpId", rec.ProvisionalForRpId);
        }

        internal static void LoadRecordingFrom(ConfigNode recNode, Recording rec)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            string id = recNode.GetValue("recordingId");
            if (!string.IsNullOrEmpty(id))
                rec.RecordingId = id;

            rec.VesselName = Recording.ResolveLocalizedName(recNode.GetValue("vesselName") ?? "");
            rec.TreeId = recNode.GetValue("treeId");
            int treeOrder;
            if (int.TryParse(recNode.GetValue("treeOrder"), NumberStyles.Integer, ic, out treeOrder))
                rec.TreeOrder = treeOrder;

            uint vesselPid;
            if (uint.TryParse(recNode.GetValue("vesselPersistentId"), NumberStyles.Integer, ic, out vesselPid))
                rec.VesselPersistentId = vesselPid;

            string explicitStartStr = recNode.GetValue("explicitStartUT");
            if (explicitStartStr != null)
            {
                double explicitStart;
                if (double.TryParse(explicitStartStr, inv, ic, out explicitStart))
                    rec.ExplicitStartUT = explicitStart;
            }
            string explicitEndStr = recNode.GetValue("explicitEndUT");
            if (explicitEndStr != null)
            {
                double explicitEnd;
                if (double.TryParse(explicitEndStr, inv, ic, out explicitEnd))
                    rec.ExplicitEndUT = explicitEnd;
            }

            string terminalStateStr = recNode.GetValue("terminalState");
            if (terminalStateStr != null)
            {
                int terminalInt;
                if (int.TryParse(terminalStateStr, NumberStyles.Integer, ic, out terminalInt)
                    && Enum.IsDefined(typeof(TerminalState), terminalInt))
                    rec.TerminalStateValue = (TerminalState)terminalInt;
            }

            string endpointPhaseStr = recNode.GetValue("endpointPhase");
            if (endpointPhaseStr != null)
            {
                int endpointPhaseInt;
                if (int.TryParse(endpointPhaseStr, NumberStyles.Integer, ic, out endpointPhaseInt)
                    && Enum.IsDefined(typeof(RecordingEndpointPhase), endpointPhaseInt))
                    rec.EndpointPhase = (RecordingEndpointPhase)endpointPhaseInt;
            }
            rec.EndpointBodyName = recNode.GetValue("endpointBodyName");

            rec.ParentBranchPointId = recNode.GetValue("parentBranchPointId");
            rec.ChildBranchPointId = recNode.GetValue("childBranchPointId");

            // Terminal orbit fields
            string tOrbBody = recNode.GetValue("tOrbBody");
            if (!string.IsNullOrEmpty(tOrbBody))
            {
                rec.TerminalOrbitBody = tOrbBody;
                double.TryParse(recNode.GetValue("tOrbInc"), inv, ic, out rec.TerminalOrbitInclination);
                double.TryParse(recNode.GetValue("tOrbEcc"), inv, ic, out rec.TerminalOrbitEccentricity);
                double.TryParse(recNode.GetValue("tOrbSma"), inv, ic, out rec.TerminalOrbitSemiMajorAxis);
                double.TryParse(recNode.GetValue("tOrbLan"), inv, ic, out rec.TerminalOrbitLAN);
                double.TryParse(recNode.GetValue("tOrbArgPe"), inv, ic, out rec.TerminalOrbitArgumentOfPeriapsis);
                double.TryParse(recNode.GetValue("tOrbMna"), inv, ic, out rec.TerminalOrbitMeanAnomalyAtEpoch);
                double.TryParse(recNode.GetValue("tOrbEpoch"), inv, ic, out rec.TerminalOrbitEpoch);
            }

            // Terminal position
            ConfigNode tpNode = recNode.GetNode("TERMINAL_POSITION");
            if (tpNode != null)
                rec.TerminalPosition = SurfacePosition.LoadFrom(tpNode);

            // Terrain height at recording end
            string thtStr = recNode.GetValue("terrainHeightAtEnd");
            if (thtStr != null)
            {
                double tht;
                if (double.TryParse(thtStr, inv, ic, out tht))
                    rec.TerrainHeightAtEnd = tht;
            }

            // Background surface position
            ConfigNode spNode = recNode.GetNode("SURFACE_POSITION");
            if (spNode != null)
                rec.SurfacePos = SurfacePosition.LoadFrom(spNode);

            // Playback settings, linkage, and chain metadata
            LoadRecordingPlaybackAndLinkage(recNode, rec);

            // Resource, rewind, geometry, and mutable state
            LoadRecordingResourceAndState(recNode, rec);

            RecordingEndpointResolver.BackfillEndpointDecision(rec, "RecordingTree.LoadRecordingFrom");

            ParsekLog.Verbose("RecordingTree",
                $"LoadRecordingFrom: id={rec.RecordingId} vessel='{rec.VesselName}' " +
                $"terminal={rec.TerminalStateValue?.ToString() ?? "null"} " +
                $"chain={rec.ChainId ?? "none"} formatVersion={rec.RecordingFormatVersion}");
        }

        #region LoadRecording Extracted Helpers

        /// <summary>
        /// Loads playback settings (format version, ghost geometry version, loop,
        /// playback enabled), EVA child linkage, and chain linkage from a RECORDING
        /// ConfigNode into the given Recording.
        /// </summary>
        private static void LoadRecordingPlaybackAndLinkage(ConfigNode recNode, Recording rec)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            // Existing recording metadata
            string formatVersionStr = recNode.GetValue("recordingFormatVersion");
            if (formatVersionStr != null)
            {
                int formatVersion;
                if (int.TryParse(formatVersionStr, NumberStyles.Integer, ic, out formatVersion))
                    rec.RecordingFormatVersion = formatVersion;
                else
                    rec.RecordingFormatVersion = 0;
            }
            else
            {
                rec.RecordingFormatVersion = 0;
            }
            rec.GhostSnapshotMode = RecordingStore.ParseGhostSnapshotMode(recNode.GetValue("ghostSnapshotMode"));

            // Sidecar epoch (bug #270)
            string sidecarEpochStr = recNode.GetValue("sidecarEpoch");
            if (sidecarEpochStr != null)
            {
                int sidecarEpoch;
                if (int.TryParse(sidecarEpochStr, NumberStyles.Integer, ic, out sidecarEpoch))
                    rec.SidecarEpoch = sidecarEpoch;
            }

            string loopPlaybackStr = recNode.GetValue("loopPlayback");
            if (loopPlaybackStr != null)
            {
                bool loopPlayback;
                if (bool.TryParse(loopPlaybackStr, out loopPlayback))
                    rec.LoopPlayback = loopPlayback;
            }

            string loopStartUTStr = recNode.GetValue("loopStartUT");
            if (loopStartUTStr != null)
            {
                double loopStartUT;
                if (double.TryParse(loopStartUTStr, inv, ic, out loopStartUT))
                    rec.LoopStartUT = loopStartUT;
            }

            string loopEndUTStr = recNode.GetValue("loopEndUT");
            if (loopEndUTStr != null)
            {
                double loopEndUT;
                if (double.TryParse(loopEndUTStr, inv, ic, out loopEndUT))
                    rec.LoopEndUT = loopEndUT;
            }

            string loopIntervalStr = recNode.GetValue("loopIntervalSeconds");
            if (loopIntervalStr != null)
            {
                double loopIntervalSeconds;
                if (double.TryParse(loopIntervalStr, inv, ic, out loopIntervalSeconds))
                {
                    if (rec.RecordingFormatVersion < RecordingStore.LaunchToLaunchLoopIntervalFormatVersion)
                    {
                        double effectiveLoopDuration;
                        double migratedLoopIntervalSeconds =
                            loopIntervalSeconds;
                        if (GhostPlaybackEngine.TryConvertLegacyGapToLoopPeriodSeconds(
                                rec, loopIntervalSeconds,
                                out migratedLoopIntervalSeconds, out effectiveLoopDuration))
                        {
                            int legacyRecordingFormatVersion = rec.RecordingFormatVersion;
                            rec.LoopIntervalSeconds = migratedLoopIntervalSeconds;
                            RecordingStore.NormalizeRecordingFormatVersionAfterLegacyLoopMigration(rec);
                            ParsekLog.Warn("Loop",
                                $"RecordingTree: migrated recording '{rec.VesselName}' from legacy " +
                                $"gap loopIntervalSeconds={loopIntervalSeconds.ToString("R", ic)} " +
                                $"to launch-to-launch period={migratedLoopIntervalSeconds.ToString("R", ic)}s " +
                                $"using effectiveLoopDuration={effectiveLoopDuration.ToString("R", ic)}s " +
                                $"for recordingFormatVersion={legacyRecordingFormatVersion} (pre-v4 loop save).");
                        }
                        else
                        {
                            rec.LoopIntervalSeconds = loopIntervalSeconds;
                            ParsekLog.Warn("Loop",
                                $"RecordingTree: loaded recording '{rec.VesselName}' with legacy " +
                                $"loopIntervalSeconds={loopIntervalSeconds.ToString("R", ic)} " +
                                $"for recordingFormatVersion={rec.RecordingFormatVersion}, but deferred migration " +
                                "because loop bounds are not hydrated yet.");
                        }
                    }
                    else
                    {
                        rec.LoopIntervalSeconds = loopIntervalSeconds;
                    }
                }
            }

            string loopAnchorPidStr = recNode.GetValue("loopAnchorPid");
            if (loopAnchorPidStr != null)
            {
                uint loopAnchorPid;
                if (uint.TryParse(loopAnchorPidStr, NumberStyles.Integer, ic, out loopAnchorPid))
                    rec.LoopAnchorVesselId = loopAnchorPid;
            }

            string loopAnchorBodyNameStr = recNode.GetValue("loopAnchorBodyName");
            if (!string.IsNullOrEmpty(loopAnchorBodyNameStr))
                rec.LoopAnchorBodyName = loopAnchorBodyNameStr;

            string playbackEnabledStr = recNode.GetValue("playbackEnabled");
            if (playbackEnabledStr != null)
            {
                bool playbackEnabled;
                if (bool.TryParse(playbackEnabledStr, out playbackEnabled))
                    rec.PlaybackEnabled = playbackEnabled;
            }
            string hiddenStr = recNode.GetValue("hidden");
            if (hiddenStr != null)
            {
                bool hidden;
                if (bool.TryParse(hiddenStr, out hidden))
                    rec.Hidden = hidden;
            }

            // EVA child linkage
            rec.ParentRecordingId = recNode.GetValue("parentRecordingId");
            rec.EvaCrewName = recNode.GetValue("evaCrewName");

            // Chain linkage
            rec.ChainId = recNode.GetValue("chainId");
            string chainIndexStr = recNode.GetValue("chainIndex");
            if (chainIndexStr != null)
            {
                int chainIndex;
                if (int.TryParse(chainIndexStr, NumberStyles.Integer, ic, out chainIndex))
                    rec.ChainIndex = chainIndex;
            }
            string chainBranchStr = recNode.GetValue("chainBranch");
            if (chainBranchStr != null)
            {
                int chainBranch;
                if (int.TryParse(chainBranchStr, NumberStyles.Integer, ic, out chainBranch))
                    rec.ChainBranch = chainBranch;
            }
        }

        /// <summary>
        /// Loads atmosphere segment metadata, pre-launch resources, rewind save metadata,
        /// ghost geometry metadata, mutable playback state, and UI grouping tags from a
        /// RECORDING ConfigNode into the given Recording.
        /// </summary>
        internal static void LoadRecordingResourceAndState(ConfigNode recNode, Recording rec)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            // Atmosphere segment metadata
            rec.SegmentPhase = recNode.GetValue("segmentPhase");
            rec.SegmentBodyName = recNode.GetValue("segmentBodyName");

            // Location context (Phase 10)
            rec.StartBodyName = recNode.GetValue("startBodyName");
            rec.StartBiome = recNode.GetValue("startBiome");
            rec.StartSituation = recNode.GetValue("startSituation");
            rec.EndBiome = recNode.GetValue("endBiome");
            rec.LaunchSiteName = recNode.GetValue("launchSiteName");

            // Pre-launch resources
            string preLaunchFundsStr = recNode.GetValue("preLaunchFunds");
            if (preLaunchFundsStr != null)
            {
                double preLaunchFunds;
                if (double.TryParse(preLaunchFundsStr, inv, ic, out preLaunchFunds))
                    rec.PreLaunchFunds = preLaunchFunds;
            }
            string preLaunchScienceStr = recNode.GetValue("preLaunchScience");
            if (preLaunchScienceStr != null)
            {
                double preLaunchScience;
                if (double.TryParse(preLaunchScienceStr, inv, ic, out preLaunchScience))
                    rec.PreLaunchScience = preLaunchScience;
            }
            string preLaunchRepStr = recNode.GetValue("preLaunchRep");
            if (preLaunchRepStr != null)
            {
                float preLaunchRep;
                if (float.TryParse(preLaunchRepStr, inv, ic, out preLaunchRep))
                    rec.PreLaunchReputation = preLaunchRep;
            }

            // Rewind save metadata
            rec.RewindSaveFileName = recNode.GetValue("rewindSave");
            string rewindFundsStr = recNode.GetValue("rewindResFunds");
            if (rewindFundsStr != null)
            {
                double rewindFunds;
                if (double.TryParse(rewindFundsStr, inv, ic, out rewindFunds))
                    rec.RewindReservedFunds = rewindFunds;
            }
            string rewindSciStr = recNode.GetValue("rewindResSci");
            if (rewindSciStr != null)
            {
                double rewindSci;
                if (double.TryParse(rewindSciStr, inv, ic, out rewindSci))
                    rec.RewindReservedScience = rewindSci;
            }
            string rewindRepStr = recNode.GetValue("rewindResRep");
            if (rewindRepStr != null)
            {
                float rewindRep;
                if (float.TryParse(rewindRepStr, inv, ic, out rewindRep))
                    rec.RewindReservedRep = rewindRep;
            }

            // Mutable playback state
            string pidStr = recNode.GetValue("spawnedPid");
            if (pidStr != null)
            {
                uint spawnedPid;
                if (uint.TryParse(pidStr, NumberStyles.Integer, ic, out spawnedPid))
                {
                    rec.SpawnedVesselPersistentId = spawnedPid;
                    // Invariant: VesselSpawned ⇔ SpawnedVesselPersistentId != 0. The field
                    // is not serialized directly; re-derive on load. Without this, the
                    // scene-enter resume path (TryFindCommittedTreeForSpawnedVessel) fails
                    // its `!VesselSpawned` filter after any save/load, so auto-record
                    // doesn't resume when the player re-enters a vessel that already has
                    // a committed recording (fix for v0.8.3 playtest bug).
                    rec.VesselSpawned = spawnedPid != 0;
                }
            }
            string destroyedStr = recNode.GetValue("vesselDestroyed");
            if (destroyedStr != null)
            {
                bool destroyed;
                if (bool.TryParse(destroyedStr, out destroyed))
                    rec.VesselDestroyed = destroyed;
            }
            rec.TerminalSpawnSupersededByRecordingId = recNode.GetValue("terminalSpawnSupersededBy");
            // #573/#589: load scoped post-rewind suppression marker. Older saves
            // only contain the bool because the original fix marked whole trees;
            // tag those as legacy-unscoped so the spawn gate can clear them.
            string spawnSuppressedStr = recNode.GetValue("spawnSuppressedByRewind");
            if (spawnSuppressedStr != null)
            {
                bool spawnSuppressed;
                if (bool.TryParse(spawnSuppressedStr, out spawnSuppressed))
                    rec.SpawnSuppressedByRewind = spawnSuppressed;
            }
            if (rec.SpawnSuppressedByRewind)
            {
                rec.SpawnSuppressedByRewindReason = recNode.GetValue("spawnSuppressedByRewindReason");
                string spawnSuppressedUTStr = recNode.GetValue("spawnSuppressedByRewindUT");
                if (spawnSuppressedUTStr != null)
                {
                    double spawnSuppressedUT;
                    if (double.TryParse(spawnSuppressedUTStr, NumberStyles.Float, ic, out spawnSuppressedUT))
                        rec.SpawnSuppressedByRewindUT = spawnSuppressedUT;
                }

                if (string.IsNullOrEmpty(rec.SpawnSuppressedByRewindReason))
                    rec.SpawnSuppressedByRewindReason = ParsekScenario.RewindSpawnSuppressionReasonLegacyUnscoped;
            }
            string resIdxStr = recNode.GetValue("lastResIdx");
            if (resIdxStr != null)
            {
                int resIdx;
                if (int.TryParse(resIdxStr, NumberStyles.Integer, ic, out resIdx))
                    rec.LastAppliedResourceIndex = resIdx;
            }
            // pointCount is informational — Points list is loaded from sidecar file

            // UI grouping tags (multi-group membership, backward compat with single value)
            string[] recGroups = recNode.GetValues("recordingGroup");
            if (recGroups != null && recGroups.Length > 0)
            {
                bool renamedAny = false;
                for (int g = 0; g < recGroups.Length; g++)
                {
                    recGroups[g] = Recording.ResolveLocalizedName(recGroups[g]);
                    // PR #328: rename the gloops group to a shorter label. Recordings
                    // from pre-rename builds keep working — the mapping runs once,
                    // marks the file dirty, and the next save writes the new name.
                    if (recGroups[g] == RecordingStore.LegacyGloopsGroupName)
                    {
                        recGroups[g] = RecordingStore.GloopsGroupName;
                        renamedAny = true;
                    }
                }
                rec.RecordingGroups = new List<string>(recGroups);
                if (renamedAny)
                    rec.FilesDirty = true;
            }
            rec.AutoAssignedStandaloneGroupName = recNode.GetValue("autoAssignedStandaloneGroup");

            // Controller info
            ConfigNode[] ctrlNodes = recNode.GetNodes("CONTROLLER");
            if (ctrlNodes.Length > 0)
            {
                rec.Controllers = new List<ControllerInfo>(ctrlNodes.Length);
                for (int i = 0; i < ctrlNodes.Length; i++)
                {
                    var ctrl = new ControllerInfo();
                    ctrl.type = ctrlNodes[i].GetValue("type") ?? "";
                    ctrl.partName = ctrlNodes[i].GetValue("part") ?? "";
                    uint pid;
                    if (uint.TryParse(ctrlNodes[i].GetValue("pid"), NumberStyles.Integer, ic, out pid))
                        ctrl.partPersistentId = pid;
                    rec.Controllers.Add(ctrl);
                }
                ParsekLog.Verbose("RecordingTree",
                    $"LoadRecordingResourceAndState: loaded {rec.Controllers.Count} controller(s) for recording={rec.RecordingId}");
            }

            string isDebrisStr = recNode.GetValue("isDebris");
            if (isDebrisStr != null)
            {
                bool isDebris;
                if (bool.TryParse(isDebrisStr, out isDebris))
                    rec.IsDebris = isDebris;
            }

            string isGhostOnlyStr = recNode.GetValue("isGhostOnly");
            if (isGhostOnlyStr != null)
            {
                bool isGhostOnly;
                if (bool.TryParse(isGhostOnlyStr, out isGhostOnly))
                    rec.IsGhostOnly = isGhostOnly;
            }

            // Max distance from launch (#302)
            string maxDistStr = recNode.GetValue("maxDist");
            if (maxDistStr != null)
            {
                double maxDist;
                if (double.TryParse(maxDistStr, inv, ic, out maxDist))
                    rec.MaxDistanceFromLaunch = maxDist;
            }

            // Cascade depth (#284). Missing key = 0 (legacy save or gen-0 recording).
            string generationStr = recNode.GetValue("generation");
            if (generationStr != null)
            {
                int generation;
                if (int.TryParse(generationStr, NumberStyles.Integer, ic, out generation))
                    rec.Generation = generation;
            }

            // Crew end states (kerbals module)
            string crewEndStatesResolvedStr = recNode.GetValue("crewEndStatesResolved");
            if (crewEndStatesResolvedStr != null)
            {
                bool crewEndStatesResolved;
                if (bool.TryParse(crewEndStatesResolvedStr, out crewEndStatesResolved))
                    rec.CrewEndStatesResolved = crewEndStatesResolved;
            }
            RecordingStore.DeserializeCrewEndStates(recNode, rec);
            if (rec.CrewEndStates != null)
                rec.CrewEndStatesResolved = true;

            // Resource manifests (Phase 11)
            RecordingStore.DeserializeResourceManifest(recNode, rec);

            // Inventory manifests (Phase 11)
            RecordingStore.DeserializeInventoryManifest(recNode, rec);
            string startInvSlotsStr = recNode.GetValue("startInvSlots");
            if (startInvSlotsStr != null)
            {
                int startInvSlots;
                if (int.TryParse(startInvSlotsStr, NumberStyles.Integer, ic, out startInvSlots))
                    rec.StartInventorySlots = startInvSlots;
            }
            string endInvSlotsStr = recNode.GetValue("endInvSlots");
            if (endInvSlotsStr != null)
            {
                int endInvSlots;
                if (int.TryParse(endInvSlotsStr, NumberStyles.Integer, ic, out endInvSlots))
                    rec.EndInventorySlots = endInvSlots;
            }

            // Crew manifests (Phase 11)
            RecordingStore.DeserializeCrewManifest(recNode, rec);

            // Dock target vessel PID (Phase 11)
            string dockTargetPidStr = recNode.GetValue("dockTargetPid");
            if (dockTargetPidStr != null)
            {
                uint dockTargetPid;
                if (uint.TryParse(dockTargetPidStr, NumberStyles.Integer, ic, out dockTargetPid))
                    rec.DockTargetVesselPid = dockTargetPid;
            }

            // Rewind-to-Staging (design section 5.5 + 9). Legacy saves without `mergeState`
            // default to Immutable. Saves that carried the old binary `committed` bool map
            // to the tri-state via RecordingStore's batch migration helper (idempotent,
            // one-shot logged). Stray transient SupersedeTargetId on committed recordings
            // is logged Warn and treated as cleared.
            string mergeStateStr = recNode.GetValue("mergeState");
            bool mergeStateWasExplicit = false;
            if (mergeStateStr != null)
            {
                mergeStateWasExplicit = true;
                MergeState parsed;
                if (Enum.TryParse(mergeStateStr, out parsed))
                    rec.MergeState = parsed;
                else
                    ParsekLog.Warn("RecordingTree",
                        $"LoadRecordingFrom: unknown mergeState '{mergeStateStr}' for rec={rec.RecordingId} — defaulting to Immutable");
            }
            else
            {
                rec.MergeState = MergeState.Immutable;
            }

            // Legacy migration: binary `committed` bool -> MergeState tri-state. The field
            // was never shipped in a release but design section 9 defines the mapping for
            // forward safety. Counter incremented in RecordingStore for a one-shot Info log.
            if (!mergeStateWasExplicit)
            {
                string committedStr = recNode.GetValue("committed");
                if (committedStr != null)
                {
                    bool committed;
                    if (bool.TryParse(committedStr, out committed))
                    {
                        rec.MergeState = committed ? MergeState.Immutable : MergeState.NotCommitted;
                        RecordingStore.BumpLegacyMergeStateMigrationCounterForTesting();
                    }
                }
            }

            rec.CreatingSessionId = recNode.GetValue("creatingSessionId");
            rec.SupersedeTargetId = recNode.GetValue("supersedeTargetId");
            rec.ProvisionalForRpId = recNode.GetValue("provisionalForRpId");

            if (!string.IsNullOrEmpty(rec.SupersedeTargetId)
                && rec.MergeState != MergeState.NotCommitted)
            {
                ParsekLog.Warn("Recording",
                    $"Stray SupersedeTargetId on committed rec={rec.RecordingId}; treating as cleared");
                rec.SupersedeTargetId = null;
            }
        }

        #endregion

        // --- BranchPoint serialization helpers ---

        internal static void SaveBranchPointInto(ConfigNode bpNode, BranchPoint bp)
        {
            var ic = CultureInfo.InvariantCulture;

            bpNode.AddValue("id", bp.Id ?? "");
            bpNode.AddValue("ut", bp.UT.ToString("R", ic));
            bpNode.AddValue("type", ((int)bp.Type).ToString(ic));

            for (int i = 0; i < bp.ParentRecordingIds.Count; i++)
                bpNode.AddValue("parentId", bp.ParentRecordingIds[i] ?? "");

            for (int i = 0; i < bp.ChildRecordingIds.Count; i++)
                bpNode.AddValue("childId", bp.ChildRecordingIds[i] ?? "");

            // SPLIT metadata
            if (bp.SplitCause != null)
                bpNode.AddValue("splitCause", bp.SplitCause);
            if (bp.DecouplerPartId != 0)
                bpNode.AddValue("decouplerPartId", bp.DecouplerPartId.ToString(ic));

            // BREAKUP metadata
            if (bp.BreakupCause != null)
                bpNode.AddValue("breakupCause", bp.BreakupCause);
            if (bp.BreakupDuration != 0)
                bpNode.AddValue("breakupDuration", bp.BreakupDuration.ToString("R", ic));
            if (bp.DebrisCount != 0)
                bpNode.AddValue("debrisCount", bp.DebrisCount.ToString(ic));
            if (bp.CoalesceWindow != 0)
                bpNode.AddValue("coalesceWindow", bp.CoalesceWindow.ToString("R", ic));

            // MERGE metadata
            if (bp.MergeCause != null)
                bpNode.AddValue("mergeCause", bp.MergeCause);
            if (bp.TargetVesselPersistentId != 0)
                bpNode.AddValue("targetVesselPid", bp.TargetVesselPersistentId.ToString(ic));

            // TERMINAL metadata
            if (bp.TerminalCause != null)
                bpNode.AddValue("terminalCause", bp.TerminalCause);

            // Rewind-to-Staging (design section 5.4)
            if (!string.IsNullOrEmpty(bp.RewindPointId))
                bpNode.AddValue("rewindPointId", bp.RewindPointId);

            ParsekLog.Verbose("RecordingTree",
                $"SaveBranchPoint: id={bp.Id} type={bp.Type} ut={bp.UT.ToString("F1", ic)}" +
                (bp.SplitCause != null ? $" splitCause={bp.SplitCause}" : "") +
                (bp.DecouplerPartId != 0 ? $" decouplerPartId={bp.DecouplerPartId}" : "") +
                (bp.BreakupCause != null ? $" breakupCause={bp.BreakupCause}" : "") +
                (bp.BreakupDuration != 0 ? $" breakupDuration={bp.BreakupDuration.ToString("F3", ic)}" : "") +
                (bp.DebrisCount != 0 ? $" debrisCount={bp.DebrisCount}" : "") +
                (bp.CoalesceWindow != 0 ? $" coalesceWindow={bp.CoalesceWindow.ToString("F3", ic)}" : "") +
                (bp.MergeCause != null ? $" mergeCause={bp.MergeCause}" : "") +
                (bp.TargetVesselPersistentId != 0 ? $" targetVesselPid={bp.TargetVesselPersistentId}" : "") +
                (bp.TerminalCause != null ? $" terminalCause={bp.TerminalCause}" : ""));
        }

        internal static BranchPoint LoadBranchPointFrom(ConfigNode bpNode)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            var bp = new BranchPoint();
            bp.Id = bpNode.GetValue("id") ?? "";
            double.TryParse(bpNode.GetValue("ut"), inv, ic, out bp.UT);

            int typeInt;
            if (int.TryParse(bpNode.GetValue("type"), NumberStyles.Integer, ic, out typeInt))
            {
                if (Enum.IsDefined(typeof(BranchPointType), typeInt))
                {
                    bp.Type = (BranchPointType)typeInt;
                }
                else
                {
                    ParsekLog.Warn("RecordingTree",
                        $"LoadBranchPoint: unknown type integer {typeInt} for id={bp.Id}, defaulting to Undock(0)");
                    bp.Type = BranchPointType.Undock;
                }
            }

            string[] parentIds = bpNode.GetValues("parentId");
            bp.ParentRecordingIds = new List<string>(parentIds);

            string[] childIds = bpNode.GetValues("childId");
            bp.ChildRecordingIds = new List<string>(childIds);

            // SPLIT metadata
            bp.SplitCause = bpNode.GetValue("splitCause");
            string decouplerPartIdStr = bpNode.GetValue("decouplerPartId");
            if (decouplerPartIdStr != null)
            {
                uint decouplerPartId;
                if (uint.TryParse(decouplerPartIdStr, NumberStyles.Integer, ic, out decouplerPartId))
                    bp.DecouplerPartId = decouplerPartId;
            }

            // BREAKUP metadata
            bp.BreakupCause = bpNode.GetValue("breakupCause");
            string breakupDurationStr = bpNode.GetValue("breakupDuration");
            if (breakupDurationStr != null)
            {
                double breakupDuration;
                if (double.TryParse(breakupDurationStr, inv, ic, out breakupDuration))
                    bp.BreakupDuration = breakupDuration;
            }
            string debrisCountStr = bpNode.GetValue("debrisCount");
            if (debrisCountStr != null)
            {
                int debrisCount;
                if (int.TryParse(debrisCountStr, NumberStyles.Integer, ic, out debrisCount))
                    bp.DebrisCount = debrisCount;
            }
            string coalesceWindowStr = bpNode.GetValue("coalesceWindow");
            if (coalesceWindowStr != null)
            {
                double coalesceWindow;
                if (double.TryParse(coalesceWindowStr, inv, ic, out coalesceWindow))
                    bp.CoalesceWindow = coalesceWindow;
            }

            // MERGE metadata
            bp.MergeCause = bpNode.GetValue("mergeCause");
            string targetVesselPidStr = bpNode.GetValue("targetVesselPid");
            if (targetVesselPidStr != null)
            {
                uint targetVesselPid;
                if (uint.TryParse(targetVesselPidStr, NumberStyles.Integer, ic, out targetVesselPid))
                    bp.TargetVesselPersistentId = targetVesselPid;
            }

            // TERMINAL metadata
            bp.TerminalCause = bpNode.GetValue("terminalCause");

            // Rewind-to-Staging (design section 5.4). Absent -> null.
            string rpId = bpNode.GetValue("rewindPointId");
            bp.RewindPointId = string.IsNullOrEmpty(rpId) ? null : rpId;

            ParsekLog.Verbose("RecordingTree",
                $"LoadBranchPoint: id={bp.Id} type={bp.Type} ut={bp.UT.ToString("F1", ic)}" +
                (bp.SplitCause != null ? $" splitCause={bp.SplitCause}" : "") +
                (bp.DecouplerPartId != 0 ? $" decouplerPartId={bp.DecouplerPartId}" : "") +
                (bp.BreakupCause != null ? $" breakupCause={bp.BreakupCause}" : "") +
                (bp.BreakupDuration != 0 ? $" breakupDuration={bp.BreakupDuration.ToString("F3", ic)}" : "") +
                (bp.DebrisCount != 0 ? $" debrisCount={bp.DebrisCount}" : "") +
                (bp.CoalesceWindow != 0 ? $" coalesceWindow={bp.CoalesceWindow.ToString("F3", ic)}" : "") +
                (bp.MergeCause != null ? $" mergeCause={bp.MergeCause}" : "") +
                (bp.TargetVesselPersistentId != 0 ? $" targetVesselPid={bp.TargetVesselPersistentId}" : "") +
                (bp.TerminalCause != null ? $" terminalCause={bp.TerminalCause}" : ""));

            return bp;
        }

        // --- Leaf identification ---

        /// <summary>
        /// Identifies spawnable leaf recordings: no children, not terminal
        /// (Destroyed/Recovered/Docked/Boarded), has vessel snapshot.
        /// </summary>
        public List<Recording> GetSpawnableLeaves()
        {
            var leaves = new List<Recording>();
            foreach (var rec in Recordings.Values)
            {
                if (IsSpawnableLeaf(rec))
                    leaves.Add(rec);
            }
            return leaves;
        }

        /// <summary>
        /// Identifies ALL leaf recordings (including destroyed/recovered).
        /// A leaf is any recording with ChildBranchPointId == null.
        /// </summary>
        public List<Recording> GetAllLeaves()
        {
            var leaves = new List<Recording>();
            foreach (var rec in Recordings.Values)
            {
                if (rec.ChildBranchPointId == null)
                    leaves.Add(rec);
            }
            return leaves;
        }

        /// <summary>
        /// Checks whether a recording is a spawnable leaf:
        /// 1. No children (ChildBranchPointId is null)
        /// 2. Terminal state allows spawning (not Destroyed/Recovered/Docked/Boarded)
        /// 3. Has a vessel snapshot
        /// </summary>
        internal static bool IsSpawnableLeaf(Recording rec)
        {
            if (rec.ChildBranchPointId != null)
                return false;

            if (rec.TerminalStateValue.HasValue)
            {
                var ts = rec.TerminalStateValue.Value;
                if (ts == TerminalState.Destroyed || ts == TerminalState.Recovered
                    || ts == TerminalState.Docked || ts == TerminalState.Boarded)
                    return false;
            }

            if (rec.VesselSnapshot == null)
                return false;

            return true;
        }

        /// <summary>
        /// Assigns terminal state based on vessel situation.
        /// Pure static method for testability.
        /// </summary>
        internal static TerminalState DetermineTerminalState(int situation)
        {
            // Vessel.Situations enum values: LANDED=1, SPLASHED=2, PRELAUNCH=4,
            // FLYING=8, SUB_ORBITAL=16, ORBITING=32, ESCAPING=64, DOCKED=128
            switch (situation)
            {
                case 32: // ORBITING
                    return TerminalState.Orbiting;
                case 1: // LANDED
                    return TerminalState.Landed;
                case 2: // SPLASHED
                    return TerminalState.Splashed;
                case 16: // SUB_ORBITAL
                case 8:  // FLYING
                case 64: // ESCAPING
                    return TerminalState.SubOrbital;
                case 4:  // PRELAUNCH
                    return TerminalState.Landed;
                case 128: // DOCKED
                    return TerminalState.Docked;
                default:
                    ParsekLog.Warn("RecordingTree", $"DetermineTerminalState: unexpected situation={situation}, defaulting to SubOrbital");
                    return TerminalState.SubOrbital;
            }
        }

        /// <summary>
        /// Assigns terminal state based on vessel situation, with orbit-aware override.
        /// KSP can report SUB_ORBITAL for a vessel with a stable bound orbit, and
        /// ORBITING for a ballistic coast whose periapsis is below the body surface.
        /// This overload checks the vessel's actual orbit to correct both cases.
        /// </summary>
        internal static TerminalState DetermineTerminalState(int situation, Vessel vessel)
        {
            TerminalState baseState = DetermineTerminalState(situation);
            if (vessel?.orbit == null || vessel.orbit.referenceBody == null)
                return baseState;

            TerminalState resolved = DetermineTerminalStateFromOrbitEvidence(
                situation,
                vessel.orbit.eccentricity,
                vessel.orbit.PeR,
                vessel.orbit.referenceBody.Radius);

            if (baseState == TerminalState.SubOrbital && resolved == TerminalState.Orbiting)
            {
                ParsekLog.Info("RecordingTree",
                    $"DetermineTerminalState: overriding SUB_ORBITAL to Orbiting - vessel has bound orbit " +
                    $"(ecc={vessel.orbit.eccentricity:F4}, PeR={vessel.orbit.PeR:F0}, " +
                    $"bodyR={vessel.orbit.referenceBody.Radius:F0})");
            }
            else if (baseState == TerminalState.Orbiting && resolved == TerminalState.SubOrbital)
            {
                ParsekLog.Info("RecordingTree",
                    $"DetermineTerminalState: overriding ORBITING to SubOrbital - periapsis is below surface " +
                    $"(ecc={vessel.orbit.eccentricity:F4}, PeR={vessel.orbit.PeR:F0}, " +
                    $"bodyR={vessel.orbit.referenceBody.Radius:F0})");
            }

            return resolved;
        }

        internal static TerminalState DetermineTerminalStateFromOrbitEvidence(
            int situation,
            double eccentricity,
            double periapsisRadius,
            double bodyRadius)
        {
            TerminalState baseState = DetermineTerminalState(situation);
            if (!IsFinite(eccentricity)
                || !IsFinite(periapsisRadius)
                || !IsFinite(bodyRadius)
                || bodyRadius <= 0.0)
            {
                return baseState;
            }

            if (baseState == TerminalState.SubOrbital
                && situation == 16
                && eccentricity < 1.0
                && periapsisRadius > bodyRadius)
            {
                return TerminalState.Orbiting;
            }

            if (baseState == TerminalState.Orbiting
                && situation == 32
                && periapsisRadius <= bodyRadius)
            {
                return TerminalState.SubOrbital;
            }

            return baseState;
        }

        private static bool IsFinite(double value)
        {
            return !double.IsNaN(value) && !double.IsInfinity(value);
        }

        static bool IsNonSpawnableTerminal(TerminalState terminalState)
        {
            return terminalState == TerminalState.Destroyed
                || terminalState == TerminalState.Recovered
                || terminalState == TerminalState.Docked
                || terminalState == TerminalState.Boarded;
        }

        /// <summary>
        /// Pure decision method: checks whether all leaf recordings in a tree have
        /// non-spawnable terminal states (Destroyed, Recovered, Docked, Boarded).
        /// A recording is a leaf if it has no ChildBranchPointId.
        /// Leaves with null TerminalStateValue are considered NOT terminal (still active).
        /// If activeRecordingId is non-null, the active recording is treated as alive
        /// unless activeVesselDestroyed is true.
        /// </summary>
        internal static bool AreAllLeavesTerminal(
            Dictionary<string, Recording> recordings,
            string activeRecordingId,
            bool activeVesselDestroyed)
        {
            if (recordings.Count == 0)
            {
                ParsekLog.Verbose("TreeDestruction", "AreAllLeavesTerminal: empty recordings dict — returning true");
                return true;
            }

            foreach (var kvp in recordings)
            {
                var rec = kvp.Value;

                // Skip non-leaf recordings (they branched into children)
                if (rec.ChildBranchPointId != null)
                    continue;

                bool isActiveRecording = activeRecordingId != null && rec.RecordingId == activeRecordingId;

                // Leaf: active recording still alive — tree is not fully terminal
                if (isActiveRecording && !activeVesselDestroyed)
                {
                    ParsekLog.Verbose("TreeDestruction",
                        $"AreAllLeavesTerminal: leaf '{rec.RecordingId}' ({rec.VesselName}) is active and alive — NOT terminal");
                    return false;
                }

                // Active recording with destroyed vessel: treat as terminal even if
                // TerminalStateValue hasn't been set yet (recorder knows it's dead,
                // but FinalizeTreeRecordings hasn't run to set the terminal state)
                if (isActiveRecording && activeVesselDestroyed)
                {
                    ParsekLog.Verbose("TreeDestruction",
                        $"AreAllLeavesTerminal: leaf '{rec.RecordingId}' ({rec.VesselName}) is active but vessel destroyed — terminal");
                    continue;
                }

                // Leaf: no terminal state means still recording / not finalized
                if (!rec.TerminalStateValue.HasValue)
                {
                    ParsekLog.Verbose("TreeDestruction",
                        $"AreAllLeavesTerminal: leaf '{rec.RecordingId}' ({rec.VesselName}) has no terminal state — NOT terminal");
                    return false;
                }

                var ts = rec.TerminalStateValue.Value;
                if (IsNonSpawnableTerminal(ts))
                {
                    // Non-spawnable terminal state — this leaf is done
                    ParsekLog.Verbose("TreeDestruction",
                        $"AreAllLeavesTerminal: leaf '{rec.RecordingId}' ({rec.VesselName}) terminal={ts} — dead");
                    continue;
                }

                // Spawnable terminal state (Orbiting, Landed, SubOrbital, Splashed) — vessel could be spawned
                ParsekLog.Verbose("TreeDestruction",
                    $"AreAllLeavesTerminal: leaf '{rec.RecordingId}' ({rec.VesselName}) terminal={ts} — spawnable, NOT terminal");
                return false;
            }

            ParsekLog.Verbose("TreeDestruction", "AreAllLeavesTerminal: all leaves are terminal — returning true");
            return true;
        }

        /// <summary>
        /// Returns true when the only leaves still blocking same-scene crash finalization
        /// are debris leaves. This is used only to decide whether the active-crash flow
        /// should keep waiting for a debris-only fallback owner; it does NOT make the tree
        /// merge-ready on its own.
        /// </summary>
        internal static bool AreAllActiveCrashBlockersDebris(
            Dictionary<string, Recording> recordings,
            string activeRecordingId)
        {
            bool sawBlockingLeaf = false;

            foreach (var kvp in recordings)
            {
                var rec = kvp.Value;
                if (rec.ChildBranchPointId != null)
                    continue;

                bool isActiveRecording = activeRecordingId != null && rec.RecordingId == activeRecordingId;
                if (isActiveRecording)
                    continue;

                if (!rec.TerminalStateValue.HasValue)
                {
                    sawBlockingLeaf = true;
                    if (!rec.IsDebris)
                        return false;
                    continue;
                }

                if (IsNonSpawnableTerminal(rec.TerminalStateValue.Value))
                    continue;

                sawBlockingLeaf = true;
                if (!rec.IsDebris)
                    return false;
            }

            return sawBlockingLeaf;
        }

    }
}
