using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

namespace Parsek
{
    public class RecordingTree
    {
        internal const int CurrentTreeFormatVersion = 0;

        // --- Serialized fields ---
        public string Id;
        public string TreeName;                     // root vessel name at launch
        public string RootRecordingId;
        public string ActiveRecordingId;            // nullable: null if all background
        public string AutoGeneratedRootGroupName;
        public string AutoGeneratedDebrisGroupName;
        public string AutoGeneratedCrewGroupName;
        public int TreeFormatVersion;

        public Dictionary<string, Recording> Recordings
            = new Dictionary<string, Recording>();
        public List<BranchPoint> BranchPoints = new List<BranchPoint>();

        // --- Runtime-only fields (not serialized) ---
        // Maps vessel persistentId -> recordingId for background vessel lookup.
        // Rebuilt from Recordings on load via RebuildBackgroundMap().
        public Dictionary<uint, string> BackgroundMap
            = new Dictionary<uint, string>();

        // Set of all vessel PIDs that appear anywhere in this tree's recordings.
        // This is archived-history membership, not a globally unique ownership claim.
        // Used by ghost skip logic to answer the tree-local question
        // "does this PID appear in this tree at all?".
        // Rebuilt alongside BackgroundMap via RebuildBackgroundMap().
        public HashSet<uint> RecordedVesselPids = new HashSet<uint>();

        internal void AddOrReplaceRecording(Recording rec)
        {
            if (rec == null || string.IsNullOrEmpty(rec.RecordingId))
                return;

            AssignTreeOrderIfMissing(rec);
            Recordings[rec.RecordingId] = rec;
        }

        internal static RecordingTree DeepClone(RecordingTree source)
        {
            if (source == null)
                return null;

            var clone = new RecordingTree
            {
                Id = source.Id,
                TreeName = source.TreeName,
                RootRecordingId = source.RootRecordingId,
                ActiveRecordingId = source.ActiveRecordingId,
                AutoGeneratedRootGroupName = source.AutoGeneratedRootGroupName,
                AutoGeneratedDebrisGroupName = source.AutoGeneratedDebrisGroupName,
                AutoGeneratedCrewGroupName = source.AutoGeneratedCrewGroupName,
                TreeFormatVersion = source.TreeFormatVersion,
                BackgroundMap = source.BackgroundMap != null
                    ? new Dictionary<uint, string>(source.BackgroundMap)
                    : new Dictionary<uint, string>(),
                RecordedVesselPids = source.RecordedVesselPids != null
                    ? new HashSet<uint>(source.RecordedVesselPids)
                    : new HashSet<uint>()
            };

            if (source.Recordings != null)
            {
                foreach (var kvp in source.Recordings)
                {
                    Recording clonedRecording = Recording.DeepClone(kvp.Value);
                    if (clonedRecording != null)
                        clone.Recordings[kvp.Key] = clonedRecording;
                }
            }

            if (source.BranchPoints != null)
            {
                for (int i = 0; i < source.BranchPoints.Count; i++)
                    clone.BranchPoints.Add(DeepCloneBranchPoint(source.BranchPoints[i]));
            }

            return clone;
        }

        private static BranchPoint DeepCloneBranchPoint(BranchPoint source)
        {
            if (source == null)
                return null;

            return new BranchPoint
            {
                Id = source.Id,
                UT = source.UT,
                Type = source.Type,
                ParentRecordingIds = source.ParentRecordingIds != null
                    ? new List<string>(source.ParentRecordingIds)
                    : new List<string>(),
                ChildRecordingIds = source.ChildRecordingIds != null
                    ? new List<string>(source.ChildRecordingIds)
                    : new List<string>(),
                SplitCause = source.SplitCause,
                DecouplerPartId = source.DecouplerPartId,
                BreakupCause = source.BreakupCause,
                BreakupDuration = source.BreakupDuration,
                DebrisCount = source.DebrisCount,
                CoalesceWindow = source.CoalesceWindow,
                MergeCause = source.MergeCause,
                TargetVesselPersistentId = source.TargetVesselPersistentId,
                TerminalCause = source.TerminalCause,
                RewindPointId = source.RewindPointId
            };
        }

        /// <summary>
        /// Returns the maximum EndUT across all recordings in this tree.
        /// Returns 0 if all recordings have 0 points (degraded tree).
        /// </summary>
        internal double ComputeEndUT()
        {
            double endUT = 0;
            foreach (var rec in Recordings.Values)
            {
                double recEnd = rec.EndUT;
                if (recEnd > endUT) endUT = recEnd;
            }
            return endUT;
        }

        /// <summary>
        /// Returns true if this tree has no trajectory data (all recordings have 0 points).
        /// Degraded trees should not have their budget applied.
        /// </summary>
        internal bool IsDegraded => ComputeEndUT() == 0;

        // --- Serialization ---

        public void Save(ConfigNode treeNode)
        {
            var ic = CultureInfo.InvariantCulture;

            treeNode.AddValue("id", Id ?? "");
            treeNode.AddValue("treeName", TreeName ?? "");
            treeNode.AddValue("rootRecordingId", RootRecordingId ?? "");
            TreeFormatVersion = CurrentTreeFormatVersion;
            treeNode.AddValue("treeFormatVersion", TreeFormatVersion.ToString(ic));
            treeNode.AddValue("recordingSchemaGeneration", RecordingStore.CurrentRecordingSchemaGeneration.ToString(ic));
            if (ActiveRecordingId != null)
                treeNode.AddValue("activeRecordingId", ActiveRecordingId);
            if (!string.IsNullOrEmpty(AutoGeneratedRootGroupName))
                treeNode.AddValue("autoGeneratedRootGroupName", AutoGeneratedRootGroupName);
            if (!string.IsNullOrEmpty(AutoGeneratedDebrisGroupName))
                treeNode.AddValue("autoGeneratedDebrisGroupName", AutoGeneratedDebrisGroupName);
            if (!string.IsNullOrEmpty(AutoGeneratedCrewGroupName))
                treeNode.AddValue("autoGeneratedCrewGroupName", AutoGeneratedCrewGroupName);

            // Phase F: legacy resource fields (preTreeFunds/preTreeScience/preTreeRep,
            // deltaFunds/deltaScience/deltaRep, resourcesApplied) are NOT written
            // anymore. They remain on the in-memory type so Phase A's load-time
            // migration in LedgerOrchestrator can still read pre-Phase-F .sfs files,
            // but the new save shape carries the ledger as the single source of truth.

            // Serialize each recording
            EnsureRecordingTreeOrder();
            var orderedRecordings = new List<Recording>(Recordings.Values);
            orderedRecordings.Sort(CompareRecordingTreeOrder);
            foreach (var rec in orderedRecordings)
            {
                ConfigNode recNode = treeNode.AddNode("RECORDING");
                SaveRecordingInto(recNode, rec);
            }

            // Serialize branch points
            for (int i = 0; i < BranchPoints.Count; i++)
            {
                ConfigNode bpNode = treeNode.AddNode("BRANCH_POINT");
                SaveBranchPointInto(bpNode, BranchPoints[i]);
            }

            // No per-tree log line here: this method is called once per committed tree
            // inside ParsekScenario.SaveTreeRecordings' loop, which would emit one line
            // per tree (hundreds with a large save). The caller logs a single batched
            // summary after the loop; the single-tree active/pending callers log their
            // own Info line.
        }

        public static RecordingTree Load(ConfigNode treeNode)
        {
            var ic = CultureInfo.InvariantCulture;

            var tree = new RecordingTree();
            tree.Id = treeNode.GetValue("id") ?? "";
            tree.TreeName = Recording.ResolveLocalizedName(treeNode.GetValue("treeName") ?? "");
            tree.RootRecordingId = treeNode.GetValue("rootRecordingId") ?? "";
            int treeFormatVersion;
            if (int.TryParse(treeNode.GetValue("treeFormatVersion"), NumberStyles.Integer, ic, out treeFormatVersion))
                tree.TreeFormatVersion = treeFormatVersion;
            else
                tree.TreeFormatVersion = 0;

            string schemaGenerationStr = treeNode.GetValue("recordingSchemaGeneration");
            if (!int.TryParse(schemaGenerationStr, NumberStyles.Integer, ic, out int treeSchemaGeneration)
                || treeSchemaGeneration != RecordingStore.CurrentRecordingSchemaGeneration)
            {
                ParsekLog.Warn("RecordingTree",
                    $"Load: skipped tree={tree.Id ?? "<no-tree>"} due to unsupported schema generation " +
                    $"generation={(schemaGenerationStr ?? "(missing)")} " +
                    $"expected={RecordingStore.CurrentRecordingSchemaGeneration.ToString(ic)}");
                tree.RootRecordingId = string.Empty;
                tree.ActiveRecordingId = null;
                tree.Recordings.Clear();
                tree.BranchPoints.Clear();
                return tree;
            }

            tree.ActiveRecordingId = treeNode.GetValue("activeRecordingId");
            tree.AutoGeneratedRootGroupName = treeNode.GetValue("autoGeneratedRootGroupName");
            tree.AutoGeneratedDebrisGroupName = treeNode.GetValue("autoGeneratedDebrisGroupName");
            tree.AutoGeneratedCrewGroupName = treeNode.GetValue("autoGeneratedCrewGroupName");

            // Load recordings
            HashSet<string> rejectedRecordingIds = null;
            ConfigNode[] recNodes = treeNode.GetNodes("RECORDING");
            for (int i = 0; i < recNodes.Length; i++)
            {
                var rec = new Recording();
                LoadRecordingFrom(recNodes[i], rec);
                if (rec.RecordingFormatVersion == -1)
                {
                    if (!string.IsNullOrEmpty(rec.RecordingId))
                    {
                        if (rejectedRecordingIds == null)
                            rejectedRecordingIds = new HashSet<string>(StringComparer.Ordinal);
                        rejectedRecordingIds.Add(rec.RecordingId);
                    }
                    ParsekLog.Warn("Codec",
                        $"RecordingTree.LoadFrom: skipped unsupported recording " +
                        $"id={rec.RecordingId ?? "<no-id>"} tree={tree.Id ?? "<no-tree>"}");
                    continue;
                }
                tree.AddOrReplaceRecording(rec);
            }

            // Load branch points
            ConfigNode[] bpNodes = treeNode.GetNodes("BRANCH_POINT");
            for (int i = 0; i < bpNodes.Length; i++)
            {
                tree.BranchPoints.Add(LoadBranchPointFrom(bpNodes[i]));
            }

            PruneRejectedRecordingReferences(tree, rejectedRecordingIds);
            tree.RebuildBackgroundMap();

            ParsekLog.Verbose("RecordingTree",
                $"Load: id={tree.Id} tree='{tree.TreeName}' recordings={tree.Recordings.Count} " +
                $"branchPoints={tree.BranchPoints.Count} treeFormatVersion={tree.TreeFormatVersion}");

            return tree;
        }

        private static void PruneRejectedRecordingReferences(
            RecordingTree tree,
            HashSet<string> rejectedRecordingIds)
        {
            if (tree == null || rejectedRecordingIds == null || rejectedRecordingIds.Count == 0)
                return;

            if (!string.IsNullOrEmpty(tree.RootRecordingId)
                && rejectedRecordingIds.Contains(tree.RootRecordingId))
            {
                int removedRecordings = tree.Recordings != null ? tree.Recordings.Count : 0;
                int rootRemovedBranchPoints = tree.BranchPoints != null ? tree.BranchPoints.Count : 0;
                string rootRecordingId = tree.RootRecordingId;
                tree.RootRecordingId = string.Empty;
                tree.ActiveRecordingId = null;
                if (tree.Recordings != null)
                    tree.Recordings.Clear();
                if (tree.BranchPoints != null)
                    tree.BranchPoints.Clear();
                if (tree.BackgroundMap != null)
                    tree.BackgroundMap.Clear();
                ParsekLog.Warn("RecordingTree",
                    $"Load: dropped entire tree id={tree.Id ?? "<no-tree>"} " +
                    $"because root recording '{rootRecordingId}' was rejected by schema gate; " +
                    $"removedRecordings={removedRecordings} removedBranchPoints={rootRemovedBranchPoints}");
                return;
            }

            if (!string.IsNullOrEmpty(tree.ActiveRecordingId)
                && rejectedRecordingIds.Contains(tree.ActiveRecordingId))
            {
                tree.ActiveRecordingId = null;
            }

            HashSet<string> removedBranchPointIds = null;
            int removedBranchPoints = 0;
            if (tree.BranchPoints != null)
            {
                for (int i = tree.BranchPoints.Count - 1; i >= 0; i--)
                {
                    BranchPoint bp = tree.BranchPoints[i];
                    bp.ParentRecordingIds?.RemoveAll(id => rejectedRecordingIds.Contains(id));
                    bp.ChildRecordingIds?.RemoveAll(id => rejectedRecordingIds.Contains(id));

                    int parentCount = bp.ParentRecordingIds != null ? bp.ParentRecordingIds.Count : 0;
                    int childCount = bp.ChildRecordingIds != null ? bp.ChildRecordingIds.Count : 0;
                    if (parentCount > 0 && childCount > 0)
                        continue;

                    if (removedBranchPointIds == null)
                        removedBranchPointIds = new HashSet<string>(StringComparer.Ordinal);
                    if (!string.IsNullOrEmpty(bp.Id))
                        removedBranchPointIds.Add(bp.Id);
                    tree.BranchPoints.RemoveAt(i);
                    removedBranchPoints++;
                }
            }

            foreach (Recording rec in tree.Recordings.Values)
            {
                ClearRejectedRecordingReferences(rec, rejectedRecordingIds, removedBranchPointIds);
            }

            ParsekLog.Warn("RecordingTree",
                $"Load: pruned references to {rejectedRecordingIds.Count} metadata-rejected recording(s) " +
                $"from tree={tree.Id ?? "<no-tree>"} removedBranchPoints={removedBranchPoints}");
        }

        /// <summary>
        /// Clears a single recording's references to schema-rejected recordings and removed
        /// branch points: nulls ParentRecordingId / ParentAnchorRecordingId when they point at a
        /// rejected recording id, and nulls ParentBranchPointId / ChildBranchPointId when they
        /// point at a removed branch point. Short-circuits on a null recording and on an empty
        /// removed-branch-point set. Mutates the recording.
        /// </summary>
        internal static void ClearRejectedRecordingReferences(
            Recording rec,
            HashSet<string> rejectedRecordingIds,
            HashSet<string> removedBranchPointIds)
        {
            if (rec == null)
                return;

            if (!string.IsNullOrEmpty(rec.ParentRecordingId)
                && rejectedRecordingIds.Contains(rec.ParentRecordingId))
            {
                rec.ParentRecordingId = null;
            }

            if (!string.IsNullOrEmpty(rec.ParentAnchorRecordingId)
                && rejectedRecordingIds.Contains(rec.ParentAnchorRecordingId))
            {
                rec.ParentAnchorRecordingId = null;
            }

            if (removedBranchPointIds == null || removedBranchPointIds.Count == 0)
                return;

            if (!string.IsNullOrEmpty(rec.ParentBranchPointId)
                && removedBranchPointIds.Contains(rec.ParentBranchPointId))
            {
                rec.ParentBranchPointId = null;
            }

            if (!string.IsNullOrEmpty(rec.ChildBranchPointId)
                && removedBranchPointIds.Contains(rec.ChildBranchPointId))
            {
                rec.ChildBranchPointId = null;
            }
        }

        public void RebuildBackgroundMap()
        {
            BackgroundMap.Clear();
            RecordedVesselPids.Clear();
            EnsureRecordingTreeOrder();
            var duplicateEligiblePids = new HashSet<uint>();
            var duplicateExamples = new List<string>();
            var orderedRecordings = new List<Recording>(Recordings.Values);
            orderedRecordings.Sort(CompareRecordingTreeOrder);
            int activePidSkips = 0;
            foreach (var rec in orderedRecordings)
            {
                if (rec.VesselPersistentId != 0)
                    RecordedVesselPids.Add(rec.VesselPersistentId);

                if (!string.Equals(rec.RecordingId, ActiveRecordingId, StringComparison.Ordinal)
                    && SharesVesselPidWithActiveRecording(rec))
                {
                    activePidSkips++;
                }

                if (IsBackgroundMapEligible(rec))
                {
                    if (BackgroundMap.TryGetValue(rec.VesselPersistentId, out string existingId))
                    {
                        duplicateEligiblePids.Add(rec.VesselPersistentId);

                        if (duplicateExamples.Count < 3)
                        {
                            duplicateExamples.Add(
                                $"{rec.VesselPersistentId}:{existingId}->{rec.RecordingId}");
                        }
                    }

                    BackgroundMap[rec.VesselPersistentId] = rec.RecordingId;
                }
            }

            if (duplicateEligiblePids.Count > 0)
            {
                string treeId = !string.IsNullOrEmpty(Id) ? Id : (TreeName ?? "unknown");
                string exampleSuffix = duplicateExamples.Count > 0
                    ? $" examples=[{string.Join(", ", duplicateExamples)}]"
                    : string.Empty;
                ParsekLog.VerboseRateLimited(
                    "RecordingTree",
                    $"bgmap-duplicate-{treeId}",
                    $"RebuildBackgroundMap: tree='{treeId}' has {duplicateEligiblePids.Count} " +
                    $"duplicate eligible PID(s); BackgroundMap kept the latest tree-order winner." +
                    exampleSuffix,
                    60.0);
            }

            ParsekLog.Verbose("RecordingTree",
                $"RebuildBackgroundMap: entries={BackgroundMap.Count} recordedPids={RecordedVesselPids.Count} totalRecordings={Recordings.Count} activePidSkips={activePidSkips}");
        }

        internal bool IsBackgroundMapEligible(Recording rec)
        {
            return rec != null
                && rec.VesselPersistentId != 0
                && rec.TerminalStateValue == null
                && !HasNextChainSegment(rec)
                && rec.ChildBranchPointId == null
                && rec.RecordingId != ActiveRecordingId
                && !SharesVesselPidWithActiveRecording(rec);
        }

        private bool SharesVesselPidWithActiveRecording(Recording rec)
        {
            if (rec == null || rec.VesselPersistentId == 0)
                return false;
            if (string.IsNullOrEmpty(ActiveRecordingId))
                return false;
            if (Recordings == null
                || !Recordings.TryGetValue(ActiveRecordingId, out Recording activeRec)
                || activeRec == null
                || activeRec.VesselPersistentId == 0)
            {
                return false;
            }

            return rec.VesselPersistentId == activeRec.VesselPersistentId;
        }

        private bool HasNextChainSegment(Recording rec)
        {
            if (rec == null || string.IsNullOrEmpty(rec.ChainId))
                return false;

            int nextIdx = rec.ChainIndex + 1;
            foreach (var other in Recordings.Values)
            {
                if (other.ChainId == rec.ChainId
                    && other.ChainIndex == nextIdx
                    && other.ChainBranch == rec.ChainBranch)
                {
                    return true;
                }
            }

            return false;
        }

        private void EnsureRecordingTreeOrder()
        {
            int nextOrder = 0;
            foreach (var rec in Recordings.Values)
            {
                if (rec != null && rec.TreeOrder >= nextOrder)
                    nextOrder = rec.TreeOrder + 1;
            }

            foreach (var rec in Recordings.Values)
            {
                if (rec != null && rec.TreeOrder < 0)
                    rec.TreeOrder = nextOrder++;
            }
        }

        private void AssignTreeOrderIfMissing(Recording rec)
        {
            if (rec == null || rec.TreeOrder >= 0)
                return;

            int nextOrder = 0;
            foreach (var existing in Recordings.Values)
            {
                if (existing != null && existing.TreeOrder >= nextOrder)
                    nextOrder = existing.TreeOrder + 1;
            }

            rec.TreeOrder = nextOrder;
        }

        private static int CompareRecordingTreeOrder(Recording a, Recording b)
        {
            if (ReferenceEquals(a, b))
                return 0;
            if (a == null)
                return -1;
            if (b == null)
                return 1;

            int aOrder = a.TreeOrder >= 0 ? a.TreeOrder : int.MaxValue;
            int bOrder = b.TreeOrder >= 0 ? b.TreeOrder : int.MaxValue;
            int cmp = aOrder.CompareTo(bOrder);
            if (cmp != 0)
                return cmp;

            cmp = a.StartUT.CompareTo(b.StartUT);
            if (cmp != 0)
                return cmp;

            cmp = a.EndUT.CompareTo(b.EndUT);
            if (cmp != 0)
                return cmp;

            return string.CompareOrdinal(a.RecordingId, b.RecordingId);
        }

        internal List<uint> FindDuplicateBackgroundMapPids()
        {
            var counts = new Dictionary<uint, int>();
            var duplicates = new List<uint>();

            foreach (var rec in Recordings.Values)
            {
                if (!IsBackgroundMapEligible(rec))
                    continue;

                int nextCount = 1;
                if (counts.TryGetValue(rec.VesselPersistentId, out int existing))
                    nextCount = existing + 1;

                counts[rec.VesselPersistentId] = nextCount;
                if (nextCount == 2)
                    duplicates.Add(rec.VesselPersistentId);
            }

            return duplicates;
        }
        // --- Recording serialization helpers ---

        internal static void SaveRecordingInto(ConfigNode recNode, Recording rec)
        {
            RecordingTreeRecordCodec.SaveRecordingInto(recNode, rec);
        }

        internal static void SaveRecordingResourceAndState(ConfigNode recNode, Recording rec)
        {
            RecordingTreeRecordCodec.SaveRecordingResourceAndState(recNode, rec);
        }

        internal static void LoadRecordingFrom(ConfigNode recNode, Recording rec)
        {
            RecordingTreeRecordCodec.LoadRecordingFrom(recNode, rec);

            RecordingEndpointResolver.BackfillEndpointDecision(rec, "RecordingTree.LoadRecordingFrom");

            ParsekLog.Verbose("RecordingTree",
                $"LoadRecordingFrom: id={rec.RecordingId} vessel='{rec.VesselName}' " +
                $"terminal={rec.TerminalStateValue?.ToString() ?? "null"} " +
                $"chain={rec.ChainId ?? "none"} formatVersion={rec.RecordingFormatVersion}");
        }

        internal static void LoadRecordingResourceAndState(ConfigNode recNode, Recording rec)
        {
            RecordingTreeRecordCodec.LoadRecordingResourceAndState(recNode, rec);
        }
        // --- BranchPoint serialization helpers ---

        internal static void SaveBranchPointInto(ConfigNode bpNode, BranchPoint bp)
        {
            var ic = CultureInfo.InvariantCulture;

            bpNode.AddValue("id", bp.Id ?? "");
            bpNode.AddValue("ut", bp.UT.ToString("R", ic));
            bpNode.AddValue("type", ((int)bp.Type).ToString(ic));

            for (int i = 0; i < bp.ParentRecordingIds.Count; i++)
                bpNode.AddValue("parentId", bp.ParentRecordingIds[i] ?? "");

            for (int i = 0; i < bp.ChildRecordingIds.Count; i++)
                bpNode.AddValue("childId", bp.ChildRecordingIds[i] ?? "");

            // SPLIT metadata
            if (bp.SplitCause != null)
                bpNode.AddValue("splitCause", bp.SplitCause);
            if (bp.DecouplerPartId != 0)
                bpNode.AddValue("decouplerPartId", bp.DecouplerPartId.ToString(ic));

            // BREAKUP metadata
            if (bp.BreakupCause != null)
                bpNode.AddValue("breakupCause", bp.BreakupCause);
            if (bp.BreakupDuration != 0)
                bpNode.AddValue("breakupDuration", bp.BreakupDuration.ToString("R", ic));
            if (bp.DebrisCount != 0)
                bpNode.AddValue("debrisCount", bp.DebrisCount.ToString(ic));
            if (bp.CoalesceWindow != 0)
                bpNode.AddValue("coalesceWindow", bp.CoalesceWindow.ToString("R", ic));

            // MERGE metadata
            if (bp.MergeCause != null)
                bpNode.AddValue("mergeCause", bp.MergeCause);
            if (bp.TargetVesselPersistentId != 0)
                bpNode.AddValue("targetVesselPid", bp.TargetVesselPersistentId.ToString(ic));

            // TERMINAL metadata
            if (bp.TerminalCause != null)
                bpNode.AddValue("terminalCause", bp.TerminalCause);

            // Rewind-to-Staging (design section 5.4)
            if (!string.IsNullOrEmpty(bp.RewindPointId))
                bpNode.AddValue("rewindPointId", bp.RewindPointId);

            ParsekLog.Verbose("RecordingTree",
                $"SaveBranchPoint: id={bp.Id} type={bp.Type} ut={bp.UT.ToString("F1", ic)}" +
                (bp.SplitCause != null ? $" splitCause={bp.SplitCause}" : "") +
                (bp.DecouplerPartId != 0 ? $" decouplerPartId={bp.DecouplerPartId}" : "") +
                (bp.BreakupCause != null ? $" breakupCause={bp.BreakupCause}" : "") +
                (bp.BreakupDuration != 0 ? $" breakupDuration={bp.BreakupDuration.ToString("F3", ic)}" : "") +
                (bp.DebrisCount != 0 ? $" debrisCount={bp.DebrisCount}" : "") +
                (bp.CoalesceWindow != 0 ? $" coalesceWindow={bp.CoalesceWindow.ToString("F3", ic)}" : "") +
                (bp.MergeCause != null ? $" mergeCause={bp.MergeCause}" : "") +
                (bp.TargetVesselPersistentId != 0 ? $" targetVesselPid={bp.TargetVesselPersistentId}" : "") +
                (bp.TerminalCause != null ? $" terminalCause={bp.TerminalCause}" : ""));
        }

        internal static BranchPoint LoadBranchPointFrom(ConfigNode bpNode)
        {
            var inv = NumberStyles.Float;
            var ic = CultureInfo.InvariantCulture;

            var bp = new BranchPoint();
            bp.Id = bpNode.GetValue("id") ?? "";
            double.TryParse(bpNode.GetValue("ut"), inv, ic, out bp.UT);

            int typeInt;
            if (int.TryParse(bpNode.GetValue("type"), NumberStyles.Integer, ic, out typeInt))
            {
                if (Enum.IsDefined(typeof(BranchPointType), typeInt))
                {
                    bp.Type = (BranchPointType)typeInt;
                }
                else
                {
                    ParsekLog.Warn("RecordingTree",
                        $"LoadBranchPoint: unknown type integer {typeInt} for id={bp.Id}, defaulting to Undock(0)");
                    bp.Type = BranchPointType.Undock;
                }
            }

            string[] parentIds = bpNode.GetValues("parentId");
            bp.ParentRecordingIds = new List<string>(parentIds);

            string[] childIds = bpNode.GetValues("childId");
            bp.ChildRecordingIds = new List<string>(childIds);

            // SPLIT metadata
            bp.SplitCause = bpNode.GetValue("splitCause");
            string decouplerPartIdStr = bpNode.GetValue("decouplerPartId");
            if (decouplerPartIdStr != null)
            {
                uint decouplerPartId;
                if (uint.TryParse(decouplerPartIdStr, NumberStyles.Integer, ic, out decouplerPartId))
                    bp.DecouplerPartId = decouplerPartId;
            }

            // BREAKUP metadata
            bp.BreakupCause = bpNode.GetValue("breakupCause");
            string breakupDurationStr = bpNode.GetValue("breakupDuration");
            if (breakupDurationStr != null)
            {
                double breakupDuration;
                if (double.TryParse(breakupDurationStr, inv, ic, out breakupDuration))
                    bp.BreakupDuration = breakupDuration;
            }
            string debrisCountStr = bpNode.GetValue("debrisCount");
            if (debrisCountStr != null)
            {
                int debrisCount;
                if (int.TryParse(debrisCountStr, NumberStyles.Integer, ic, out debrisCount))
                    bp.DebrisCount = debrisCount;
            }
            string coalesceWindowStr = bpNode.GetValue("coalesceWindow");
            if (coalesceWindowStr != null)
            {
                double coalesceWindow;
                if (double.TryParse(coalesceWindowStr, inv, ic, out coalesceWindow))
                    bp.CoalesceWindow = coalesceWindow;
            }

            // MERGE metadata
            bp.MergeCause = bpNode.GetValue("mergeCause");
            string targetVesselPidStr = bpNode.GetValue("targetVesselPid");
            if (targetVesselPidStr != null)
            {
                uint targetVesselPid;
                if (uint.TryParse(targetVesselPidStr, NumberStyles.Integer, ic, out targetVesselPid))
                    bp.TargetVesselPersistentId = targetVesselPid;
            }

            // TERMINAL metadata
            bp.TerminalCause = bpNode.GetValue("terminalCause");

            // Rewind-to-Staging (design section 5.4). Absent -> null.
            string rpId = bpNode.GetValue("rewindPointId");
            bp.RewindPointId = string.IsNullOrEmpty(rpId) ? null : rpId;

            ParsekLog.Verbose("RecordingTree",
                $"LoadBranchPoint: id={bp.Id} type={bp.Type} ut={bp.UT.ToString("F1", ic)}" +
                (bp.SplitCause != null ? $" splitCause={bp.SplitCause}" : "") +
                (bp.DecouplerPartId != 0 ? $" decouplerPartId={bp.DecouplerPartId}" : "") +
                (bp.BreakupCause != null ? $" breakupCause={bp.BreakupCause}" : "") +
                (bp.BreakupDuration != 0 ? $" breakupDuration={bp.BreakupDuration.ToString("F3", ic)}" : "") +
                (bp.DebrisCount != 0 ? $" debrisCount={bp.DebrisCount}" : "") +
                (bp.CoalesceWindow != 0 ? $" coalesceWindow={bp.CoalesceWindow.ToString("F3", ic)}" : "") +
                (bp.MergeCause != null ? $" mergeCause={bp.MergeCause}" : "") +
                (bp.TargetVesselPersistentId != 0 ? $" targetVesselPid={bp.TargetVesselPersistentId}" : "") +
                (bp.TerminalCause != null ? $" terminalCause={bp.TerminalCause}" : ""));

            return bp;
        }

        // --- Leaf identification ---

        /// <summary>
        /// Identifies spawnable leaf recordings: no children, not terminal
        /// (Destroyed/Recovered/Docked/Boarded), has vessel snapshot.
        /// </summary>
        public List<Recording> GetSpawnableLeaves()
        {
            var leaves = new List<Recording>();
            foreach (var rec in Recordings.Values)
            {
                if (IsSpawnableLeaf(rec))
                    leaves.Add(rec);
            }
            return leaves;
        }

        /// <summary>
        /// Identifies ALL leaf recordings (including destroyed/recovered).
        /// A leaf is any recording with ChildBranchPointId == null.
        /// </summary>
        public List<Recording> GetAllLeaves()
        {
            var leaves = new List<Recording>();
            foreach (var rec in Recordings.Values)
            {
                if (rec.ChildBranchPointId == null)
                    leaves.Add(rec);
            }
            return leaves;
        }

        /// <summary>
        /// Checks whether a recording is a spawnable leaf:
        /// 1. No children (ChildBranchPointId is null)
        /// 2. Terminal state allows spawning (not Destroyed/Recovered/Docked/Boarded)
        /// 3. Has a vessel snapshot
        /// </summary>
        internal static bool IsSpawnableLeaf(Recording rec)
        {
            if (rec.ChildBranchPointId != null)
                return false;

            if (rec.TerminalStateValue.HasValue)
            {
                var ts = rec.TerminalStateValue.Value;
                if (ts == TerminalState.Destroyed || ts == TerminalState.Recovered
                    || ts == TerminalState.Docked || ts == TerminalState.Boarded)
                    return false;
            }

            if (rec.VesselSnapshot == null)
                return false;

            return true;
        }

        /// <summary>
        /// Assigns terminal state based on vessel situation.
        /// Pure static method for testability.
        /// </summary>
        internal static TerminalState DetermineTerminalState(int situation)
        {
            // Vessel.Situations enum values: LANDED=1, SPLASHED=2, PRELAUNCH=4,
            // FLYING=8, SUB_ORBITAL=16, ORBITING=32, ESCAPING=64, DOCKED=128
            switch (situation)
            {
                case 32: // ORBITING
                    return TerminalState.Orbiting;
                case 1: // LANDED
                    return TerminalState.Landed;
                case 2: // SPLASHED
                    return TerminalState.Splashed;
                case 16: // SUB_ORBITAL
                case 8:  // FLYING
                case 64: // ESCAPING
                    return TerminalState.SubOrbital;
                case 4:  // PRELAUNCH
                    return TerminalState.Landed;
                case 128: // DOCKED
                    return TerminalState.Docked;
                default:
                    ParsekLog.Warn("RecordingTree", $"DetermineTerminalState: unexpected situation={situation}, defaulting to SubOrbital");
                    return TerminalState.SubOrbital;
            }
        }

        /// <summary>
        /// Pure decision: is the orbit a stable bound orbit whose periapsis clears
        /// the body's atmosphere (or surface, if the body has no atmosphere)?
        /// Atmospheric grazers — orbits whose periapsis radius lies inside
        /// <paramref name="atmosphereDepth"/> — are excluded because they decay
        /// to destruction within a few orbits via drag. Strict inequality at the
        /// atmosphere top mirrors KSP's drag boundary.
        /// </summary>
        internal static bool IsBoundOrbitAboveAtmosphere(
            double eccentricity,
            double periapsisRadius,
            double bodyRadius,
            bool bodyHasAtmosphere,
            double atmosphereDepth)
        {
            if (!IsFinite(eccentricity)
                || !IsFinite(periapsisRadius)
                || !IsFinite(bodyRadius)
                || bodyRadius <= 0.0)
            {
                return false;
            }

            if (eccentricity >= 1.0)
                return false;

            double effectiveAtmosphereDepth = bodyHasAtmosphere
                && IsFinite(atmosphereDepth)
                && atmosphereDepth > 0.0
                    ? atmosphereDepth
                    : 0.0;
            double minSafePeR = bodyRadius + effectiveAtmosphereDepth;
            return periapsisRadius > minSafePeR;
        }

        /// <summary>
        /// Assigns terminal state based on vessel situation, with orbit-aware override.
        /// KSP can report SUB_ORBITAL for a stable bound orbit, and ORBITING for
        /// a ballistic coast whose periapsis is inside the surface or atmosphere.
        /// This overload checks the vessel's actual orbit to correct both cases.
        /// </summary>
        internal static TerminalState DetermineTerminalState(int situation, Vessel vessel)
        {
            TerminalState baseState = DetermineTerminalState(situation);
            if (vessel?.orbit == null || vessel.orbit.referenceBody == null)
                return baseState;

            var body = vessel.orbit.referenceBody;
            bool bodyHasAtmosphere = body.atmosphere;
            double atmosphereDepth = bodyHasAtmosphere ? body.atmosphereDepth : 0.0;
            TerminalState resolved = DetermineTerminalStateFromOrbitEvidence(
                situation,
                vessel.orbit.eccentricity,
                vessel.orbit.PeR,
                body.Radius,
                bodyHasAtmosphere,
                atmosphereDepth);

            if (baseState == TerminalState.SubOrbital && resolved == TerminalState.Orbiting)
            {
                ParsekLog.Info("RecordingTree",
                    $"DetermineTerminalState: overriding SUB_ORBITAL to Orbiting - vessel has bound orbit " +
                    $"(ecc={vessel.orbit.eccentricity:F4}, PeR={vessel.orbit.PeR:F0}, " +
                    $"bodyR={body.Radius:F0}, atmoTop={atmosphereDepth:F0}, " +
                    $"bodyHasAtmosphere={bodyHasAtmosphere})");
            }
            else if (baseState == TerminalState.Orbiting && resolved == TerminalState.SubOrbital)
            {
                string reason = vessel.orbit.eccentricity >= 1.0
                    ? "orbit evidence is unbound"
                    : vessel.orbit.PeR <= body.Radius
                        ? "periapsis is below surface"
                        : "periapsis is inside atmosphere";
                ParsekLog.Info("RecordingTree",
                    $"DetermineTerminalState: overriding ORBITING to SubOrbital - {reason} " +
                    $"(ecc={vessel.orbit.eccentricity:F4}, PeR={vessel.orbit.PeR:F0}, " +
                    $"bodyR={body.Radius:F0}, atmoTop={atmosphereDepth:F0}, " +
                    $"bodyHasAtmosphere={bodyHasAtmosphere})");
            }

            return resolved;
        }

        internal static TerminalState DetermineTerminalStateFromOrbitEvidence(
            int situation,
            double eccentricity,
            double periapsisRadius,
            double bodyRadius,
            bool bodyHasAtmosphere = false,
            double atmosphereDepth = 0.0)
        {
            TerminalState baseState = DetermineTerminalState(situation);
            if (!IsFinite(eccentricity)
                || !IsFinite(periapsisRadius)
                || !IsFinite(bodyRadius)
                || bodyRadius <= 0.0)
            {
                return baseState;
            }

            if (baseState == TerminalState.SubOrbital
                && situation == 16
                && IsBoundOrbitAboveAtmosphere(
                    eccentricity,
                    periapsisRadius,
                    bodyRadius,
                    bodyHasAtmosphere,
                    atmosphereDepth))
            {
                return TerminalState.Orbiting;
            }

            if (baseState == TerminalState.Orbiting
                && situation == 32
                && !IsBoundOrbitAboveAtmosphere(
                    eccentricity,
                    periapsisRadius,
                    bodyRadius,
                    bodyHasAtmosphere,
                    atmosphereDepth))
            {
                return TerminalState.SubOrbital;
            }

            return baseState;
        }

        private static bool IsFinite(double value)
        {
            return !double.IsNaN(value) && !double.IsInfinity(value);
        }

        static bool IsNonSpawnableTerminal(TerminalState terminalState)
        {
            return terminalState == TerminalState.Destroyed
                || terminalState == TerminalState.Recovered
                || terminalState == TerminalState.Docked
                || terminalState == TerminalState.Boarded;
        }

        /// <summary>
        /// Pure decision method: checks whether all leaf recordings in a tree have
        /// non-spawnable terminal states (Destroyed, Recovered, Docked, Boarded).
        /// A recording is a leaf if it has no ChildBranchPointId.
        /// Leaves with null TerminalStateValue are considered NOT terminal (still active).
        /// If activeRecordingId is non-null, the active recording is treated as alive
        /// unless activeVesselDestroyed is true.
        /// </summary>
        internal static bool AreAllLeavesTerminal(
            Dictionary<string, Recording> recordings,
            string activeRecordingId,
            bool activeVesselDestroyed)
        {
            int total = 0;
            int terminalCount = 0;
            int aliveCount = 0;
            bool result = true;

            // Deliberately scan every leaf here: this is a destruction merge gate,
            // and the log summary is useful only when its counts describe the
            // whole tree. The all-terminal path had to inspect every leaf before
            // this log-hygiene change as well.
            foreach (var kvp in recordings)
            {
                var rec = kvp.Value;

                // Skip non-leaf recordings (they branched into children)
                if (rec.ChildBranchPointId != null)
                    continue;

                total++;
                bool isActiveRecording = activeRecordingId != null && rec.RecordingId == activeRecordingId;
                bool isTerminal;

                // Leaf: active recording still alive — tree is not fully terminal
                if (isActiveRecording && !activeVesselDestroyed)
                {
                    isTerminal = false;
                }
                // Active recording with destroyed vessel: treat as terminal even if
                // TerminalStateValue hasn't been set yet (recorder knows it's dead,
                // but FinalizeTreeRecordings hasn't run to set the terminal state)
                else if (isActiveRecording && activeVesselDestroyed)
                {
                    isTerminal = true;
                }
                // Leaf: no terminal state means still recording / not finalized
                else if (!rec.TerminalStateValue.HasValue)
                {
                    isTerminal = false;
                }
                else
                {
                    var ts = rec.TerminalStateValue.Value;
                    isTerminal = IsNonSpawnableTerminal(ts);
                }

                if (isTerminal)
                {
                    terminalCount++;
                }
                else
                {
                    aliveCount++;
                    result = false;
                }
            }

            ParsekLog.Verbose("TreeDestruction",
                $"AreAllLeavesTerminal: leaves={total} terminal={terminalCount} " +
                $"alive={aliveCount} -> {result}");
            return result;
        }

        /// <summary>
        /// Returns true when the only leaves still blocking same-scene crash finalization
        /// are debris leaves. This is used only to decide whether the active-crash flow
        /// should keep waiting for a debris-only fallback owner; it does NOT make the tree
        /// merge-ready on its own.
        /// </summary>
        internal static bool AreAllActiveCrashBlockersDebris(
            Dictionary<string, Recording> recordings,
            string activeRecordingId)
        {
            bool sawBlockingLeaf = false;

            foreach (var kvp in recordings)
            {
                var rec = kvp.Value;
                if (rec.ChildBranchPointId != null)
                    continue;

                bool isActiveRecording = activeRecordingId != null && rec.RecordingId == activeRecordingId;
                if (isActiveRecording)
                    continue;

                if (!rec.TerminalStateValue.HasValue)
                {
                    sawBlockingLeaf = true;
                    if (!rec.IsDebris)
                        return false;
                    continue;
                }

                if (IsNonSpawnableTerminal(rec.TerminalStateValue.Value))
                    continue;

                sawBlockingLeaf = true;
                if (!rec.IsDebris)
                    return false;
            }

            return sawBlockingLeaf;
        }

    }
}
