using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Parsek.Tests.Analyzer
{
    // The -WriteBaseline authoring builder (design doc "Authoring: -WriteBaseline").
    // Lives in Parsek.Tests beside the codec. Pure with respect to the filesystem
    // (FromReport builds the object; BuildAndWrite adds the codec write + the
    // one-shot path log). Captures FAIL/WARN findings only, preserves human reasons
    // on update, prunes stale entries by default, and skips placeholder-Target
    // findings (each surfaced on a Warn line).
    internal static class BaselineBuilder
    {
        private static readonly CultureInfo IC = CultureInfo.InvariantCulture;

        internal sealed class BaselineBuildResult
        {
            public AnalysisBaseline Baseline;
            public int NewCount;
            public int PreservedCount;
            public int PrunedCount;
            public int KeptStaleCount;
            public int SkippedPlaceholder;
        }

        /// <summary>
        /// Builds a baseline from the TRUE (unfiltered) report. Update semantics:
        /// every FAIL/WARN finding becomes an entry (skipping meta-findings and
        /// placeholder-Target findings); an existing entry that still matches keeps
        /// its human-authored reason; stale entries are pruned unless
        /// <paramref name="keepStale"/> retains them.
        /// </summary>
        internal static BaselineBuildResult FromReport(
            AnalysisReport report, AnalysisBaseline existing, bool keepStale)
        {
            var result = new BaselineBuildResult();
            string version = report?.AnalyzerVersion ?? AnalysisReport.CurrentAnalyzerVersion;

            var existingByKey = new Dictionary<BaselineKey, BaselineEntry>();
            if (existing?.Entries != null)
            {
                foreach (BaselineEntry e in existing.Entries)
                    if (!existingByKey.ContainsKey(e.Key))
                        existingByKey[e.Key] = e;
            }

            var newEntries = new List<BaselineEntry>();
            var seenKeys = new HashSet<BaselineKey>();

            // Deterministic order so the written file is stable across runs.
            foreach (Finding f in ReportWriter.SortFindings(report?.Findings ?? new List<Finding>()))
            {
                if (f.Level != VerdictLevel.Fail && f.Level != VerdictLevel.Warn)
                    continue; // FAIL/WARN only (INFO never gates; STALE is fresh-managed)
                if (BaselineFilter.IsMetaRuleId(f.RuleId))
                    continue; // meta-findings are generated by the filter, not eligible
                if (BaselineFilter.IsPlaceholderTarget(f.Target))
                {
                    result.SkippedPlaceholder++;
                    ParsekLog.Warn("Analyzer",
                        "baseline write skip placeholder-target rule=" + (f.RuleId ?? "")
                        + " target=" + (f.Target ?? ""));
                    continue;
                }

                BaselineKey key = BaselineFilter.KeyOf(f);
                if (seenKeys.Contains(key))
                    continue; // collapse digest-duplicate findings (multi-match) into one entry
                seenKeys.Add(key);

                string reason;
                if (existingByKey.TryGetValue(key, out BaselineEntry prev))
                {
                    reason = prev.Reason;      // preserve the human reason on update
                    result.PreservedCount++;
                }
                else
                {
                    reason = "captured by -WriteBaseline " + version;
                    result.NewCount++;
                }

                newEntries.Add(new BaselineEntry(
                    key.RuleId, key.Target, key.SectionIndex, key.MessageDigest, f.Level, reason));
            }

            // Stale pruning (a still-matching entry, e.g. the immutable INV2 five, is
            // already in newEntries via its live finding and never reaches here).
            if (existing?.Entries != null)
            {
                foreach (BaselineEntry e in existing.Entries)
                {
                    if (seenKeys.Contains(e.Key))
                        continue;
                    if (keepStale)
                    {
                        if (!newEntries.Any(x => x.Key.Equals(e.Key)))
                        {
                            newEntries.Add(e);
                            result.KeptStaleCount++;
                        }
                    }
                    else
                    {
                        result.PrunedCount++;
                    }
                }
            }

            result.Baseline = new AnalysisBaseline
            {
                BaselineFormatVersion = BaselineFormat.CurrentBaselineFormatVersion,
                CreatedAtAnalyzerVersion = version,
                SubjectSchemaGeneration = report?.SubjectSchemaGeneration ?? 0,
                CreatedAtUtc = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", IC),
                Reason = string.IsNullOrEmpty(existing?.Reason)
                    ? "Known findings baseline for save '" + (report?.SaveName ?? "") + "'."
                    : existing.Reason,
                Entries = newEntries,
            };
            return result;
        }

        /// <summary>
        /// Builds the baseline and writes it via the codec, emitting the one-shot
        /// write summary line (with the destination path). The only path that creates
        /// or updates a baseline file.
        /// </summary>
        internal static AnalysisBaseline BuildAndWrite(
            AnalysisReport report, AnalysisBaseline existing, bool keepStale, string path)
        {
            BaselineBuildResult result = FromReport(report, existing, keepStale);
            BaselineCodec.Write(result.Baseline, path);

            ParsekLog.Info("Analyzer",
                "baseline write save='" + (report?.SaveName ?? "") + "'"
                + " entries=" + result.Baseline.Entries.Count
                + " new=" + result.NewCount
                + " preserved=" + result.PreservedCount
                + " pruned=" + result.PrunedCount
                + " keptStale=" + result.KeptStaleCount
                + " skippedPlaceholder=" + result.SkippedPlaceholder
                + " path='" + path + "'");
            return result.Baseline;
        }
    }
}
