using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace Parsek.Analyzer
{
    // The pure reporting-layer baseline filter (design doc
    // docs/dev/design-autotest-findings-baseline.md). It sits between the
    // evaluator's findings and the verdict: it marks findings Baselined, emits
    // meta-findings, and recomputes Counts / IsRed. It NEVER touches a file (the
    // codec + builder in Parsek.Tests own all I/O and hand it the loaded baseline +
    // fault list). Rules, AnalyzerModel, and InvariantEvaluator never know it
    // exists. No store symbol is referenced here (ERS grep gate stays clean).
    internal static class BaselineFilter
    {
        // Meta-finding rule ids. All start "BASELINE-" so the builder can exclude
        // them from capture by prefix (they are generated by the filter, never
        // baseline-eligible).
        internal const string StaleEntryRuleId = "BASELINE-STALE-ENTRY";        // INFO, per-entry
        internal const string MultiMatchRuleId = "BASELINE-MULTI-MATCH";        // WARN, per-entry
        internal const string SeverityEscalatedRuleId = "BASELINE-SEVERITY-ESCALATED"; // WARN, per-entry
        internal const string EntryMalformedRuleId = "BASELINE-ENTRY-MALFORMED"; // WARN, per-entry
        internal const string DuplicateEntryRuleId = "BASELINE-DUPLICATE-ENTRY"; // WARN, per-entry
        internal const string ParseFaultRuleId = "BASELINE-PARSE-FAULT";        // FAIL, file-level
        internal const string VersionFutureRuleId = "BASELINE-VERSION-FUTURE";  // FAIL, file-level
        internal const string ForbiddenRuleId = "BASELINE-FORBIDDEN";           // FAIL, file-level
        internal const string NotFoundRuleId = "BASELINE-NOT-FOUND";            // INFO, file-level
        internal const string PresentNotAppliedRuleId = "BASELINE-PRESENT-NOT-APPLIED"; // INFO, file-level
        internal const string RefusedStampedRuleId = "BASELINE-REFUSED-STAMPED"; // WARN, file-level

        private const string CitedApply = "BaselineFilter.Apply";
        private const string CitedCodec = "BaselineCodec.Load";

        private const string PlaceholderTombstone = "<tombstone>";
        private const string PlaceholderSupersede = "<supersede>";

        // A maximal numeric literal: optional sign, an integer/decimal mantissa, an
        // optional binding exponent. A '-' or '+' not immediately followed by a
        // number (e.g. inside "field-name") does not start a match and stays literal.
        private static readonly Regex NumberRun =
            new Regex(@"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?", RegexOptions.Compiled);

        /// <summary>
        /// Masks every numeric literal in a finding message with a single '#', so the
        /// matching key is stable against value drift but still distinguishes
        /// structurally different messages. GUID-hex ids keep their letters, so two
        /// different ids still yield different digests.
        /// </summary>
        internal static string NormalizeMessageDigest(string message)
        {
            if (string.IsNullOrEmpty(message))
                return message ?? "";
            return NumberRun.Replace(message, "#");
        }

        /// <summary>A placeholder Target names a MUTABLE row population shared across
        /// findings; it is never stable enough to baseline.</summary>
        internal static bool IsPlaceholderTarget(string target)
        {
            return string.Equals(target, PlaceholderTombstone, StringComparison.Ordinal)
                || string.Equals(target, PlaceholderSupersede, StringComparison.Ordinal);
        }

        /// <summary>The matching key for a live finding.</summary>
        internal static BaselineKey KeyOf(Finding f)
        {
            return new BaselineKey(f.RuleId, f.Target, f.SectionIndex, NormalizeMessageDigest(f.Message));
        }

        /// <summary>True when this finding is a filter-generated meta-finding (never
        /// baseline-eligible).</summary>
        internal static bool IsMetaRuleId(string ruleId)
        {
            return ruleId != null && ruleId.StartsWith("BASELINE-", StringComparison.Ordinal);
        }

        /// <summary>
        /// Applies the baseline to the report per <paramref name="mode"/>, then
        /// recomputes Counts / IsRed. Pure: the caller supplies whether a baseline
        /// file existed (<paramref name="baselinePresent"/>) and the codec's fault
        /// list (<paramref name="loadFaults"/>), so the filter never touches disk.
        /// </summary>
        internal static void Apply(
            AnalysisReport report,
            AnalysisBaseline baseline,
            BaselineMode mode,
            bool baselinePresent,
            IReadOnlyList<BaselineLoadFault> loadFaults)
        {
            if (report == null)
                return;
            loadFaults = loadFaults ?? new List<BaselineLoadFault>();
            string saveTarget = report.SaveName ?? "<save>";
            int entryCount = baseline?.Entries?.Count ?? 0;

            // One-shot load line (design "Diagnostic Logging"). The createdAtVersion
            // note folds the edge-case-8 version-difference message in here.
            ParsekLog.Info("Analyzer",
                "baseline mode=" + mode + " present=" + baselinePresent
                + " entries=" + entryCount
                + " formatVersion=" + (baseline?.BaselineFormatVersion ?? 0)
                + " createdAtVersion=" + (baseline?.CreatedAtAnalyzerVersion ?? ""));

            switch (mode)
            {
                case BaselineMode.Ignore:
                    if (baselinePresent)
                        AddMeta(report, PresentNotAppliedRuleId, VerdictLevel.Info, saveTarget, -1,
                            "baseline present but mode=Ignore; not applied", CitedApply);
                    break;

                case BaselineMode.Forbid:
                    if (baselinePresent)
                    {
                        AddMeta(report, ForbiddenRuleId, VerdictLevel.Fail, saveTarget, -1,
                            "fresh-save context carries a baseline; forbidden", CitedApply);
                        ParsekLog.Warn("Analyzer",
                            "baseline FORBIDDEN save='" + (report.SaveName ?? "")
                            + "' - fresh-save context carries a baseline");
                    }
                    break;

                case BaselineMode.Apply:
                    ApplyMode(report, baseline, baselinePresent, loadFaults, saveTarget);
                    break;
            }

            Recompute(report);
        }

        private static void ApplyMode(
            AnalysisReport report,
            AnalysisBaseline baseline,
            bool baselinePresent,
            IReadOnlyList<BaselineLoadFault> loadFaults,
            string saveTarget)
        {
            // 1. Codec faults become findings first (loud, never silent). A HARD
            //    fault (parse / future-version) aborts matching: a broken baseline
            //    must neither silently un-suppress nor silently suppress.
            bool hard = false;
            foreach (BaselineLoadFault fault in loadFaults)
            {
                switch (fault.Kind)
                {
                    case BaselineFaultKind.ParseFault:
                        hard = true;
                        AddMeta(report, ParseFaultRuleId, VerdictLevel.Fail, saveTarget, -1,
                            "baseline parse fault: " + fault.Detail, CitedCodec);
                        ParsekLog.Warn("Analyzer",
                            "baseline parse-fault path='" + (fault.Target ?? "") + "' reason=" + fault.Detail);
                        break;
                    case BaselineFaultKind.VersionFuture:
                        hard = true;
                        AddMeta(report, VersionFutureRuleId, VerdictLevel.Fail, saveTarget, -1,
                            "baseline format version too new: " + fault.Detail, CitedCodec);
                        ParsekLog.Warn("Analyzer",
                            "baseline version-future path='" + (fault.Target ?? "") + "' " + fault.Detail);
                        break;
                    case BaselineFaultKind.EntryMalformed:
                        AddMeta(report, EntryMalformedRuleId, VerdictLevel.Warn,
                            fault.Target ?? saveTarget, -1,
                            "malformed entry dropped: " + fault.Detail, CitedCodec);
                        break;
                    case BaselineFaultKind.DuplicateEntry:
                        AddMeta(report, DuplicateEntryRuleId, VerdictLevel.Warn,
                            fault.Target ?? saveTarget, -1,
                            "duplicate entry deduped: " + fault.Detail, CitedCodec);
                        break;
                }
            }

            if (hard)
                return; // do not match; the hard FAIL reds the run

            if (!baselinePresent || baseline == null)
            {
                if (!baselinePresent)
                    AddMeta(report, NotFoundRuleId, VerdictLevel.Info, saveTarget, -1,
                        "Apply requested but no baseline file present; every finding surfaces", CitedApply);
                return;
            }

            // 2. Stamped-fixture refusal (before any matching): the fresh-managed
            //    STALE-FIXTURE scope must never be softened by a baseline.
            if (report.SubjectIsStampedFixture)
            {
                AddMeta(report, RefusedStampedRuleId, VerdictLevel.Warn, saveTarget, -1,
                    "Apply refused: subject is a stamped fixture", CitedApply);
                ParsekLog.Warn("Analyzer",
                    "baseline refused-stamped save='" + (report.SaveName ?? "") + "' - stamped fixture scope");
                return;
            }

            // 3. The match sweep.
            MatchSweep(report, baseline);
        }

        private static void MatchSweep(AnalysisReport report, AnalysisBaseline baseline)
        {
            Dictionary<BaselineKey, BaselineEntry> index = baseline.BuildIndex();

            // Deterministic finding order (same total order the writer uses) so the
            // "FIRST match" of a multi-match is stable run to run.
            List<int> order = OrderedFindingIndices(report.Findings);

            var matchCount = new Dictionary<BaselineKey, int>();
            var seenEntries = new HashSet<BaselineKey>();
            int matched = 0, baselined = 0, escalated = 0;

            foreach (int i in order)
            {
                Finding f = report.Findings[i];
                if (f.Level == VerdictLevel.StaleFixture)
                    continue; // STALE-FIXTURE is never baselined (fresh-managed scope)
                if (IsMetaRuleId(f.RuleId))
                    continue; // meta-findings are not baseline-eligible
                if (IsPlaceholderTarget(f.Target))
                    continue; // placeholder Target findings always gate

                BaselineKey key = KeyOf(f);
                if (!index.TryGetValue(key, out BaselineEntry entry))
                    continue;

                seenEntries.Add(key); // the entry matched -> it is not stale
                matched++;

                // Severity escalation: current level EXCEEDS captured (Info<Warn<Fail).
                // Not baselined; the FAIL surfaces and the WARN explains why the stale
                // low-severity entry did not silence it.
                if ((int)f.Level > (int)entry.CapturedLevel)
                {
                    escalated++;
                    string msg = "escalated captured=" + Token(entry.CapturedLevel)
                        + " now=" + Token(f.Level) + " notBaselined";
                    AddMeta(report, SeverityEscalatedRuleId, VerdictLevel.Warn,
                        entry.Target, entry.SectionIndex, msg, CitedApply);
                    ParsekLog.Warn("Analyzer",
                        "baseline escalated rule=" + entry.RuleId
                        + " target=" + entry.Target + "#" + entry.SectionIndex
                        + " captured=" + Token(entry.CapturedLevel)
                        + " now=" + Token(f.Level) + " notBaselined");
                    continue;
                }

                int prior = matchCount.TryGetValue(key, out int c) ? c : 0;
                matchCount[key] = prior + 1;
                if (prior == 0)
                {
                    // One-match-per-entry-per-run: the FIRST match is baselined.
                    f.Baselined = true;
                    report.Findings[i] = f;
                    baselined++;
                }
                // else: surplus match stays UNBASELINED and gates (multi-match below).
            }

            // Multi-match WARNs, deterministic order (a surplus non-baselined match
            // can red the run, so this is WARN, not INFO).
            int multiMatch = 0;
            foreach (BaselineKey key in SortedKeys(matchCount.Keys))
            {
                int count = matchCount[key];
                if (count <= 1)
                    continue;
                multiMatch++;
                BaselineEntry entry = index[key];
                AddMeta(report, MultiMatchRuleId, VerdictLevel.Warn, entry.Target, entry.SectionIndex,
                    "multi-match count=" + count + " baselinedFirst surplusUnbaselined=" + (count - 1),
                    CitedApply);
                ParsekLog.Warn("Analyzer",
                    "baseline multi-match rule=" + entry.RuleId
                    + " target=" + entry.Target + "#" + entry.SectionIndex
                    + " count=" + count + " baselinedFirst surplusUnbaselined=" + (count - 1));
            }

            // Stale entries (matched nothing), deterministic order.
            int stale = 0;
            foreach (BaselineKey key in SortedKeys(index.Keys))
            {
                if (seenEntries.Contains(key))
                    continue;
                stale++;
                BaselineEntry entry = index[key];
                AddMeta(report, StaleEntryRuleId, VerdictLevel.Info, entry.Target, entry.SectionIndex,
                    "stale-entry rule=" + entry.RuleId + " no live finding matched", CitedApply);
                ParsekLog.Verbose("Analyzer",
                    "baseline stale-entry rule=" + entry.RuleId
                    + " target=" + entry.Target + "#" + entry.SectionIndex);
            }

            // One summary line after the sweep (batch-counting convention).
            ParsekLog.Info("Analyzer",
                "baseline applied matched=" + matched + " baselined=" + baselined
                + " stale=" + stale + " multiMatch=" + multiMatch + " escalated=" + escalated);
        }

        private static void Recompute(AnalysisReport report)
        {
            report.Counts = Counts.From(report.Findings);
            ParsekLog.Info("Analyzer",
                "verdict red=" + (report.IsRed ? "1" : "0")
                + " failNonBaselined=" + report.Counts.FailNonBaselined
                + " staleNonBaselined=" + report.Counts.StaleNonBaselined
                + " failBaselined=" + (report.Counts.Fail - report.Counts.FailNonBaselined));
        }

        private static void AddMeta(
            AnalysisReport report, string ruleId, VerdictLevel level,
            string target, int sectionIndex, string message, string cited)
        {
            report.Findings.Add(new Finding(ruleId, level, target, sectionIndex, message, cited));
        }

        /// <summary>Indices into <paramref name="findings"/> in the deterministic
        /// report total order (level desc, ruleId, target, sectionIndex).</summary>
        private static List<int> OrderedFindingIndices(List<Finding> findings)
        {
            var idx = new List<int>(findings.Count);
            for (int i = 0; i < findings.Count; i++)
                idx.Add(i);
            idx.Sort((a, b) =>
            {
                Finding fa = findings[a];
                Finding fb = findings[b];
                int c = ((int)fb.Level).CompareTo((int)fa.Level); // level DESC
                if (c != 0) return c;
                c = string.CompareOrdinal(fa.RuleId ?? "", fb.RuleId ?? "");
                if (c != 0) return c;
                c = string.CompareOrdinal(fa.Target ?? "", fb.Target ?? "");
                if (c != 0) return c;
                c = fa.SectionIndex.CompareTo(fb.SectionIndex);
                if (c != 0) return c;
                return a.CompareTo(b); // stable tiebreak on original position
            });
            return idx;
        }

        private static IEnumerable<BaselineKey> SortedKeys(IEnumerable<BaselineKey> keys)
        {
            return keys.OrderBy(k => k.RuleId ?? "", StringComparer.Ordinal)
                .ThenBy(k => k.Target ?? "", StringComparer.Ordinal)
                .ThenBy(k => k.SectionIndex)
                .ThenBy(k => k.MessageDigest ?? "", StringComparer.Ordinal);
        }

        private static string Token(VerdictLevel level)
        {
            switch (level)
            {
                case VerdictLevel.Fail: return "FAIL";
                case VerdictLevel.Warn: return "WARN";
                case VerdictLevel.StaleFixture: return "STALE";
                default: return "INFO";
            }
        }
    }
}
